### ISSUE TITLE
build failing with micromamba 0.26

### ISSUE THREAD

**Issue by mdespriee** [mamba-org/mamba#1977] opened 2022-10-03 10:05 UTC
Our docker builds based on micromamba are failing since the update to 0.26.

```
Step 4/8 : RUN micromamba install -y -n base -f demeter.yml &&     micromamba clean --all --yes
 ---> Running in 996bec140c16
info     libmamba ****************** Backtrace Start ******************
debug    libmamba Loading configuration
trace    libmamba Compute configurable 'create_base'
trace    libmamba Compute configurable 'no_env'
trace    libmamba Compute configurable 'no_rc'
trace    libmamba Compute configurable 'rc_files'
trace    libmamba Compute configurable 'root_prefix'
trace    libmamba Get RC files configuration from locations up to HomeDir
trace    libmamba Configuration not found at '/home/mambauser/.mambarc'
trace    libmamba Configuration not found at '/home/mambauser/.condarc'
trace    libmamba Configuration not found at '/home/mambauser/.conda/condarc.d'
trace    libmamba Configuration not found at '/home/mambauser/.conda/condarc'
trace    libmamba Configuration not found at '/home/mambauser/.conda/.condarc'
trace    libmamba Configuration not found at '/opt/conda/.mambarc'
trace    libmamba Configuration not found at '/opt/conda/condarc.d'
trace    libmamba Configuration not found at '/opt/conda/condarc'
trace    libmamba Configuration not found at '/opt/conda/.condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.mambarc'
trace    libmamba Configuration not found at '/var/lib/conda/condarc.d/'
trace    libmamba Configuration not found at '/var/lib/conda/condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.condarc'
trace    libmamba Configuration not found at '/etc/conda/.mambarc'
trace    libmamba Configuration not found at '/etc/conda/condarc.d/'
trace    libmamba Configuration not found at '/etc/conda/condarc'
trace    libmamba Configuration not found at '/etc/conda/.condarc'
trace    libmamba Update configurable 'no_env'
trace    libmamba Compute configurable 'file_specs'
critical libmamba filesystem error: cannot make absolute path: Invalid argument []
info     libmamba ****************** Backtrace End ********************
```

OS is ubuntu 22.04

**Comment by jonashaag** [comment] 2022-10-03 10:14
Dupe of #1975

**Closed by jonashaag** 2022-10-03 10:14 UTC
