### ISSUE TITLE
Package cache does not take channel/platform into consideration

### ISSUE THREAD

**Issue by calebzulawski** [mamba-org/mamba#1027] opened 2021-06-21 18:08 UTC
My micromamba use case involves using various channels and platforms on a single machine.  If I download a particular package for `linux-64`, when I try to download the same package again for `linux-aarch64`, I get the `linux-64` package instead.

I am currently working around this by hashing the channels and platform and using that to generate a unique prefix for each combination, but it would be nice if micromamba did something like that automatically.

**Comment by adriendelsalle** [comment] 2021-06-22 17:40
Hi @calebzulawski thanks for opening this issue!

The cache is/should be specific to a `subdir`, which is `<channel>/<os>-<platform>`. This looks like a bug.
Could you please provide a minimal example to reproduce that behavior?

**Comment by wolfv** [comment] 2021-06-22 18:09
@adriendelsalle I believe what this is talking about is hash collisions in packages themselves (in the package cache).

E.g. there could be a `xtensor-0.20-xxx` package with the same hash for linux-64 and linux-aarch64.

I've experimented with this in boa (whihc is why we can set the package cahce dir seperately), but we haven't added this functionality into core mamba yet as it would break conda-compatibility to some degree.

What we could do though is for all non-host platforms create another cache subdir, e.g. `/pkgs/linux-aarch64/...` and put tarballs + extracted packages there. However, it will complicate the logic quite a bit as the noarch cache dir would be different etc.

**Comment by calebzulawski** [comment] 2021-06-22 18:16
@wolfv I just tested this and came to the same conclusion.  The packages I am talking about have the same build strings (they are not hashes, unlike in conda-forge etc) and therefore collide.

Separating the platforms would help, but there is also the collision that can occur if two channels provide the same package for the same architecture (this also occurs in my use case, unfortunately).

**Comment by wolfv** [comment] 2021-06-22 18:25
are these packages very old? In new packages conda-build adds the target platform as part of the hash, and quite some other information so that it shouldn't be (as much of a) problem.

Maybe you can rebuild these packages with the latest conda-build?

**Comment by adriendelsalle** [comment] 2021-06-22 19:22
Ok I see thanks!

I'm a bit surprised that at the second operation the cache is not detected as corrupted because not matching some properties such as size and checksums.
In that case the cache would be deleted, keeping the previously created env unchanged (if using hard links or copy), then linking the new env against the right files freshly downloaded.

The only case would be with old packages not providing those metadata, I'm talking about those [lines](https://github.com/mamba-org/mamba/blob/e7a8caea03a70c1efefb243001e50f2dcff8fd20/src/core/package_cache.cpp#L155).
Am I wrong with that?

**Comment by wolfv** [comment] 2021-06-22 20:10
that might well be the case, but previously created environments would also be kinda broken through that (although with hard links they would prob still work in some capacity). And in general it's annoying to re-download the packages over and over.

**Comment by adriendelsalle** [comment] 2021-06-22 20:42
Yep I agree that this cache overriding is definitely not great..
The env should be fully functional if all files are hard linked or copied from the cache.

**Comment by calebzulawski** [comment] 2021-06-23 14:15
These packages are not built with conda-build, so the build string is not a hash at all, which I'm guessing is the only reason this shows up for me.

**Comment by afranchuk** [comment] 2021-12-14 14:08
Note that this issue would be fixed with a similar change to what @mingwandroid suggests in https://github.com/conda/conda-build/issues/3155 (that's a conda-build issue but the resolution is to make a change in conda). Also seems like such a change would be simple.

**Comment by jjerphan** [comment] 2024-12-03 09:53
This has been fixed by https://github.com/conda/conda-build/pull/4065.

**Closed by jjerphan** 2024-12-03 09:53 UTC
Labels: type::feature-request
