### ISSUE TITLE
Invalid cross-device link when running micromamba create

### ISSUE THREAD

**Issue by chrisburr** [mamba-org/mamba#650] opened 2021-01-07 08:34 UTC
I don't have a easy reproducer to hand as this was in a private CI pipeline but the latest micromamba has fails when creating environments on a different device than the root prefix:

```
Linking ld_impl_linux-64-2.35.1-hed1e6ac_1
terminate called after throwing an instance of 'ghc::filesystem::filesystem_error'
  what():  Invalid cross-device link: '/root/micromamba/pkgs/ld_impl_linux-64-2.35.1-hed1e6ac_1/bin/x86_64-conda-linux-gnu-ld', '/builds/cburr/lbmc-prototyping/test-env/bin/x86_64-conda-linux-gnu-ld'
/usr/bin/bash: line 174:    18 Aborted                 (core dumped) "/builds/cburr/lbmc-prototyping/bin/micromamba" "$cmd" "$@"
```

**Comment by wolfv** [comment] 2021-01-07 09:07
Hi, yes, this happens when attempting to link between devices (e.g. mounted hard drive, mounted volume in a docker container etc.)

A workaround is to have the `pkgs` cache folder and the target prefix location on the same device. 

The real fix is to fall back to either sym-linking or file copying instead of using hard links.

**Comment by wolfv** [comment] 2021-01-11 13:28
This is actually a duplicate of https://github.com/mamba-org/mamba/issues/260

**Closed by wolfv** 2021-01-11 13:28 UTC
