### ISSUE TITLE
Unable to install local packages

### ISSUE THREAD

**Issue by hoffenbauer** [mamba-org/mamba#2938] opened 2023-10-25 18:02 UTC
### Troubleshooting docs

- [x] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

local solve, --offline

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

I'm trying to install packages locally in a computer without internet connection. All the packages and their dependencies are within the folder, but micromamba is unable to look for them locally to solve the dependencies.

I'm new to using micromamba, I apologize in advance if this a silly problem, but I couldn't find the solution in the docs, troubleshooting or the issues. 

### mamba info / micromamba info

```shell
libmamba version : 1.5.1
     micromamba version : 1.5.1
           curl version : libcurl/8.4.0 OpenSSL/3.1.3 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /home/alhur/micromamba/envs
          package cache : /home/alhur/micromamba/pkgs
            environment : test_env (active)
           env location : /home/alhur/micromamba/envs/test_env
      user config files : /home/alhur/.mambarc
 populated config files : /home/alhur/.condarc
       virtual packages : __unix=0=0
                          __linux=3.10.0=0
                          __glibc=2.17=0
                          __archspec=1=x86_64
               channels : file:///home/alhur/packages/linux-64
                          file:///home/alhur/packages/noarch
       base environment : /home/alhur/micromamba
               platform : linux-64
```

### Logs

```shell
$ micromamba install --channel ~/pkgs python=3.12 --offline
file:///home/alhur/packages/linux-64 (check zst) Checked  0.0s
file:///home/alhur/packages/noarch (check zst)   Checked  0.0s
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ python 3.12**  is not installable because it requires
       └─ libgcc-ng >=12 , which does not exist (perhaps a missing channel).

ls ~/packages/libgcc*
/home/alhur/packages/libgcc-ng-13.2.0-h807b86a_2.conda
```

### ~/.condarc

```yaml
channels:
- ${HOME}/packages

envs_dirs:
- ${HOME}/micromamba/envs

pkgs_dirs:
- ${HOME}/micromamba/pkgs

offline: True
```

**Comment by Hind-M** [comment] 2023-11-16 09:38
According to the logs, `python 3.12` depends on `libgcc-ng` which is not available locally.

**Comment by jjerphan** [comment] 2024-12-06 12:16
As mentioned by Hind, You need to have `libgcc-ng` in your local caches for packages which depend on it to be installable in the environment.

I cannot reproduce the problem with 2.0 with caches containing `libgcc-ng`, so I am closing this issue as not planned. Feel free to comment or reopen this issue if you still have a problem.

**Closed by jjerphan** 2024-12-06 12:16 UTC
