### ISSUE TITLE
mamba uninstall xyzzy --force is different compared to conda

### ISSUE THREAD

**Issue by looooo** [mamba-org/mamba#1740] opened 2022-06-11 13:47 UTC
I just moved some scripts to use mamba instead of conda and found that `mamba uninstall xyzzy --force` results in deleting all the dependent packages too (at least I guess this is happening). The equivalent conda command uninstalls only the selected package.

**Comment by jonashaag** [comment] 2022-06-11 20:24
Duplicate of https://github.com/mamba-org/mamba/issues/1523?

**Closed** 2022-09-13 13:51 UTC
