### ISSUE TITLE
mamba installs PyTorch CPU version instead of the CUDA version

### ISSUE THREAD

**Issue by bryant1410** [mamba-org/mamba#1349] opened 2021-12-14 08:24 UTC
Given this `environment.yml` file:

```yaml
name: test
channels:
  - pytorch
dependencies:
  - tensorflow=2.5.0
  - six=1.15.0
  - regex=2021.7.6
  - numpy
  - pytorch=1.8.1
  - nltk=3.6.2
  - cudatoolkit=10.2
  - python=3.9
  - sentencepiece
```

`mamba env create` installs the CPU version of PyTorch (`py3.9_cpu_0`) but the CUDA one should be installed instead.

I'm using mamba 0.19.1 and conda 4.11.0 on Linux.

**Comment by jeanmonet** [comment] 2022-01-08 15:54
Maybe not related, but I've solved this once by choosing the correct cudatookit version (https://stackoverflow.com/a/70536292/11750716).
In your case, is cudatoolkit 10.2 compatible with pytorch 1.8.1?

**Comment by bryant1410** [comment] 2022-01-08 16:07
Yes, it is.

**Comment by wolfv** [comment] 2022-01-26 10:37
This used to be an issue before pytorch moved to a `mutex` package: https://github.com/pytorch/builder/pull/823

I am not sure at what version that happened though.

**Comment by wolfv** [comment] 2022-01-26 10:38
Duplicate of #336

**Closed by wolfv** 2022-01-26 10:38 UTC

**Comment by bryant1410** [comment] 2022-02-24 22:01
@wolfv it's not a duplicate because #336 is about installing the cpuonly version, while here I want to do the opposite.

I still see this issue is happening for PyTorch 1.10.2.

**Comment by pjb7687** [comment] 2022-03-23 14:21
@wolfv I also have the same issue too. This is absolutely not a duplicate of #336. This is the exact opposite case, Mamba only installs the CPU version of PyTorch. See below log, Mamba attempts to install PyTorch "cpu_py310h2272b30_0".

```
> mamba install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch # https://pytorch.org/get-started/locally/

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.22.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['pytorch', 'torchvision', 'torchaudio', 'cudatoolkit=11.3']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
pkgs/main/linux-64                                            No change
pkgs/main/noarch                                              No change
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change
pytorch/noarch                                                No change
pytorch/linux-64                                              No change
Transaction

  Prefix: /home/parkj/miniconda3/envs/testenv

  Updating specs:

   - pytorch
   - torchvision
   - torchaudio
   - cudatoolkit=11.3


  Package                  Version  Build                Channel                    Size
──────────────────────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex              0.1  conda_forge          conda-forge/linux-64     Cached
  + _openmp_mutex              4.5  1_gnu                conda-forge/linux-64     Cached
  + brotlipy                 0.7.0  py310h6acc77f_1003   conda-forge/linux-64     Cached
  + bzip2                    1.0.8  h7f98852_4           conda-forge/linux-64     Cached
  + ca-certificates      2021.10.8  ha878542_0           conda-forge/linux-64     Cached
  + certifi              2021.10.8  py310hff52083_1      conda-forge/linux-64     Cached
  + cffi                    1.15.0  py310h0fdd8cc_0      conda-forge/linux-64     Cached
  + charset-normalizer      2.0.12  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + cryptography            36.0.2  py310h597c629_0      conda-forge/linux-64     Cached
  + cudatoolkit             11.3.1  ha36c431_10          conda-forge/linux-64     Cached
  + ffmpeg                   4.3.2  h37c90e5_3           conda-forge/linux-64     Cached
  + freetype                2.10.4  h0708190_1           conda-forge/linux-64     Cached
  + giflib                   5.2.1  h36c2ea0_2           conda-forge/linux-64     Cached
  + gmp                      6.2.1  h58526e2_0           conda-forge/linux-64     Cached
  + gnutls                  3.6.13  h85f3911_1           conda-forge/linux-64     Cached
  + idna                       3.3  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + intel-openmp          2022.0.1  h06a4308_3633        pkgs/main/linux-64       Cached
  + jbig                       2.1  h7f98852_2003        conda-forge/linux-64     Cached
  + jpeg                        9e  h7f98852_0           conda-forge/linux-64     Cached
  + lame                     3.100  h7f98852_1001        conda-forge/linux-64     Cached
  + lcms2                     2.12  hddcbb42_0           conda-forge/linux-64     Cached
  + ld_impl_linux-64        2.36.1  hea4e1c9_2           conda-forge/linux-64     Cached
  + lerc                       3.0  h9c3ff4c_0           conda-forge/linux-64     Cached
  + libblas                  3.9.0  13_linux64_mkl       conda-forge/linux-64     Cached
  + libcblas                 3.9.0  13_linux64_mkl       conda-forge/linux-64     Cached
  + libdeflate                1.10  h7f98852_0           conda-forge/linux-64     Cached
  + libffi                   3.4.2  h7f98852_5           conda-forge/linux-64     Cached
  + libgcc-ng               11.2.0  h1d223b6_14          conda-forge/linux-64     Cached
  + libgomp                 11.2.0  h1d223b6_14          conda-forge/linux-64     Cached
  + liblapack                3.9.0  13_linux64_mkl       conda-forge/linux-64     Cached
  + libnsl                   2.0.0  h7f98852_0           conda-forge/linux-64     Cached
  + libpng                  1.6.37  h21135ba_2           conda-forge/linux-64     Cached
  + libprotobuf             3.19.4  h780b84a_0           conda-forge/linux-64     Cached
  + libstdcxx-ng            11.2.0  he4da1e4_14          conda-forge/linux-64     Cached
  + libtiff                  4.3.0  h542a066_3           conda-forge/linux-64     Cached
  + libuuid                 2.32.1  h7f98852_1000        conda-forge/linux-64     Cached
  + libwebp                  1.2.2  h3452ae3_0           conda-forge/linux-64     Cached
  + libwebp-base             1.2.2  h7f98852_1           conda-forge/linux-64     Cached
  + libxcb                    1.13  h7f98852_1004        conda-forge/linux-64     Cached
  + libzlib                 1.2.11  h36c2ea0_1013        conda-forge/linux-64     Cached
  + lz4-c                    1.9.3  h9c3ff4c_1           conda-forge/linux-64     Cached
  + mkl                   2022.0.1  h06a4308_117         pkgs/main/linux-64       Cached
  + ncurses                    6.3  h9c3ff4c_0           conda-forge/linux-64     Cached
  + nettle                     3.6  he412f7d_0           conda-forge/linux-64     Cached
  + ninja                   1.10.2  h4bd325d_1           conda-forge/linux-64     Cached
  + numpy                   1.22.3  py310h45f3432_0      conda-forge/linux-64        7MB
  + openh264                 2.1.1  h780b84a_0           conda-forge/linux-64     Cached
  + openjpeg                 2.4.0  hb52868f_1           conda-forge/linux-64     Cached
  + openssl                 1.1.1l  h7f98852_0           conda-forge/linux-64     Cached
  + pillow                   9.0.1  py310he619898_2      conda-forge/linux-64     Cached
  + pip                     22.0.4  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + pthread-stubs              0.4  h36c2ea0_1001        conda-forge/linux-64     Cached
  + pycparser                 2.21  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + pyopenssl               22.0.0  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + pysocks                  1.7.1  py310hff52083_4      conda-forge/linux-64     Cached
  + python                  3.10.2  h85951f9_4_cpython   conda-forge/linux-64     Cached
  + python_abi                3.10  2_cp310              conda-forge/linux-64     Cached
  + pytorch                 1.11.0  cpu_py310h2272b30_0  conda-forge/linux-64     Cached
  + pytorch-mutex              1.0  cuda                 pytorch/noarch           Cached
  + readline                   8.1  h46c0cb4_0           conda-forge/linux-64     Cached
  + requests                2.27.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + setuptools             60.10.0  py310hff52083_0      conda-forge/linux-64     Cached
  + sleef                    3.5.1  h9b69904_2           conda-forge/linux-64     Cached
  + sqlite                  3.37.1  h4ff8645_0           conda-forge/linux-64     Cached
  + tk                      8.6.12  h27826a3_0           conda-forge/linux-64     Cached
  + torchaudio              0.11.0  py310_cu113          pytorch/linux-64         Cached
  + torchvision             0.12.0  cpu_py310h3f5528d_0  conda-forge/linux-64     Cached
  + typing_extensions        4.1.1  pyha770c72_0         conda-forge/noarch       Cached
  + tzdata                   2022a  h191b570_0           conda-forge/noarch       Cached
  + urllib3                 1.26.9  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + wheel                   0.37.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + x264                1!161.3030  h7f98852_1           conda-forge/linux-64     Cached
  + xorg-libxau              1.0.9  h7f98852_0           conda-forge/linux-64     Cached
  + xorg-libxdmcp            1.1.3  h7f98852_0           conda-forge/linux-64     Cached
  + xz                       5.2.5  h516909a_1           conda-forge/linux-64     Cached
  + zlib                    1.2.11  h36c2ea0_1013        conda-forge/linux-64     Cached
  + zstd                     1.5.2  ha95c52a_0           conda-forge/linux-64     Cached

  Summary:

  Install: 77 packages

  Total download: 7MB

──────────────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n]
```
