### ISSUE TITLE
Most mamba commands stopped working after updating conda to 24.11.0 and mamba to 1.5.11

### ISSUE THREAD

**Issue by jtabox** [mamba-org/mamba#3637] opened 2024-11-27 12:28 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

conda reactivate command not found

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

As the title says, running `mamba install` or `mamba update --all` (or some specific environment instead) exits with the following error: `__conda_reactivate: command not found`. This started happening after I updated from `conda-24.9.2` to `conda-24.11.0`, and `mamba`, `libmamba` and `libmambapy` from `1.5.10` to `1.5.11`.

It happens exclusively when using the mamba commands, as their conda counterparts seem to work fine. In the examples below, I had to revert to revision 82 for the issue to disappear, and running `mamba install --revision 82` wouldn't work so I had to run its conda counterpart.

I assume this is a problem with mamba, but if I should post it in conda's repo please let me know.

### mamba info / micromamba info

```shell
2024-11-23 00:26:46  (rev 83)
     libmamba  {1.5.10 (conda-forge/linux-64) -> 1.5.11 (conda-forge/linux-64)}
     libmambapy  {1.5.10 (conda-forge/linux-64) -> 1.5.11 (conda-forge/linux-64)}
     mamba  {1.5.10 (conda-forge/linux-64) -> 1.5.11 (conda-forge/linux-64)}
     setuptools  {75.5.0 (conda-forge/noarch) -> 75.6.0 (conda-forge/noarch)}

2024-11-23 16:51:00  (rev 84)
     libssh2  {1.11.0 (conda-forge/linux-64) -> 1.11.1 (conda-forge/linux-64)}
     wheel  {0.45.0 (conda-forge/noarch) -> 0.45.1 (conda-forge/noarch)}

2024-11-25 18:06:05  (rev 85)
     c-ares  {1.34.3 (conda-forge/linux-64) -> 1.34.3 (conda-forge/linux-64)}
     conda  {24.9.2 (conda-forge/linux-64) -> 24.11.0 (conda-forge/linux-64)}
     tqdm  {4.67.0 (conda-forge/noarch) -> 4.67.1 (conda-forge/noarch)}
```

### Logs

```shell
>> mamba install --revision 82

Looking for: []

conda-forge/noarch                                  17.5MB @  28.9MB/s  0.8s
conda-forge/linux-64                                40.1MB @  40.1MB/s  1.5s

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: /home/jtabox/progs/miniforge3

  All requested packages already installed

13.51s user 1.07s system 92% cpu 15.682s total
13.51s user 1.07s system 92% cpu 15.685s total
__conda_reactivate: command not found

>>
```

### ~/.condarc

```yaml
channels:
  - conda-forge
auto_activate_base: false
```

**Comment by Jdbeck66** [comment] 2024-11-30 16:25
Same. Get the closing statement after successfully using mamba to update:

```bash
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
mamba:8: command not found: __conda_reactivate
```

```bash
mamba --version
mamba 1.5.11
conda 24.11.0
```

**Comment by ZhongRuoyu** [comment] 2024-11-30 16:56
Should be fixed by #3643.

**Comment by jjerphan** [comment] 2024-12-02 13:05
Can you update to use mamba 2 and see if the issue is still present? Thank you.

**Comment by Jdbeck66** [comment] 2024-12-02 14:42
Yes. 2.0.4 correct the issue for me. Thanks.

**Closed as completed** 2024-12-02 14:44 UTC
Labels: type::bug, 1.x
