### ISSUE TITLE
2.0.3-0 breaks mamba-org/setup-micromamba@v2 GH Action

### ISSUE THREAD

**Issue by kmuehlbauer** [mamba-org/mamba#3576] opened 2024-11-06 14:54 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

no other issue found

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

With latest micromamba 2.0.3-0 our CI mamba-org/setup-micromamba@v2 GH Action stopped working.

See https://github.com/pydata/xarray/actions/runs/11704038363/job/32595639555

```
/home/runner/micromamba-bin/micromamba list -r /home/runner/micromamba -n xarray-tests
  critical libmamba could not load prefix data
Error: The process '/home/runner/micromamba-bin/micromamba' failed with exit code 1
```

### mamba info / micromamba info

```shell
/home/runner/micromamba-bin/micromamba info -r /home/runner/micromamba -n xarray-tests
  
         libmamba version : 2.0.3
       micromamba version : 2.0.3
             curl version : libcurl/8.10.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.64.0
       libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
         envs directories : /home/runner/micromamba/envs
            package cache : /home/runner/micromamba/pkgs
                            /home/runner/.mamba/pkgs
              environment : xarray-tests
             env location : /home/runner/micromamba/envs/xarray-tests
        user config files : /home/runner/.mambarc
   populated config files : /home/runner/work/_temp/setup-micromamba/.condarc
         virtual packages : __unix=0=0
                            __linux=6.5.0=0
                            __glibc=2.35=0
                            __archspec=1=x86_64_v3
                 channels : https://conda.anaconda.org/conda-forge/linux-64
                            https://conda.anaconda.org/conda-forge/noarch
         base environment : /home/runner/micromamba
                 platform : linux-64
```

### Logs

```shell
https://github.com/pydata/xarray/actions/runs/11704038363/job/32595639555
```

### environment.yml

```yaml
name: xarray-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiobotocore
  - array-api-strict
  - boto3
  - bottleneck
  - cartopy
  - cftime
  - dask-core
  - dask-expr # dask raises a deprecation warning without this, breaking doctests
  - distributed
  - flox
  - fsspec
  - h5netcdf
  - h5py
  - hdf5
  - hypothesis
  - iris
  - lxml # Optional dep of pydap
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - numba
  - numbagg
  - numexpr
  - numpy>=2
  - opt_einsum
  - packaging
  - pandas
  # - pint>=0.22
  - pip
  - pooch
  - pre-commit
  - pyarrow # pandas raises a deprecation warning without this, breaking doctests
  - pydap
  # start pydap server dependencies, can be removed if pydap-server is available
  - gunicorn
  - PasteDeploy
  - docopt-ng
  - Webob
  - Jinja2
  - beautifulsoup4
  # end pydap server dependencies
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-xdist
  - pytest-timeout
  - rasterio
  - scipy
  - seaborn
  - sparse
  - toolz
  - typing_extensions
  - zarr
```

### ~/.condarc

```yaml
no input
```

**Comment by kapiraman** [comment] 2024-11-06 17:22
I can reproduce this on the powershell command-line with micromamba.
```console
PS C:\Users\Me> micromamba env create -yqn minrepro python<3.13
PS C:\Users\Me> micromamba list -n minrepro
critical libmamba could not load prefix data
PS C:\Users\Me> micromamba --version
2.0.3
```

It does not repro with unconstrained python (or `python=3.13`).

**Comment by jnooree** [comment] 2024-11-06 23:04
same issue here. (micromamba-releases#62)

**Comment by ocefpaf** [comment] 2024-11-07 08:24
Another example of that issue in https://github.com/pyoceans/nbrr/actions/runs/11719160248/job/32641844119?pr=28

**Comment by JohanMabille** [comment] 2024-11-07 08:57
micromamba 2.0.3 has been marked as broken, and the release removed from micromamba-releases. micromamba 2.0.2 should be downloaded as the latesst, this should fix the issues for now.

**Comment by kapiraman** [comment] 2024-11-07 15:10
> micromamba 2.0.3 has been marked as broken, and the release removed from micromamba-releases. micromamba 2.0.2 should be downloaded as the latesst, this should fix the issues for now.

Unfortunately 2-2.0.2 had another issue preventing `micromamba` from creating environments with pip packages on windows.
  * #3467 

(Which seems to be fixed in 2.0.3, so that's progress!)

**Comment by Klaim** [comment] 2024-11-12 09:45
We think the issue might be fixed by https://github.com/mamba-org/mamba/pull/3584 
However we suspect there might be actually several issues, it's hard to say because of the variety of reports and lack of info provided by the error output. We intend to release an alpha with that fix and https://github.com/mamba-org/mamba/pull/3581 to help figure out the other problems if they appear.
If you intend to try that alpha, consider also adding `--log-verbose 1` in the `list` command in your scripts for more helpful data.

**Comment by maresb** [comment] 2024-11-12 09:57
I'm very eager to try it out in the context of conda-lock. Would you please be able to post here with instructions once the alpha is available?

**Comment by Klaim** [comment] 2024-11-12 12:02
Yes 👍🏽
The alpha release is now available: https://github.com/mamba-org/mamba/commit/e1bdc942afe5b3cbe2e16722696ffbefc6a622a9

In your ci scripts that reproduces the issue, add `--log-level 1` to the `micromamba` (or `mamba`) commands which were previously failing (`micromamba list` at a minimum, not really needed for the env creation).
If it fails again but in another command, add that flag in these other commands.
Then report here so that we get a better idea of if there are issues we couldn't reproduce yet.
Thanks for your help!

**Comment by kapiraman** [comment] 2024-11-12 17:26
Looks good for my use case.  Using the 2.0.4-alpha win-64 build artifact, I can't repro.

**Comment by kapiraman** [comment] 2024-11-12 17:26
Looks good for my use case.  Using the 2.0.4-alpha win-64 build artifact, I can't repro.

**Comment by maresb** [comment] 2024-11-12 21:56
How can I use an alpha version? It doesn't seem possible:

https://github.com/mamba-org/setup-micromamba/blob/ab6bf8bf7403e8023a094abeec19d6753bdc143e/src/options.ts#L298

**Comment by kapiraman** [comment] 2024-11-13 04:52
@maresb I used the [built artifact](https://github.com/mamba-org/mamba/actions/runs/11799303398) directly for my command-line case.  For setup-micromamba, it looks like you could use [`micromamba-url`](https://github.com/mamba-org/setup-micromamba/blob/ab6bf8bf7403e8023a094abeec19d6753bdc143e/src/options.ts#L147) instead of `micromamba-version`.  But the artifact link is both cookie-protected and zipped... so I guess you'd need to host the unzipped binary yourself.  I have not tried this, it's just an idea.

**Comment by Hind-M** [comment] 2024-11-13 09:45
@maresb `micromamba 2.0.4alpha1` is available now on [micromamba-releases](https://github.com/mamba-org/micromamba-releases/releases).

**Comment by maresb** [comment] 2024-11-13 11:47
[Here](https://github.com/conda/conda-lock/actions/runs/11816562422/job/32920108414?pr=720#step:5:206)'s the result:

```
  /home/runner/micromamba-bin/micromamba list -r /home/runner/micromamba -n conda-lock-dev
  critical libmamba could not load prefix data: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<U+001B>'
```

@Klaim, I added `log-level: trace`, but unfortunately it doesn't seem to work on the `micromamba list` step.

**Comment by Klaim** [comment] 2024-11-13 13:11
@maresb Thanks! Did you try with `--log-level 1` ?

**Comment by maresb** [comment] 2024-11-13 17:18
Great! Could you please be more specific with your suggestion? Where can I insert `--log-level 1` so that it executes in the `micromamba list` step of the setup-micromamba action?

**Comment by Klaim** [comment] 2024-11-13 18:20
> Great! Could you please be more specific with your suggestion? Where can I insert `--log-level 1` so that it executes in the `micromamba list` step of the setup-micromamba action?

Ah sorry I thought you were running the list command through a custom script. I'll have to check how `setup-micromamba` work and why `log-level: trace` doesnt work

**Comment by kapiraman** [comment] 2024-11-13 18:27
It's because [this line](https://github.com/mamba-org/setup-micromamba/blob/ab6bf8bf7403e8023a094abeec19d6753bdc143e/src/main.ts#L123) doesn't pass in `options.logLevel`.

**Comment by maresb** [comment] 2024-11-13 21:00
I went ahead and forked setup-micromamba to add the logging. Here are the [full logs](https://github.com/conda/conda-lock/actions/runs/11825610268/job/32949995266?pr=720#step:5:412)

```
...
info     libmamba Loading single package record: "/home/runner/micromamba/envs/conda-lock-dev/conda-meta/libcurl-8.11.0-hbbe4b11_0.json"
  info     libmamba Loading single package record: "/home/runner/micromamba/envs/conda-lock-dev/conda-meta/click-default-group-1.2.4-pyhd8ed1ab_0.json"
  info     libmamba Loading site packages
  critical libmamba could not load prefix data: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<U+001B>'
```

**Comment by Klaim** [comment] 2024-11-14 15:11
@maresb We still fail to reproduce that issue and we need to see what's that data being parsed (we have some idea of what is failing but not sure) so we'll release another alpha with [more logs when that error occurs](#3604)

**Comment by Hind-M** [comment] 2024-11-15 10:17
Hey @maresb! The new alpha is available on [micromamba-releases](https://github.com/mamba-org/micromamba-releases/releases).

**Comment by maresb** [comment] 2024-11-15 11:11
Great, thanks! Please see https://github.com/conda/conda-lock/actions/runs/11855193213/job/33038908463?pr=720#step:5:416

**Comment by wolfv** [comment] 2024-11-15 11:32
looks like pip uses `rich` output by default?

**Comment by Klaim** [comment] 2024-11-21 14:21
We just released v2.0.4alpha3 which should fix at least the immediate "rich output" issue (see #3607) . So far we didn't manage to find other issues beyond that one so we'll need your feedback with that alpha @maresb

**Comment by Hind-M** [comment] 2024-11-21 15:43
[`v2.0.4alpha3`](https://github.com/mamba-org/micromamba-releases/releases/) is available now.

**Comment by maresb** [comment] 2024-11-21 17:16
Now setup-micromamba is working as expected for me. Thanks so much!!!

**Comment by jjerphan** [comment] 2024-11-25 08:28
Let us know if 2.0.4 which is being released solves the problem.

**Comment by JohanMabille** [comment] 2024-11-25 10:58
Closing this as 2.0.4 is out and 2.0.3 has been removed.

**Closed by JohanMabille** 2024-11-25 10:58 UTC
Labels: type::bug
