### ISSUE TITLE
micromamba cannot create an environment with pip dependencies

### ISSUE THREAD

**Issue by antonkulaga** [mamba-org/mamba#751] opened 2021-03-09 17:41 UTC
the following environment is created by conda without any issues, however when I try to create it by micromamba by:
```
micromamba create -f environment.yaml
```
I get
```
 "ERROR   Could not read environment 'dependencies' as list of strings from environment.yaml" by micromamba
```
here is the content of environment.yaml:
```yaml
name: ramos
channels:
  - antonkulaga
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - jupyterlab>=2.2.8
  - dvc>=2.0.1
  - mamba>=0.7.12
  - scikit-learn>=0.23.2
  - seaborn>=0.10.1
  - biopython>=1.78
  - pip:
      - autocbei
prefix: /home/eugen/miniconda3/envs/ramos
```
My hypothesis is that it does not parse correctly pip dependencies

**Comment by wolfv** [comment] 2021-03-09 17:56
yes, we cannot currently handle pip deps in environment yaml files. this is a duplicate of #589 

btw. we also don't handle the `prefix: ...` specifier yet.

PR's for implementing the `pip` part would be very welcome!

**Comment by wolfv** [comment] 2021-03-09 17:56
closed as duplicate

**Closed by wolfv** 2021-03-09 17:56 UTC
