### ISSUE TITLE
nothing provides requested tensorflow 2.10.0 gpu_py310*

### ISSUE THREAD

**Issue by otavio-silva** [mamba-org/mamba#2186] opened 2022-12-20 19:05 UTC
I'm trying to install TensorFlow with CUDA enabled on Windows 11 but mamba apparently can't find the package?
Trying the following:
```
❯ mamba install -c anaconda tensorflow==2.10.0=gpu_py310*

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['tensorflow==2.10.0[build=gpu_py310*]']

anaconda/win-64                                             Using cache
anaconda/noarch                                             Using cache
conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested tensorflow 2.10.0 gpu_py310*

The environment can't be solved, aborting the operation

```
But the package does exist and it is available [here](https://anaconda.org/anaconda/tensorflow/2.10.0/download/win-64/tensorflow-2.10.0-gpu_py310h4d27e69_0.tar.bz2), why can't mamba install it?
Relevant info:
```
❯ mamba info

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : tf
    active env location : C:\ProgramData\scoop\apps\mambaforge\current\envs\tf
            shell level : 1
       user config file : C:\Users\Otávio Augusto Silva\.condarc
 populated config files : C:\ProgramData\scoop\apps\mambaforge\current\.condarc
                          C:\Users\Otávio Augusto Silva\.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __win=0=0
       base environment : C:\ProgramData\scoop\apps\mambaforge\current  (writable)
      conda av data dir : C:\ProgramData\scoop\apps\mambaforge\current\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\ProgramData\scoop\apps\mambaforge\current\pkgs
                          C:\Users\Otávio Augusto Silva\.conda\pkgs
                          C:\Users\Otávio Augusto Silva\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\scoop\apps\mambaforge\current\envs
                          C:\Users\Otávio Augusto Silva\.conda\envs
                          C:\Users\Otávio Augusto Silva\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.10.8 Windows/10 Windows/10.0.22000
          administrator : True
             netrc file : None
           offline mode : False

```
OS info:
```
Nome do dispositivo	DESKTOP-MID9VAM
Processador	AMD Ryzen 9 5900HS with Radeon Graphics           3.30 GHz
RAM instalada	40,0 GB (utilizável: 39,4 GB)
ID do dispositivo	A6B175BA-7F1C-4678-AD2A-5144EC838C04
ID do Produto	00330-80000-00000-AA397
Tipo de sistema	Sistema operacional de 64 bits, processador baseado em x64
Caneta e toque	Nenhuma entrada à caneta ou por toque disponível para este vídeo

```

**Comment by jonashaag** [comment] 2022-12-20 19:45
Try to remove the anaconda channels, it’s not recommend to mix with conda-forge. If that doesn’t solve the problem, can you try with Conda instead of Mamba?

**Comment by otavio-silva** [comment] 2022-12-21 18:18
@jonashaag The conda-forge channels do not have a recent version of TensorFlow, at least not for Windows.

**Comment by jonashaag** [comment] 2022-12-21 18:30
It seems to have some variants of TensorFlow (maybe missing GPU support? not sure) of 2.10: https://github.com/conda-forge/tensorflow-feedstock#current-release-info

**Comment by otavio-silva** [comment] 2022-12-21 18:34
@jonashaag It looks like it, but it's not available to install anywhere

**Comment by jonashaag** [comment] 2022-12-21 18:36
Could be because of incompatible other dependencies. Can you try something like

```
mamba create -n myenv 'tensorflow>=2.10' --override-channels -c conda-forge
```

Does that work?

**Comment by otavio-silva** [comment] 2022-12-21 18:57
@jonashaag Your command is still running, I don't think it's making any progress

**Comment by otavio-silva** [comment] 2022-12-21 19:00
@jonashaag It finished, but installed TensorFlow 1.14

**Comment by jonashaag** [comment] 2022-12-21 20:12
Can you please post the entire output? And also the exact command that you ran

**Comment by otavio-silva** [comment] 2022-12-21 20:22
@jonashaag  The  command was  `mamba create -n tf2 'tensorflow>=2.10' --override-channels -c conda-forge` and there was no output in the console

**Comment by jonashaag** [comment] 2022-12-21 20:45
Umm ok then something is really broken, are you sure you typed the quotes as well? Otherwise in most shells it will redirect to a file called `=2.10`. You might want to try `tensorflow=2.10`.

**Comment by otavio-silva** [comment] 2022-12-21 20:57
@jonashaag I typed that exact command, copied from the console. but a funny thing happened, it created a folder called `2.10'` with this inside:
```
conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache
Transaction

  Prefix: C:\ProgramData\scoop\apps\mambaforge\current\envs\tf2

  Updating specs:

   - tensorflow


  Package                               Version  Build                   Channel                  Size
--------------------------------------------------------------------------------------------------------
  Install:
--------------------------------------------------------------------------------------------------------

  + absl-py                               1.3.0  pyhd8ed1ab_0            conda-forge/noarch       98kB
  + astor                                 0.8.1  pyh9f0ad1d_0            conda-forge/noarch       26kB
  + c-ares                               1.18.1  h8ffe710_0              conda-forge/win-64      117kB
  + ca-certificates                   2022.12.7  h5b45459_0              conda-forge/win-64     Cached
  + cached-property                       1.5.2  hd8ed1ab_1              conda-forge/noarch        4kB
  + cached_property                       1.5.2  pyha770c72_1            conda-forge/noarch       11kB
  + gast                                  0.5.3  pyhd8ed1ab_0            conda-forge/noarch       21kB
  + google-pasta                          0.2.0  pyh8c360ce_0            conda-forge/noarch       43kB
  + grpc-cpp                             1.48.1  h6a6baca_1              conda-forge/win-64       30MB
  + grpcio                               1.48.1  py37h2fbb7ef_1          conda-forge/win-64        2MB
  + h5py                                  3.7.0  nompi_py37h24adfc3_101  conda-forge/win-64        1MB
  + hdf5                                 1.12.2  nompi_h57737ce_101      conda-forge/win-64       12MB
  + importlib-metadata                   4.11.4  py37h03978a9_0          conda-forge/win-64       34kB
  + intel-openmp                       2023.0.0  h57928b3_25922          conda-forge/win-64        2MB
  + keras-applications                    1.0.8  py_1                    conda-forge/noarch       31kB
  + keras-preprocessing                   1.1.2  pyhd8ed1ab_0            conda-forge/noarch       35kB
  + krb5                                 1.20.1  heb0366b_0              conda-forge/win-64     Cached
  + libabseil                        20220623.0  cxx17_h1a56200_6        conda-forge/win-64        1MB
  + libaec                                1.0.6  h39d44d4_0              conda-forge/win-64       61kB
  + libblas                               3.9.0  16_win64_mkl            conda-forge/win-64        6MB
  + libcblas                              3.9.0  16_win64_mkl            conda-forge/win-64        6MB
  + libcurl                              7.87.0  h68f0423_0              conda-forge/win-64      305kB
  + libhwloc                              2.8.0  h039e092_1              conda-forge/win-64     Cached
  + libiconv                               1.17  h8ffe710_0              conda-forge/win-64     Cached
  + liblapack                             3.9.0  16_win64_mkl            conda-forge/win-64        6MB
  + libprotobuf                          3.21.8  h12be248_0              conda-forge/win-64        2MB
  + libsqlite                            3.40.0  hcfcfb64_0              conda-forge/win-64     Cached
  + libssh2                              1.10.0  h9a1e1f7_3              conda-forge/win-64     Cached
  + libxml2                              2.10.3  hc3477c8_0              conda-forge/win-64     Cached
  + libzlib                              1.2.13  hcfcfb64_4              conda-forge/win-64     Cached
  + m2w64-gcc-libgfortran                 5.3.0  6                       conda-forge/win-64      351kB
  + m2w64-gcc-libs                        5.3.0  7                       conda-forge/win-64      532kB
  + m2w64-gcc-libs-core                   5.3.0  7                       conda-forge/win-64      219kB
  + m2w64-gmp                             6.1.0  2                       conda-forge/win-64      744kB
  + m2w64-libwinpthread-git  5.0.0.4634.697f757  2                       conda-forge/win-64       32kB
  + markdown                              3.4.1  pyhd8ed1ab_0            conda-forge/noarch       66kB
  + markupsafe                            2.1.1  py37hcc03f2d_1          conda-forge/win-64       25kB
  + mkl                                2022.1.0  h6a75c08_874            conda-forge/win-64      192MB
  + msys2-conda-epoch                  20160418  1                       conda-forge/win-64        3kB
  + numpy                                1.21.6  py37h2830a78_0          conda-forge/win-64        6MB
  + openssl                               3.0.7  hcfcfb64_1              conda-forge/win-64     Cached
  + pip                                  22.3.1  pyhd8ed1ab_0            conda-forge/noarch     Cached
  + protobuf                             4.21.8  py37h7f67f24_0          conda-forge/win-64      709kB
  + pthreads-win32                        2.9.1  hfa6e2cd_3              conda-forge/win-64     Cached
  + python                               3.7.12  h900ac77_100_cpython    conda-forge/win-64       19MB
  + python_abi                              3.7  3_cp37m                 conda-forge/win-64        6kB
  + re2                              2022.06.01  h0e60522_1              conda-forge/win-64      379kB
  + scipy                                 1.7.3  py37hb6553fb_0          conda-forge/win-64       26MB
  + setuptools                           65.6.3  pyhd8ed1ab_0            conda-forge/noarch     Cached
  + six                                  1.16.0  pyh6c4a22f_0            conda-forge/noarch       14kB
  + sqlite                               3.40.0  hcfcfb64_0              conda-forge/win-64      674kB
  + tbb                                2021.7.0  h91493d7_1              conda-forge/win-64     Cached
  + tensorboard                          1.14.0  py37_0                  conda-forge/win-64        3MB
  + tensorflow                           1.14.0  h1f41ff6_0              conda-forge/win-64       24kB
  + tensorflow-base                      1.14.0  py37hc8dfbb8_0          conda-forge/win-64       60MB
  + tensorflow-estimator                 1.14.0  py37h5ca1d4c_0          conda-forge/win-64      662kB
  + termcolor                             2.1.1  pyhd8ed1ab_0            conda-forge/noarch       10kB
  + typing_extensions                     4.4.0  pyha770c72_0            conda-forge/noarch       30kB
  + ucrt                           10.0.22621.0  h57928b3_0              conda-forge/win-64     Cached
  + vc                                     14.3  h3d8a991_9              conda-forge/win-64     Cached
  + vs2015_runtime                  14.32.31332  h1d6e394_9              conda-forge/win-64     Cached
  + werkzeug                              2.2.2  pyhd8ed1ab_0            conda-forge/noarch      255kB
  + wheel                                0.38.4  pyhd8ed1ab_0            conda-forge/noarch     Cached
  + wrapt                                1.14.1  py37hcc03f2d_0          conda-forge/win-64       49kB
  + zipp                                 3.11.0  pyhd8ed1ab_0            conda-forge/noarch     Cached
  + zlib                                 1.2.13  hcfcfb64_4              conda-forge/win-64      116kB

  Summary:

  Install: 66 packages

  Total download: 379MB

--------------------------------------------------------------------------------------------------------


Confirm changes: [Y/n] 
Looking for: ['tensorflow']


Downloading and Extracting Packages


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

To activate this environment, use

     $ mamba activate tf2

To deactivate an active environment, use

     $ mamba deactivate


```

**Comment by otavio-silva** [comment] 2022-12-21 21:00
Using double quotes helped, but it gives this  output:
```
❯ mamba create -n tf2 "tensorflow>=2.10" --override-channels -c conda-forge

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ["tensorflow[version='>=2.10']"]

conda-forge/noarch                                  10.7MB @   3.0MB/s  4.3s
conda-forge/win-64                                  18.5MB @   3.7MB/s  6.4s
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested tensorflow >=2.10

The environment can't be solved, aborting the operation
```

**Comment by jonashaag** [comment] 2022-12-21 23:14
I'm sorry, you are right, there's no recent Windows build of TensorFlow on conda-forge.

Soo, going back to the very first question: Why doesn't Mamba find it? I'm not sure, it might be related to some dependency of TensorFlow. Just to be sure that the problem isn't that your query is too restrictive, can you please play around with a bunch of alternatives like

```
tensorflow>2=gpu*
tensorflow=2.10
```

And maybe also try those with Conda.

**Comment by otavio-silva** [comment] 2022-12-22 00:11
@jonashaag  The command `mamba install -c conda-forge -c anaconda -c main "tensorflow>=2.9=gpu*"` installs the 2.9.1 version of the package just fine. But still, no 2.10 version with CUDA enabled.

**Comment by jonashaag** [comment] 2022-12-22 00:52
Is there any Conda command that installs the right version for you?

**Comment by otavio-silva** [comment] 2022-12-22 01:07
@jonashaag at the moment, on. Witch is strange, considering that the anaconda and main channels have the package there, so I don't understand what is happening.

**Comment by jonashaag** [comment] 2022-12-22 06:51
Ok in that case I’m afraid this is not a package Manager issue. Maybe a package issue (contact Anaconda) or maybe some property of your system doesn’t work with recent TF.

**Comment by davedgd** [comment] 2023-01-21 21:57
I ran into this today and found a solution that works. Long story short, you need to use `CONDA_CUDA_OVERRIDE` to make this work as described in this [conda-forge blog post](https://conda-forge.org/blog/posts/2021-11-03-tensorflow-gpu/).

For example, with CUDA 11.8 and mamba, use:

`CONDA_CUDA_OVERRIDE="11.8" mamba install tensorflow -c conda-forge`

For CUDA 11.8 and conda, it would be:

`CONDA_CUDA_OVERRIDE="11.8" conda install tensorflow -c conda-forge`

Depending on your setup, you may also want to install cudatoolkit as well, e.g.,

`CONDA_CUDA_OVERRIDE="11.8" mamba install tensorflow cudatoolkit -c conda-forge`

**Comment by jonashaag** [comment] 2023-02-14 16:56
Closing because I don't think we can do anything here

**Closed by jonashaag** 2023-02-14 16:56 UTC
