### ISSUE TITLE
critical libmamba Package cache error. When building with micromamba

### ISSUE THREAD

**Issue by stefanklut** [mamba-org/mamba#2167] opened 2022-12-14 15:26 UTC
When building the following environment the mamba installation works fine, but the micromamba installation gives an error:
```yml
name: test
channels:
  - default
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3
  - pytorch 
  - torchvision 
  - torchaudio 
  - cudatoolkit=11.7
  - numpy
  - opencv
  - pillow
  - matplotlib
  - scipy
  - scikit-learn
  - pip
  - tensorboard
  - pip:
    - 'git+https://github.com/facebookresearch/detectron2.git'
    - natsort
    - torch-tb-profiler
    - imagesize
```

The error in question is as follows (includes all warning, please let me know if something else is needed):
```
warning  libmamba [cuda-cuobjdump-11.7.91-0] The following files were already present in the environment:
    - LICENSE
Linking cuda-cuxxfilt-11.7.91-0
warning  libmamba [cuda-cuxxfilt-11.7.91-0] The following files were already present in the environment:
    - LICENSE
Linking cuda-nvcc-11.7.99-0
warning  libmamba [cuda-nvcc-11.7.99-0] The following files were already present in the environment:
    - LICENSE
Linking cuda-nvprune-11.7.91-0
warning  libmamba [cuda-nvprune-11.7.91-0] The following files were already present in the environment:
    - LICENSE
Linking cuda-cccl-11.7.91-0
Linking cuda-driver-dev-11.7.99-0
Linking cuda-cupti-11.7.101-0
warning  libmamba [cuda-cupti-11.7.101-0] The following files were already present in the environment:
    - LICENSE
Linking cuda-nvtx-11.7.91-0
warning  libmamba [cuda-nvtx-11.7.91-0] The following files were already present in the environment:
    - LICENSE
Linking cuda-nsight-12.0.78-0
warning  libmamba [cuda-nsight-12.0.78-0] The following files were already present in the environment:
    - LICENSE
Linking nsight-compute-2022.4.0.15-0
warning  libmamba [nsight-compute-2022.4.0.15-0] The following files were already present in the environment:
    - LICENSE
Linking libcufile-1.5.0.59-0
warning  libmamba Invalid package cache, could not read 'paths.json' from '/home/stefan/micromamba/pkgs/libcufile-1.5.0.59-0'
    
error    libmamba Cannot find a valid extracted directory cache for 'libcufile-1.5.0.59-0.tar.bz2'
critical libmamba Package cache error.
```

Versions:
```sh
$mamba --version
mamba 1.0.0
conda 22.9.0
```

```sh
$micromamba -v
Version: 1.1.0
```

First encountered this problem when trying to build a docker container using the micromamba docker, but the error was present in version 1.0.0 and outside the docker environment as well.

Tested on Ubuntu 22.04

**Comment by jonashaag** [comment] 2022-12-15 08:52
Could it be that that package is simply broken? What channels is it from?

Btw it is not recommended to mix the `defaults` and `conda-forge` channels.

**Comment by philschmid** [comment] 2022-12-15 16:49
> Could it be that that package is simply broken? What channels is it from?

`libcufile-1.5.0.59-0.tar.bz2` should come from the `nvidia` channel and `cudatoolkit=11.7` package

**Comment by jonashaag** [comment] 2022-12-15 16:51
Does installation work with Conda? I wonder if the package is broken

**Comment by philschmid** [comment] 2022-12-15 17:05
Running 
```
conda install -y -n base -c conda-forge -c nvidia -c pytorch python=3.9.13 nvidia::cudatoolkit=11.6 pytorch::pytorch=1.13.0=py3.9_cuda11.6*
```
on a AWS EC2 with a NVIDIA T4 and `conda 4.12.0` worked

**Comment by wolfv** [comment] 2022-12-15 17:18
Strange! I investigated a bit. The paths.json fiile appears to be there in the archive ... 

The user id and group ids in the tar file are:

```
tar tvf libcufile-1.5.0.59-0.tar.bz2

-rw-r--r--  0 25503  2174      110 Oct 12 21:57 info/files
-rw-r--r--  0 25503  2174      201 Oct 12 21:57 info/index.json
-rw-r--r--  0 25503  2174     1024 Oct 12 21:57 info/paths.json
-rw-r--r--  0 25503  2174     3156 Oct 12 21:57 info/about.json
-rw-r--r--  0 25503  2174        0 Oct 12 21:57 info/git
-rw-rw-r--  0 25503  2174    10758 Oct 12 21:57 etc/cufile.json
lrwxrwxrwx  0 25503  2174        0 Oct 12 21:57 lib/libcufile.so.0 -> libcufile.so.0
-rwxrwxr-x  0 25503  2174    47656 Oct 12 21:57 lib/libcufile_rdma.so.1.5.0
-rwxrwxr-x  0 25503  2174  2088640 Oct 12 21:57 lib/libcufile.so.1.5.0
lrwxrwxrwx  0 25503  2174        0 Oct 12 21:57 lib/libcufile_rdma.so.1 -> libcufile_rdma.so.1.5.0
```

While for some random package from conda-forge they are:

```
➜  Downloads tar tvf ~/micromamba/pkgs/mpfr-4.1.0-h6d7a090_1.tar.bz2
-rw-r--r--  0 501    20         33 Aug 26  2021 info/run_exports.json
-rw-r--r--  0 501    20        258 Aug 26  2021 info/index.json
-rw-r--r--  0 501    20        278 Aug 26  2021 info/hash_input.json
-rw-r--r--  0 501    20        283 Aug 26  2021 info/has_prefix
-rw-r--r--  0 501    20        513 Aug 26  2021 info/files
-rw-r--r--  0 501    20       3945 Aug 26  2021 info/about.json
-rw-r--r--  0 501    20       4356 Aug 26  2021 info/paths.json
-rw-r--r--  0 501    20          0 Aug 26  2021 info/git
```

But I have no idea if that changes anything.

**Comment by urucoder** [comment] 2022-12-16 20:11
I can confirm suffering the same issue on my side, using the mamba binary from the micromamba installation works like a charm.

**Failing**
> micromamba install pytorch::pytorch=1.13.1=py3.9_cuda11.7_cudnn8.5.0_0 -c pytorch -c nvidia

**Installing successfully** 
> /opt/micromamba/envs/<environ>/condabin/mamba install pytorch::pytorch=1.13.1=py3.9_cuda11.7_cudnn8.5.0_0 -c pytorch -c nvidia

**Comment by urucoder** [comment] 2022-12-20 14:58
Hey, we migrated from Miniconda to Micromamba a month ago, and now we were forced to roll it back due to this bug, but we loved the performance and want to keep using this dependency manager. Please, let me know if I can share any output or discuss the issue together

**Comment by mgbckr** [comment] 2022-12-20 16:03
I had the same issue. I am [using a workaround now](https://gist.github.com/mgbckr/bd7da9205b8d84eb7eaeeddfaf1012bd) based on @urucoder 's comment.

**Comment by peyerroger** [comment] 2022-12-21 12:28
Same issue here. Would be great if you could fix that.

**Comment by EKami** [comment] 2022-12-23 08:19
Same issue here, I noticed the other day the dependency `https://conda.anaconda.org/pytorch/noarch/pytorch-cuda-11.7-h67b0de4_0.tar.bz2` md5 changed from `ba87bf7c4126c2e9754c339643b8a58c` to `f27b09d1320cab15e0e23dd43c7a15c4`. That might be related.

**Comment by EKami** [comment] 2022-12-23 08:22
Adding `libcufile=1.4.0.31` to my dependency list in my `conda.yaml` worked for me

**Comment by popfido** [comment] 2023-01-05 08:47
Same issue here. It can be accurately reproduced by following the official install instruction of PyTorch.

**Comment by wolfv** [comment] 2023-01-10 12:15
When running only the extract for that specific libcufile pacakge, I get: 

```
 ✘ wolfv@thinknext  ~/exte  micromamba package extract libcufile-1.5.0.59-0.tar.bz2     
critical libmamba filesystem error: cannot make absolute path: Invalid argument []
Extracting "/home/wolfv/exte/libcufile-1.5.0.59-0.tar.bz2" to %                                                                                                                                                                                                                                                                 ✘ wolfv@thinknext  ~/exte  
```

... investigating

**Comment by wolfv** [comment] 2023-01-10 12:18
ouch, false alarm. was missing the second argument :)

**Comment by wolfv** [comment] 2023-01-10 12:39
So the real problem is a circular soft link in that package (warning  libmamba Could not check existence: Too many levels of symbolic links)

It was also reported here: https://forums.developer.nvidia.com/t/libcufile-1-5-0-59-0-conda-package-has-broken-symlink/238757

I'll see what conda does in that case ...

**Comment by wolfv** [comment] 2023-01-18 06:25
Please try again with latest micromamba :)

**Comment by wolfv** [comment] 2023-01-18 06:26
Also Nvidia folks have told me that it's going to be fixed in the next releases.

**Closed by wolfv** 2023-01-18 06:25 UTC

**Comment by Ayenem** [comment] 2023-07-17 19:57
Update: Problem persists

Fixed it with running `micromamba install libcufile` first, and then my torch install; in my case, for python 3.11.4: `micromamba install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`

**Comment by jonashaag** [comment] 2023-07-17 20:20
Please open a new issue with the issue template.
