### ISSUE TITLE
"Mamba install -- revision XX" never works

### ISSUE THREAD

**Issue by sweettyler** [mamba-org/mamba#2209] opened 2023-01-08 04:40 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

revision

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Didn't try

### Describe your issue

Although "mamba list --revisions" always give correct results, "mamba install --revision XX" never works (actually it does nothing) and always says:

Looking for: []

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*

Transaction

  Prefix: /private/pzha/mambaforge

  All requested packages already installed

**Comment by sweettyler** [comment] 2023-01-08 04:44
Tried with "conda install --revision XX" and it works!

**Comment by jonashaag** [comment] 2023-01-08 05:30
IIUC this is a dupe of https://github.com/mamba-org/mamba/issues/803#issuecomment-1374710574

**Closed by jonashaag** 2023-01-08 05:30 UTC
