### ISSUE TITLE
Cannot create an env with micromamba but mamba works

### ISSUE THREAD

**Issue by 183amir** [mamba-org/mamba#2171] opened 2022-12-16 16:30 UTC
It seems that there is an issue with the package cache handling when using micromamba to create a conda environment and install the libcufile package.
In contrast, when using mamba to create the same environment and install the same package, the process appears to be successful. It is possible that there is an issue with the package cache handling when using micromamba, which is causing the error.

Please compare the outputs below:
```
micromamba create -n test -c nvidia libcufile=1.5.0.59=0

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

nvidia/noarch                                        2.4kB @  11.7kB/s  0.2s
nvidia/linux-64                                     96.3kB @ 466.8kB/s  0.2s

Transaction

  Prefix: /home/amir/micromamba/envs/test

  Updating specs:

   - libcufile==1.5.0.59=0


  Package       Version  Build  Channel              Size
───────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────

  + libcufile  1.5.0.59  0      nvidia/linux-64     772kB

  Summary:

  Install: 1 packages

  Total download: 772kB

───────────────────────────────────────────────────────────


Confirm changes: [Y/n] 

Transaction starting
libcufile                                          771.9kB @   5.4MB/s  0.1s
Linking libcufile-1.5.0.59-0
warning  libmamba Invalid package cache, could not read 'paths.json' from '/home/amir/micromamba/pkgs/libcufile-1.5.0.59-0'
    
error    libmamba Cannot find a valid extracted directory cache for 'libcufile-1.5.0.59-0.tar.bz2'
critical libmamba Package cache error.
```
```
mamba create -n test -c nvidia libcufile=1.5.0.59=0 

Looking for: ['libcufile==1.5.0.59=0']

nvidia/linux-64                                             Using cache
nvidia/noarch                                               Using cache
warning  libmamba Invalid package cache, could not read 'paths.json' from '/home/amir/Data/conda/pkgs/libcufile-1.5.0.59-0'
    
Transaction

  Prefix: /home/amir/Data/conda/envs/test

  Updating specs:

   - libcufile==1.5.0.59=0


  Package       Version  Build  Channel               Size
────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────

  + libcufile  1.5.0.59  0      nvidia/linux-64     Cached

  Summary:

  Install: 1 packages

  Total download: 0 B

────────────────────────────────────────────────────────────

Confirm changes: [Y/n] 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

To activate this environment, use

     $ mamba activate test

To deactivate an active environment, use

     $ mamba deactivate
```
some more information:
```
micromamba info                                         

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


       libmamba version : 1.1.0
     micromamba version : 1.1.0
           curl version : libcurl/7.86.0 OpenSSL/1.1.1s zlib/1.2.13 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.6.1 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __archspec=1=x86_64
                          __cuda=11.7=0
```
```
mamba info
            shell level : 1
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __cuda=11.7=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
  conda av metadata url : None
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.13 Linux/5.4.0-135-generic ubuntu/20.04.5 glibc/2.31
             netrc file : None
           offline mode : False

$ mamba --version
mamba 0.22.1
conda 4.12.0
```

**Comment by jonashaag** [comment] 2022-12-16 18:27
Please search related issues before creating a ticket, this is a duplicate of #2167

**Closed by jonashaag** 2022-12-16 18:27 UTC
