### ISSUE TITLE
`zsh: killed mamba` after new update to version 0.24.0

### ISSUE THREAD

**Issue by RiccardoMPesce** [mamba-org/mamba#1744] opened 2022-06-12 18:53 UTC
After upgrading mamba and related packages to version 0.24.0, as long as I run `mamba` related commands, I get `zsh: killed     mamba ....`. I run MacOS 12.4 and, and important detail, as soon as I `brew reinstall mambaforge` all seem to be back to normal until I update again. Mambaforge is installed through Brew.

**Comment by ajye92** [comment] 2022-06-12 20:40
Looks like it was caused by `libcxx v14.0.5`. Try: 
`conda install libcxx=14.0.4 --force-reinstall`

**Comment by LeoAdL** [comment] 2022-06-12 20:52
Fixed it for me! Thanks.

**Comment by mfansler** [comment] 2022-06-13 00:44
Note that since the breakage is via `libmamba`, anyone using the `experimental_solver: libmamba` configuration will also need to first switch back to classic mode (default):

```
conda config --remove-key experimental_solver
conda install libcxx=14.0.4
conda config --set experimental_solver libmamba
```

Also, a patched build for v14.0.5 is up on Anaconda Cloud, though repodata hasn't included it yet. So, maybe in an hour, users can just `conda update libcxx`.

**Comment by RiccardoMPesce** [comment] 2022-06-13 05:06
Everything seems to be fixed. The issue seemed indeed to be as @ajye92 said, i.e. with `libcxx v14.0.5`. However, @mfansler is right, i.e. the patched working version is available through updating. Just run `mamba clean --all` before updating again so you get the new, patched and working version.

**Comment by wolfv** [comment] 2022-06-13 12:04
Thanks guys for chiming in and the debugging! This should be fixed now :)

**Closed by wolfv** 2022-06-13 12:04 UTC
