### ISSUE TITLE
micromamba errors when installed to a location with spaces in the path

### ISSUE THREAD

**Issue by emlys** [mamba-org/mamba#3057] opened 2023-12-11 18:51 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

"path space", "no such file or directory"

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I followed the micromamba manual installation instructions in a directory that contains spaces in the path. Some micromamba commands produce an error that appears to be caused by the path space not being handled correctly.
```bash
$ mkdir "with spaces"
$ cd "with spaces"
$ curl -Ls https://micro.mamba.pm/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
$ eval "$(./bin/micromamba shell hook -s posix)"
$ micromamba create -n test python==3.11
$ micromamba run --name test python --version
/var/folders/zh/dy02ljyd4mj5_nfm158hwcr00000gn/T/mambafAXk1Ko5alu: line 2: /Users/emily/with: No such file or directory
/var/folders/zh/dy02ljyd4mj5_nfm158hwcr00000gn/T/mambafAXk1Ko5alu: line 3: micromamba: command not found
/var/folders/zh/dy02ljyd4mj5_nfm158hwcr00000gn/T/mambafAXk1Ko5alu: line 5: exec: python: not found
```
I think it is an issue with path handling because of the line `/Users/emily/with: No such file or directory`, the path is broken at the space.

### mamba info / micromamba info

```shell
libmamba version : 1.5.3
     micromamba version : 1.5.3
           curl version : libcurl/8.4.0 SecureTransport (OpenSSL/3.1.4) zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /Users/emily/micromamba/envs
          package cache : /Users/emily/micromamba/pkgs
                          /Users/emily/.mamba/pkgs
            environment : /Users/emily/mambaforge/envs/plugin (active)
           env location : /Users/emily/mambaforge/envs/plugin
      user config files : /Users/emily/.mambarc
 populated config files : /Users/emily/.condarc
       virtual packages : __unix=0=0
                          __osx=13.2.1=0
                          __archspec=1=x86_64-v4
               channels : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
       base environment : /Users/emily/micromamba
               platform : osx-64
```

**Comment by emlys** [comment] 2024-03-26 19:52
If someone can point me to the relevant source, I'd be happy to try and submit a fix. I'm not sure where to find the source for the `bin/micromamba` binary or whatever is running in the temporary location `/var/folders/zh/dy02ljyd4mj5_nfm158hwcr00000gn/T/mambafAXk1Ko5alu` where the error comes from.

This issue is relevant because I'm trying to install micromamba as a dependency of our desktop software, and the appropriate path for it on macOS contains a space: `~/Library/Application Support/`.

**Comment by dcdenu4** [comment] 2024-08-08 14:14
Hi @jonashaag, I'm hoping since you labeled this a bug you might have an update on this or be able to point our group in the right direction to try and help out with this issue? Thanks!

**Comment by crotron** [comment] 2024-10-01 21:12
I'm getting this error too on Linux on micromamba 2.0.1-0, in my case:

`
/tmp/mambafW3WTpCGUjp: line 2: /media/(my username)/4: No such file or directory
/tmp/mambafW3WTpCGUjp: line 3: micromamba: command not found
/tmp/mambafW3WTpCGUjp: line 5: exec: python: not found
`

The next folder should be "4 TB" but is instead "4".

I moved it to a different folder without any spaces in the path and everything appears to work normally.

@dcdenu4 is there any information we could provide that would help with this?

**Comment by luciorq** [comment] 2024-12-06 16:09
The relevant piece of code is in line 1485:

https://github.com/mamba-org/mamba/blob/b6150dba8f09cfeb7fe19487a8d9adfc42e64de8/libmamba/src/core/util.cpp#L1483-L1486

Currently, the `$MAMBA_EXE` variable is passed to the temporary shell script without being quoted, which can cause issues if it contains whitespace. To fix this, the line should include double quotes around `$MAMBA_EXE`.

Would you be interested in a Pull Request that addresses this issue, given that the previous issue #3658 was closed as “not planned”?

**Comment by jjerphan** [comment] 2024-12-09 10:07
> Would you be interested in a Pull Request that addresses this issue, given that the other issue https://github.com/mamba-org/mamba/issues/3658 was closed as “not planned”?

Yes, we definitely would be interested! (#3658 was closed as a duplicate of this issue).

**Closed** 2024-12-09 16:23 UTC
Labels: type::bug
