### ISSUE TITLE
A KeyError Exception occurs when uninstalling flask

### ISSUE THREAD

**Issue by gutkyu** [mamba-org/mamba#2464] opened 2023-04-17 02:26 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

remove

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

A KeyError Exception occurs when uninstalling flask after installing it.

- target package : flask 
- target version : 2 (version 1 succeeded)

Here's how to reproduce it
1. create a conda environment
`$ conda create -p ./cond_test -c conda-forge python=3.9`
2. install flask
`$ mamba install -p ./cond_test -c conda-forge -y flask`
3. remove flask
`$ mamba remove -p ./cond_test -c conda-forge -y flask`

But, conda works fine.

### mamba info / micromamba info

```shell
__    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : None
            shell level : 0
       user config file : /home/jayden/.condarc
 populated config files : /home/jayden/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /home/jayden/miniconda3  (writable)
      conda av data dir : /home/jayden/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jayden/miniconda3/pkgs
                          /home/jayden/.conda/pkgs
       envs directories : /home/jayden/miniconda3/envs
                          /home/jayden/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.9.16 Linux/4.18.0-372.32.1.el8_6.x86_64 rocky/8.6 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Logs

```shell
$ mamba remove -p cond_test -c conda-forge -y -v flask 

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Removing specs: ['flask']
info     libmamba Reading cache files '/tmp/tmp8hvdoe56.*' for repo index 'installed'
info     libmamba parsing history: "/home/jayden/myproject/cond_test/conda-meta/history"
info     libmamba Parsing MatchSpec python=3.9
info     libmamba Parsing MatchSpec flask
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec flask
info     libmamba Parsing MatchSpec flask=1.1.4
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec flask
info     libmamba Parsing MatchSpec flask=2.1.3
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec flask
info     libmamba Parsing MatchSpec flask=2.0.3
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec flask
info     libmamba Parsing MatchSpec flask=2.0.1
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec flask
info     libmamba Parsing MatchSpec flask=1.1.4
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec flask
info     libmamba Parsing MatchSpec flask=2.0.1
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec flask =2.0.1*
info     libmamba Adding job: flask 2.0.1*
info     libmamba Parsing MatchSpec openssl
info     libmamba Adding job: openssl
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Adding job: ca-certificates
info     libmamba Parsing MatchSpec python =3.9*
info     libmamba Adding job: python 3.9*
info     libmamba Parsing MatchSpec flask
info     libmamba Parsing MatchSpec flask
info     libmamba Adding job: flask
info     libmamba Problem count: 0
info     libmamba Found python in installed packages 3.9.16
Transaction

  Prefix: /home/jayden/myproject/cond_test

  Removing specs:

   - flask


  Package         Version  Build              Channel         Size
────────────────────────────────────────────────────────────────────
  Remove:
────────────────────────────────────────────────────────────────────

  - __unix              0  0                  installed           
  - click           8.1.3  unix_pyhd8ed1ab_2  conda-forge         
  - flask           2.0.1  pyhd8ed1ab_0       conda-forge         
  - itsdangerous    2.1.2  pyhd8ed1ab_0       conda-forge         
  - jinja2          3.1.2  pyhd8ed1ab_1       conda-forge         
  - markupsafe      2.1.2  py39h72bdee0_0     conda-forge         
  - python_abi        3.9  3_cp39             conda-forge         
  - werkzeug        2.2.3  pyhd8ed1ab_0       conda-forge         

  Summary:

  Remove: 8 packages

  Total download: 0 B

────────────────────────────────────────────────────────────────────


info     libmamba All targets to download are cached
PackageRecord(_hash=-6491596840269787336, name='__unix', version='0', build='0', build_number=0, channel=Channel("@"), subdir='linux-64', fn='__unix', md5='12345678901234567890123456789012', package_type='virtual_system')

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/jayden/miniconda3/lib/python3.9/site-packages/conda/_vendor/boltons/setutils.py", line 248, in remove
        didx = self.item_index_map.pop(item)
    KeyError: PackageRecord(_hash=-6491596840269787336, name='__unix', version='0', build='0', build_number=0, channel=Channel("@"), subdir='linux-64', fn='__unix', md5='12345678901234567890123456789012', package_type='virtual_system')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/jayden/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/home/jayden/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/home/jayden/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/jayden/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/jayden/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 756, in do_call
        exit_code = remove(args, parser)
      File "/home/jayden/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 240, in remove
        conda_transaction = to_txn(
      File "/home/jayden/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 436, in to_txn
        final_precs = compute_final_precs(
      File "/home/jayden/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 371, in compute_final_precs
        final_precs.remove(i_rec)
      File "/home/jayden/miniconda3/lib/python3.9/site-packages/conda/_vendor/boltons/setutils.py", line 250, in remove
        raise KeyError(item)
    KeyError: PackageRecord(_hash=-6491596840269787336, name='__unix', version='0', build='0', build_number=0, channel=Channel("@"), subdir='linux-64', fn='__unix', md5='12345678901234567890123456789012', package_type='virtual_system')

`$ /home/jayden/miniconda3/condabin/mamba remove -p cond_test -c conda-forge -y -v flask`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/home/jayden/miniconda3/bin/conda
         CONDA_PYTHON_EXE=/home/jayden/miniconda3/bin/python
               CONDA_ROOT=/home/jayden/miniconda3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/jayden/.vscode-
                          server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/bin/remote-cli:/ho
                          me/jayden/miniconda3/condabin:/home/jayden/.nvm/versions/node/v16.16.0
                          /bin:/home/jayden/.local/bin:/home/jayden/bin:/usr/local/bin:/usr/bin:
                          /usr/local/sbin:/usr/sbin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b0
                          7-2.el8_5.x86_64/bin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-2.e
                          l8_5.x86_64/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /home/jayden/.condarc
 populated config files : /home/jayden/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /home/jayden/miniconda3  (writable)
      conda av data dir : /home/jayden/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jayden/miniconda3/pkgs
                          /home/jayden/.conda/pkgs
       envs directories : /home/jayden/miniconda3/envs
                          /home/jayden/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.9.16 Linux/4.18.0-372.32.1.el8_6.x86_64 rocky/8.6 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

info     libmamba Freeing solver.
info     libmamba Freeing transaction.
info     libmamba Freeing pool.
```

### environment.yml

```yaml
name: /home/jayden/myproject/cond_test
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - flask=2.0.1=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - markupsafe=2.1.2=py39h72bdee0_0
  - ncurses=6.3=h27087fc_1
  - openssl=3.1.0=h0b41bf4_0
  - pip=23.1=pyhd8ed1ab_0
  - python=3.9.16=h2782a2a_0_cpython
  - python_abi=3.9=3_cp39
  - readline=8.2=h8228510_1
  - setuptools=67.6.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2023c=h71feb2d_0
  - werkzeug=2.2.3=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
prefix: /home/jayden/myproject/cond_test
```

### ~/.condarc

```
auto_activate_base: false
```

**Comment by jonashaag** [comment] 2023-04-17 17:05
Dupe of https://github.com/mamba-org/mamba/issues/1770#issue-comment-box

**Closed by jonashaag** 2023-04-17 17:05 UTC
