### ISSUE TITLE
micromamba create does not support the --override-channels flag

### ISSUE THREAD

**Issue by mariusvniekerk** [mamba-org/mamba#521] opened 2020-09-29 21:01 UTC
When trying to use micromamba in conjunction with `conda-lock` we get the following kinds of errors 

```
   Command: ['/root/.local/share/ensure-conda/micromamba', 'create', 
            '--prefix', '/tmp/tmp408fyo5_/prefix', '--dry-run', '--json', 
            '--override-channels', '--channel', 'conda-forge', '--channel', 'defaults',
            'python >=3.6,<3.7']
    STDERR:
The following argument was not expected: --override-channels
Run with --help for more information.
```

It would be great if micromamba supported this, which would enable us to make micromamba the default solver for conda-lock in the even that neither conda or mamba are installed.

**Comment by mariusvniekerk** [comment] 2020-09-29 21:02
For reference see https://github.com/conda-incubator/conda-lock/commit/2dd88f7d55695f171c7e060d5fec0dc23ce1a1d7

**Comment by mariusvniekerk** [comment] 2020-09-30 14:32
This can just be a `noop`

**Comment by wolfv** [comment] 2020-10-01 21:33
this is fixed with 0.5.3, as a noop for now.

Although I am not sure: if you pass in an environment.yml file, what is the expected behavior? override channels from in there?

**Comment by mariusvniekerk** [comment] 2020-10-02 02:01
I'm not sure what conda env create does for that (but if memory serves it doesn't have the ability to specify channels).

**Comment by wolfv** [comment] 2020-10-02 07:19
you can have channels in environment.yml files afaik

**Comment by xhochy** [comment] 2020-10-02 11:06
If you want to override channels with an `environment.yml` you need to add the special `nodefaults` channel to it. The commandline option should have any influence.

**Closed** 2020-10-29 16:20 UTC

**Comment by zxdawn** [comment] 2021-12-03 14:13
I tried to use a mirror like this:
```
micromamba create -n test matplotlib -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

But I got this error:
```

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/noarch       [====================] (00m:00s) No change
pkgs/free/noarch         [====================] (00m:00s) No change
pkgs/pro/linux-64        [====================] (00m:00s) No change
pkgs/msys2/noarch        [====================] (00m:00s) No change
cloud/linux-64           [====================] (00m:00s) 404 Failed
pkgs/free/linux-64       [====================] (00m:00s) No change
pkgs/pro/noarch          [====================] (00m:00s) No change
pkgs/main/linux-64       [====================] (00m:00s) No change
cloud/noarch             [====================] (00m:00s) 404 Failed
critical Multi-download failed.
```

So, is url not supported yet?

**Comment by emlys** [comment] 2025-06-16 21:53
It would be very useful if micromamba did support `--override-channels`. Since this warning has recently started appearing whenever the default channel is included:
```
  warning  libmamba 'repo.anaconda.com', a commercial channel hosted by Anaconda.com, is used.
      
  warning  libmamba Please make sure you understand Anaconda Terms of Services.
      
  warning  libmamba See: https://legal.anaconda.com/policies/en/
```
we are taking care to always use `--override-channels -c conda-forge` and it seems like a pretty common use case (we want our software to be usable to organizations with over 200 employees, which rules out the default channel). I think we should not have to create an environment file for this functionality.
