### ISSUE TITLE
Installing packages fails due to missing "bin" directory

### ISSUE THREAD

**Issue by jochenott** [mamba-org/mamba#2552] opened 2023-05-30 14:03 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

"no such file or directory"

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I'm using `docker.io/mambaorg/micromamba:bullseye-slim` and an explicit environment file to create reproducible conda environments. In some cases, installation fails with this error:

```
Linking alembic-1.11.1-pyhd8ed1ab_0
#7 6.794 error    libmamba Error opening for writing "/opt/conda/bin/alembic": No such file or directory
#7 6.824 critical libmamba filesystem error: cannot set permissions: No such file or directory [/opt/conda/bin/alembic]
#7 ERROR: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -f /tmp/env.txt" did not complete successfully: exit code: 1
```

In some cases, I only see the error message (line with "No such file or directory"), but without an exit code 1.

To reproduce, use this `Dockerfile`:
```
FROM docker.io/mambaorg/micromamba:1.4.3-bullseye-slim

COPY env.txt /tmp/

# workaround; see below
# RUN mkdir /opt/conda/bin
RUN  micromamba install -y -n base -f /tmp/env.txt
```

with this `env.txt` (which is derived from merely `alembic` and its dependencies, although I think this would happen also for other packages):
```
@EXPLICIT
https://conda.anaconda.org/conda-forge/noarch/alembic-1.11.1-pyhd8ed1ab_0.conda#6a55e123397b42b79c48b31d1b7a91b8
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2#d7c89558ba9fa0495403155b64376d81
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2023.5.7-hbcca054_0.conda#f5c65075fc34438d5b456c7f3f5ab695
https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.40-h41732ed_0.conda#7aca3059a1729aa76c597603f10b0dd3
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-12.2.0-h46fd767_19.tar.bz2#1030b1f38c129f2634eae026f704fe60
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.11-3_cp311.conda#c2e2630ddb68cf52eec74dc7dfab20b5
https://conda.anaconda.org/conda-forge/noarch/tzdata-2023c-h71feb2d_0.conda#939e3e74d8be4dac89ce83b20de2492a
https://conda.anaconda.org/conda-forge/linux-64/libgomp-12.2.0-h65d4601_19.tar.bz2#cedcee7c064c01c403f962c9e8d3c373
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-2_gnu.tar.bz2#73aaf86a425cc6e73fcf236a5a46396d
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-12.2.0-h65d4601_19.tar.bz2#e4c94f80aef025c17ab0828cd85ef535
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.6-h166bdaf_0.tar.bz2#2161070d867d1b1204ea749c8eec4ef0
https://conda.anaconda.org/conda-forge/linux-64/openssl-3.1.0-hd590300_3.conda#8f24d371ed9efb3f0b0de383fb81d51c
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.3-h27087fc_1.tar.bz2#4acfc691e64342b9dae57cf2adc63238
https://conda.anaconda.org/conda-forge/linux-64/libzlib-1.2.13-h166bdaf_4.tar.bz2#f3f9de449d32ca9b9c66a22863c96f41
https://conda.anaconda.org/conda-forge/linux-64/libuuid-2.38.1-h0b41bf4_0.conda#40b61aab5c7ba9ff276c41cfffe6b80b
https://conda.anaconda.org/conda-forge/linux-64/libnsl-2.0.0-h7f98852_0.tar.bz2#39b1328babf85c7c3a61636d9cd50206
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.4.2-h7f98852_5.tar.bz2#d645c6d2ac96843a2bfaccd2d62b3ac3
https://conda.anaconda.org/conda-forge/linux-64/libexpat-2.5.0-hcb278e6_1.conda#6305a3dd2752c76335295da4e581f2fd
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h7f98852_4.tar.bz2#a1fd65c7ccbf10880423d82bca54eb54
https://conda.anaconda.org/conda-forge/linux-64/readline-8.2-h8228510_1.conda#47d31b792659ce70f470b5c82fdfb7a4
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.12-h27826a3_0.tar.bz2#5b8c42eb62e9fc961af70bdd6a26e168
https://conda.anaconda.org/conda-forge/linux-64/libsqlite-3.42.0-h2797004_0.conda#fdaae20a1cf7cd62130a0973190a31b7
https://conda.anaconda.org/conda-forge/linux-64/python-3.11.3-h2755cc3_0_cpython.conda#37005ea5f68df6a8a381b70cf4d4a160
https://conda.anaconda.org/conda-forge/noarch/wheel-0.40.0-pyhd8ed1ab_0.conda#49bb0d9e60ce1db25e151780331bb5f3
https://conda.anaconda.org/conda-forge/noarch/setuptools-67.7.2-pyhd8ed1ab_0.conda#3b68bc43ec6baa48f7354a446267eefe
https://conda.anaconda.org/conda-forge/noarch/pip-23.1.2-pyhd8ed1ab_0.conda#7288da0d36821349cf1126e8670292df
https://conda.anaconda.org/conda-forge/noarch/zipp-3.15.0-pyhd8ed1ab_0.conda#13018819ca8f5b7cc675a8faf1f5fedf
https://conda.anaconda.org/conda-forge/noarch/typing_extensions-4.6.2-pyha770c72_0.conda#5a4a270e5a3f93846d6bade2f71fa440
https://conda.anaconda.org/conda-forge/linux-64/markupsafe-2.1.2-py311h2582759_0.conda#adb20bd57069614552adac60a020c36d
https://conda.anaconda.org/conda-forge/linux-64/greenlet-2.0.2-py311hb755f60_1.conda#82f9885f18cc7ba9bca6687ac97f1d65
https://conda.anaconda.org/conda-forge/noarch/importlib_resources-5.12.0-pyhd8ed1ab_0.conda#e5fd2260a231ee63b6969f4801082f2b
https://conda.anaconda.org/conda-forge/noarch/importlib-metadata-6.6.0-pyha770c72_0.conda#f91a5d5175fb7ff2a91952ec7da59cb9
https://conda.anaconda.org/conda-forge/noarch/typing-extensions-4.6.2-hd8ed1ab_0.conda#f676553904bb8f7c1dfe71c9db0d9ba7
https://conda.anaconda.org/conda-forge/noarch/mako-1.2.4-pyhd8ed1ab_0.tar.bz2#0d072f0edc017b6318dbab701e053f94
https://conda.anaconda.org/conda-forge/linux-64/sqlalchemy-2.0.15-py311h459d7ec_0.conda#d2199e4c33e24003103845ab9b07469e
```

Running this through `docker build . --progress=plain --no-cache` gives the above error.

Using the line "mkdir /opt/conda/bin" (commented out above in the Dockerfile) works around the issue.

I can't say whether this is a bug in `micromamba` which fails to create the directory `/opt/conda/bin` or in the docker images, which might need to already include the directory `/opt/conda/bin`.

### Logs

```shell
#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 217B done
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/mambaorg/micromamba:1.4.3-bullseye-slim
#3 DONE 0.7s

#4 [1/3] FROM docker.io/mambaorg/micromamba:1.4.3-bullseye-slim@sha256:25b00e28c39abc2e698943c2279fa865d0ec7c97891c7faecafb5c6417313e71
#4 CACHED

#5 [internal] load build context
#5 transferring context: 29B done
#5 DONE 0.0s

#6 [2/3] COPY env.txt /tmp/
#6 DONE 0.0s

#7 [3/3] RUN  micromamba install -y -n base -f /tmp/env.txt
#7 0.279
#7 0.279                                            __
#7 0.279           __  ______ ___  ____ _____ ___  / /_  ____ _
#7 0.279          / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
#7 0.279         / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
#7 0.279        / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
#7 0.279       /_/
#7 0.279
#7 0.681 Transaction
#7 0.681
#7 0.681   Prefix: /opt/conda
#7 0.681
#7 0.681   Updating specs:
#7 0.681
#7 0.681    - conda-forge/noarch::alembic==1.11.1=pyhd8ed1ab_0[md5=6a55e123397b42b79c48b31d1b7a91b8]
#7 0.681    - conda-forge/linux-64::_libgcc_mutex==0.1=conda_forge[md5=d7c89558ba9fa0495403155b64376d81]
#7 0.681    - conda-forge/linux-64::ca-certificates==2023.5.7=hbcca054_0[md5=f5c65075fc34438d5b456c7f3f5ab695]
#7 0.681    - conda-forge/linux-64::ld_impl_linux-64==2.40=h41732ed_0[md5=7aca3059a1729aa76c597603f10b0dd3]
#7 0.681    - conda-forge/linux-64::libstdcxx-ng==12.2.0=h46fd767_19[md5=1030b1f38c129f2634eae026f704fe60]
#7 0.681    - conda-forge/linux-64::python_abi==3.11=3_cp311[md5=c2e2630ddb68cf52eec74dc7dfab20b5]
#7 0.681    - conda-forge/noarch::tzdata==2023c=h71feb2d_0[md5=939e3e74d8be4dac89ce83b20de2492a]
#7 0.681    - conda-forge/linux-64::libgomp==12.2.0=h65d4601_19[md5=cedcee7c064c01c403f962c9e8d3c373]
#7 0.681    - conda-forge/linux-64::_openmp_mutex==4.5=2_gnu[md5=73aaf86a425cc6e73fcf236a5a46396d]
#7 0.681    - conda-forge/linux-64::libgcc-ng==12.2.0=h65d4601_19[md5=e4c94f80aef025c17ab0828cd85ef535]
#7 0.681    - conda-forge/linux-64::xz==5.2.6=h166bdaf_0[md5=2161070d867d1b1204ea749c8eec4ef0]
#7 0.681    - conda-forge/linux-64::openssl==3.1.0=hd590300_3[md5=8f24d371ed9efb3f0b0de383fb81d51c]
#7 0.681    - conda-forge/linux-64::ncurses==6.3=h27087fc_1[md5=4acfc691e64342b9dae57cf2adc63238]
#7 0.681    - conda-forge/linux-64::libzlib==1.2.13=h166bdaf_4[md5=f3f9de449d32ca9b9c66a22863c96f41]
#7 0.681    - conda-forge/linux-64::libuuid==2.38.1=h0b41bf4_0[md5=40b61aab5c7ba9ff276c41cfffe6b80b]
#7 0.681    - conda-forge/linux-64::libnsl==2.0.0=h7f98852_0[md5=39b1328babf85c7c3a61636d9cd50206]
#7 0.681    - conda-forge/linux-64::libffi==3.4.2=h7f98852_5[md5=d645c6d2ac96843a2bfaccd2d62b3ac3]
#7 0.681    - conda-forge/linux-64::libexpat==2.5.0=hcb278e6_1[md5=6305a3dd2752c76335295da4e581f2fd]
#7 0.681    - conda-forge/linux-64::bzip2==1.0.8=h7f98852_4[md5=a1fd65c7ccbf10880423d82bca54eb54]
#7 0.681    - conda-forge/linux-64::readline==8.2=h8228510_1[md5=47d31b792659ce70f470b5c82fdfb7a4]
#7 0.681    - conda-forge/linux-64::tk==8.6.12=h27826a3_0[md5=5b8c42eb62e9fc961af70bdd6a26e168]
#7 0.681    - conda-forge/linux-64::libsqlite==3.42.0=h2797004_0[md5=fdaae20a1cf7cd62130a0973190a31b7]
#7 0.681    - conda-forge/linux-64::python==3.11.3=h2755cc3_0_cpython[md5=37005ea5f68df6a8a381b70cf4d4a160]
#7 0.681    - conda-forge/noarch::wheel==0.40.0=pyhd8ed1ab_0[md5=49bb0d9e60ce1db25e151780331bb5f3]
#7 0.681    - conda-forge/noarch::setuptools==67.7.2=pyhd8ed1ab_0[md5=3b68bc43ec6baa48f7354a446267eefe]
#7 0.681    - conda-forge/noarch::pip==23.1.2=pyhd8ed1ab_0[md5=7288da0d36821349cf1126e8670292df]
#7 0.681    - conda-forge/noarch::zipp==3.15.0=pyhd8ed1ab_0[md5=13018819ca8f5b7cc675a8faf1f5fedf]
#7 0.681    - conda-forge/noarch::typing_extensions==4.6.2=pyha770c72_0[md5=5a4a270e5a3f93846d6bade2f71fa440]
#7 0.681    - conda-forge/linux-64::markupsafe==2.1.2=py311h2582759_0[md5=adb20bd57069614552adac60a020c36d]
#7 0.682    - conda-forge/linux-64::greenlet==2.0.2=py311hb755f60_1[md5=82f9885f18cc7ba9bca6687ac97f1d65]
#7 0.682    - conda-forge/noarch::importlib_resources==5.12.0=pyhd8ed1ab_0[md5=e5fd2260a231ee63b6969f4801082f2b]
#7 0.682    - conda-forge/noarch::importlib-metadata==6.6.0=pyha770c72_0[md5=f91a5d5175fb7ff2a91952ec7da59cb9]
#7 0.682    - conda-forge/noarch::typing-extensions==4.6.2=hd8ed1ab_0[md5=f676553904bb8f7c1dfe71c9db0d9ba7]
#7 0.682    - conda-forge/noarch::mako==1.2.4=pyhd8ed1ab_0[md5=0d072f0edc017b6318dbab701e053f94]
#7 0.682    - conda-forge/linux-64::sqlalchemy==2.0.15=py311h459d7ec_0[md5=d2199e4c33e24003103845ab9b07469e]
#7 0.682
#7 0.682
#7 0.687   Package                 Version  Build               Channel         Size
#7 0.687 ─────────────────────────────────────────────────────────────────────────────
#7 0.687   Install:
#7 0.687 ─────────────────────────────────────────────────────────────────────────────
#7 0.687
#7 0.687   + _libgcc_mutex             0.1  conda_forge         conda-forge      0 B
#7 0.687   + _openmp_mutex             4.5  2_gnu               conda-forge      0 B
#7 0.687   + alembic                1.11.1  pyhd8ed1ab_0        conda-forge      0 B
#7 0.687   + bzip2                   1.0.8  h7f98852_4          conda-forge      0 B
#7 0.687   + ca-certificates      2023.5.7  hbcca054_0          conda-forge      0 B
#7 0.687   + greenlet                2.0.2  py311hb755f60_1     conda-forge      0 B
#7 0.687   + importlib-metadata      6.6.0  pyha770c72_0        conda-forge      0 B
#7 0.687   + importlib_resources    5.12.0  pyhd8ed1ab_0        conda-forge      0 B
#7 0.687   + ld_impl_linux-64         2.40  h41732ed_0          conda-forge      0 B
#7 0.687   + libexpat                2.5.0  hcb278e6_1          conda-forge      0 B
#7 0.687   + libffi                  3.4.2  h7f98852_5          conda-forge      0 B
#7 0.687   + libgcc-ng              12.2.0  h65d4601_19         conda-forge      0 B
#7 0.687   + libgomp                12.2.0  h65d4601_19         conda-forge      0 B
#7 0.687   + libnsl                  2.0.0  h7f98852_0          conda-forge      0 B
#7 0.687   + libsqlite              3.42.0  h2797004_0          conda-forge      0 B
#7 0.687   + libstdcxx-ng           12.2.0  h46fd767_19         conda-forge      0 B
#7 0.687   + libuuid                2.38.1  h0b41bf4_0          conda-forge      0 B
#7 0.687   + libzlib                1.2.13  h166bdaf_4          conda-forge      0 B
#7 0.687   + mako                    1.2.4  pyhd8ed1ab_0        conda-forge      0 B
#7 0.687   + markupsafe              2.1.2  py311h2582759_0     conda-forge      0 B
#7 0.687   + ncurses                   6.3  h27087fc_1          conda-forge      0 B
#7 0.687   + openssl                 3.1.0  hd590300_3          conda-forge      0 B
#7 0.687   + pip                    23.1.2  pyhd8ed1ab_0        conda-forge      0 B
#7 0.687   + python                 3.11.3  h2755cc3_0_cpython  conda-forge      0 B
#7 0.687   + python_abi               3.11  3_cp311             conda-forge      0 B
#7 0.687   + readline                  8.2  h8228510_1          conda-forge      0 B
#7 0.687   + setuptools             67.7.2  pyhd8ed1ab_0        conda-forge      0 B
#7 0.687   + sqlalchemy             2.0.15  py311h459d7ec_0     conda-forge      0 B
#7 0.687   + tk                     8.6.12  h27826a3_0          conda-forge      0 B
#7 0.687   + typing-extensions       4.6.2  hd8ed1ab_0          conda-forge      0 B
#7 0.687   + typing_extensions       4.6.2  pyha770c72_0        conda-forge      0 B
#7 0.687   + tzdata                  2023c  h71feb2d_0          conda-forge      0 B
#7 0.687   + wheel                  0.40.0  pyhd8ed1ab_0        conda-forge      0 B
#7 0.687   + xz                      5.2.6  h166bdaf_0          conda-forge      0 B
#7 0.687   + zipp                   3.15.0  pyhd8ed1ab_0        conda-forge      0 B
#7 0.687
#7 0.687   Summary:
#7 0.687
#7 0.687   Install: 35 packages
#7 0.687
#7 0.687   Total download: 0 B
#7 0.687
#7 0.687 ─────────────────────────────────────────────────────────────────────────────
#7 0.687
#7 0.687
#7 0.688
#7 0.688 Transaction starting
#7 6.747 Linking alembic-1.11.1-pyhd8ed1ab_0
#7 6.965 error    libmamba Error opening for writing "/opt/conda/bin/alembic": No such file or directory
#7 6.993 critical libmamba filesystem error: cannot set permissions: No such file or directory [/opt/conda/bin/alembic]
#7 ERROR: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -f /tmp/env.txt" did not complete successfully: exit code: 1
------
 > [3/3] RUN  micromamba install -y -n base -f /tmp/env.txt:
#7 0.687   Total download: 0 B
#7 0.687
#7 0.687 ─────────────────────────────────────────────────────────────────────────────
#7 0.687
#7 0.687
#7 0.688
#7 0.688 Transaction starting
#7 6.747 Linking alembic-1.11.1-pyhd8ed1ab_0
#7 6.965 error    libmamba Error opening for writing "/opt/conda/bin/alembic": No such file or directory
#7 6.993 critical libmamba filesystem error: cannot set permissions: No such file or directory [/opt/conda/bin/alembic]
------
Dockerfile:7
--------------------
   5 |     # workaround; see below
   6 |     # RUN mkdir /opt/conda/bin
   7 | >>> RUN  micromamba install -y -n base -f /tmp/env.txt
   8 |
--------------------
ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -f /tmp/env.txt" did not complete successfully: exit code: 1
```

**Comment by jonashaag** [comment] 2023-05-31 15:14
@maresb

**Comment by maresb** [comment] 2023-05-31 17:32
Hi @jonashaag, presumably the ping is in reference to micromamba-docker? I'm going to suggest that this issue lies outside of the micromamba-docker realm. The reason being that I was able to reproduce this issue in the regular Ubuntu image using `curl micro.mamba.pm/install.sh | bash`. The default root prefix generated by this command contains just an empty `conda-meta/` and `etc/profile.d/micromamba.sh`. The `bin/` directory is not present.

In principle we could work around this by creating `bin/` [here](https://github.com/mamba-org/micromamba-docker/blob/main/_dockerfile_setup_root_prefix.sh) alongside `conda-meta/`, but this doesn't address the underlying problem, which I understand to be that `libmamba` neither initializes the root prefix with `bin/` nor does it create it as necessary in the above-reported case.

Would it make sense to solve the issue by either initializing the root prefix with `bin/` or by ensuring that `bin/` gets created in the above-reported case? (In the first option, we would need to make the corresponding modification to micromamba-docker.)

**Comment by jonashaag** [comment] 2023-05-31 17:33
Oh, sorry and thanks for the explanation!

**Comment by jonashaag** [comment] 2023-05-31 17:34
I wonder why this hasn't bubbled up earlier

**Comment by AntoinePrv** [comment] 2023-06-23 08:53
Hello, thank you for reporting this.

You are getting this issue because the package are not properly sorted. Mamba tries to to link `alembic` before `python` is installed.
This is due to a bug in `micromamba env export --explicit` that is producing the reverse of what is expected :sweat_smile: 

A fix for this is coming in #2616.

On top of this, `micromamba create` with lockfile is trusting that the packages in the file are sorted.
Right now, explicit install does not have access to dependency information, since it does not need to download repodata.json. We could load that information after the package are downloaded, but since there is an ongoing significant refactor of `MTransaction`, I'll leave this for another issue.

In the meantime, you can fix your lockfile this by reversing all the entries in it.

**Closed** 2023-06-23 10:23 UTC
Labels: type::bug

**Comment by maresb** [comment] 2023-06-23 11:07
Wow, this is amazing. Thanks so much for tracking this down!!!

Thanks also for the detailed breakdown. One thing I don't understand is how creating `/opt/conda/bin` functioned as a workaround. Do you have any insight into this?

**Comment by AntoinePrv** [comment] 2023-06-23 13:46
Not sure, in my context creating it was not a solution. It may depend on said packages, `pyc` policy...

**Comment by jochenott** [comment] 2023-06-26 07:20
Thanks for looking into this. However, I'm not quite sure this is a valid fix.

First off, note that I did *not* create the environment file in my report with micromamba. The environment file was created with a small in-house tool that simply sorts all packages by name, alphabetically. This seemed like a valid option to me, since I could not find conda docs pointing out that this list needs to be sorted. On the contrary: many examples given in the conda docs such as this one:

https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments

do *not* sort the entries in the explicit environment file by dependencies (see e.g. how much down the line "python" is, although "mupy" and "pip" require it).

**Comment by AntoinePrv** [comment] 2023-06-26 07:45
@jochenott That is a good point. The conda specifications are loose, some would argue the specs files need to be topologically sorted, but I agree with you it is better not to make assumptions. Especially given the example you point to.

Since #2616 restore the previous behaviour, let's call it a feature request and track it in https://github.com/mamba-org/mamba/issues/2617.
