### ISSUE TITLE
[micromamba] annoyance: ERROR vs. warning

### ISSUE THREAD

**Issue by vjmp** [mamba-org/mamba#636] opened 2020-12-17 05:44 UTC
When running micromamba environment creation, we get lots of message like following:
_**ERROR**   link.cpp:693 **Clobberwarning**: "...\\Lib\\site-packages\\wheel\\__pycache__\\bdist_wheel.cpython-37.pyc_

And why is that annoying?

1. Text is red, so this must be important, right?
2. But it does not know which one it is, error or warning. So which is it?
3. And if it is actually error, why does it continue to build environment? Should it just exit with non-zero exit code?
4. And what should end user to do about them? Should error message tell what user can do to fix this?
5. And why should user  care about contents of __pycache__ folder, or .pyc files?

**Comment by wolfv** [comment] 2020-12-17 07:12
Hi, yes I agree we should make this less "severe" looking.

The problem is that multiple packages contain the same files (they "clobber" each other). So package B overwrites some files `...\Lib\site-packages\wheel\__pycache__\bdist_wheel.cpython-37.pyc` from package A. That is usually a packaging error and ideally should be fixed :)

However, the wheel package is a noarch package and the `pyc` file should be generated upon installation (and therefore it should not clobber). I am wondering if this is a legitimate issue in micromamba, beyond the annyoing warning?

**Comment by vjmp** [comment] 2020-12-17 09:35
Yes, but if it is packaging error, and developers of that package don't care [and are silently exclaiming that it is totally okay to have that error] and release that package anyway, then end user of that package cannot do anything about it, so should they even be warned.

And yes, it is just annoyance, but at least my heart "jumps" when I suddenly see red ERRORs appearing. And if they are meaningless, I know "learn" that there is no point of even exploring ANY of those red ERRORs, since I cannot do anything. And that leads "me" to ignore those different, important red ERRORs, since I have so learned.

**Comment by dhirschfeld** [comment] 2020-12-17 11:35
> *then end user of that package cannot do anything about it* 

The end user can open issues against the offending [`conda-forge`](https://github.com/conda-forge) feedstock or [`AnacondaRecipes`](https://github.com/AnacondaRecipes) feedstock as appropriate. A motivated user could even open a PR to fix the packaging issue themselves.


In this case however, inspecting the `wheel` package from [anaconda.org](https://anaconda.org/conda-forge/wheel/files) shows there is no `__pycache__` files in the package:

![image](https://user-images.githubusercontent.com/881019/102482894-a5cc0d80-40af-11eb-87a9-c527170300df.png)


..hence, *maybe* there is an issue with `micromamba`.

**Comment by obilaniu** [comment] 2020-12-17 11:46
`link.cpp` and "linking", as I understand it, implements a logic of precompiling Python bytecode on disk using the expected Python interpreter. But that's not only purely optional, it creates new files that can be clobbered by future upgrades (and separately it hurts the purely-statically-linked storyline by invoking unconditionally a potentially dynamically linked executable).

@wolfv what usecase was such "linking" intended to serve?

**Comment by wolfv** [comment] 2020-12-17 11:52
@obilaniu we are re-implementing the logic of conda's noarch packages here. the idea (for Python noarch packages) is to compile all `.py` files to `.pyc`, and add them to the index at install time. The main benefit is that when you modify, update or remove the noarch package this will be done cleanly, and all `.pyc` files will be deleted as well.

Mamba should make sure that `python` is (properly) installed before any `.pyc` compilation happens.

Yeah, @vjmp I am wondering if you were maybe overwriting existing envs somehow, which might trigger many such warnings.

**Comment by wolfv** [comment] 2020-12-17 11:53
And yes, I will "downgrade" this from a LOG_ERROR to some nicer form of warning. I totally agree with that.

**Comment by kariharju** [comment] 2020-12-17 16:12
The test yaml for the case is this:
```
channels:
  - defaults
  - conda-forge/label/jupyterlab_rc
  - conda-forge/label/jupyterlab_server_rc
  - conda-forge/label/jupyterlab_widgets_rc
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - jupyterlab ==3.0.0rc10
  - ipywidgets=7.5.1
  - jupyterlab_widgets
  - python-language-server=0.36.2
  - robotframework-lsp=0.6.1

```
We are just creating a new environment with this.

**Comment by wolfv** [comment] 2020-12-17 18:25
Ok, on Linux I see only a single clobberwarning for this environment:

```
ERROR   link.cpp:693 Clobberwarning: "/home/wolfv/micromamba/envs/testrobo/bin/jupyter-bundlerextension"
```

will have to check what's going on on Windows.

**Closed** 2020-12-21 16:34 UTC
