### ISSUE TITLE
mamba does not pull latest packages - unpinned dependencies

### ISSUE THREAD

**Issue by ncclementi** [mamba-org/mamba#1870] opened 2022-08-22 19:21 UTC
I'm creating a new environment where I want to install `dask-mongo`. I have three requirements `dask`, `distributed` and `pymongo` all of them unpinned, but if I try to create a clean environment by installing `dask-mongo`  with mamba by doing 

`mamba create -n test_ver python=3.9 dask-mongo`

It doesn't pull the latest versions. (I'd expect to pull dask and distributed 2022.8.1)

<details>
<summary>Packages that mamba pulls:</summary>

```
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
Transaction

  Prefix: /Users/ncclementi/mambaforge/envs/test_ver

  Updating specs:

   - python=3.9
   - dask-mongo


  Package                Version  Build                 Channel                     Size
──────────────────────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────────────────────

  + bokeh                  2.4.3  pyhd8ed1ab_3          conda-forge/noarch        Cached
  + bzip2                  1.0.8  h3422bc3_4            conda-forge/osx-arm64     Cached
  + ca-certificates    2022.6.15  h4653dfc_0            conda-forge/osx-arm64     Cached
  + click                  8.0.4  py39h2804cbe_0        conda-forge/osx-arm64     Cached
  + cloudpickle            2.1.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + cytoolz               0.12.0  py39h9eb174b_0        conda-forge/osx-arm64     Cached
  + dask                2022.3.0  pyhd8ed1ab_1          conda-forge/noarch        Cached
  + dask-core           2022.3.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + dask-mongo          2022.5.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + distributed         2022.3.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + freetype              2.12.1  hd633e50_0            conda-forge/osx-arm64     Cached
  + fsspec              2022.7.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + heapdict               1.0.1  py_0                  conda-forge/noarch        Cached
  + jinja2                 3.1.2  pyhd8ed1ab_1          conda-forge/noarch        Cached
  + jpeg                      9e  he4db4b2_2            conda-forge/osx-arm64     Cached
  + lcms2                   2.12  had6a04f_0            conda-forge/osx-arm64     Cached
  + lerc                   4.0.0  h9a09cb3_0            conda-forge/osx-arm64     Cached
  + libblas                3.9.0  16_osxarm64_openblas  conda-forge/osx-arm64     Cached
  + libcblas               3.9.0  16_osxarm64_openblas  conda-forge/osx-arm64     Cached
  + libcxx                14.0.6  h04bba0f_0            conda-forge/osx-arm64     Cached
  + libdeflate              1.13  h57fd34a_0            conda-forge/osx-arm64     Cached
  + libffi                 3.4.2  h3422bc3_5            conda-forge/osx-arm64     Cached
  + libgfortran            5.0.0  11_3_0_hd922786_25    conda-forge/osx-arm64     Cached
  + libgfortran5          11.3.0  hdaf2cc0_25           conda-forge/osx-arm64     Cached
  + liblapack              3.9.0  16_osxarm64_openblas  conda-forge/osx-arm64     Cached
  + libopenblas           0.3.21  openmp_hc731615_2     conda-forge/osx-arm64     Cached
  + libpng                1.6.37  h9b2ccdc_4            conda-forge/osx-arm64     Cached
  + libsqlite             3.39.2  h2c9beb0_1            conda-forge/osx-arm64     Cached
  + libtiff                4.4.0  hd6ca8d7_3            conda-forge/osx-arm64     Cached
  + libwebp-base           1.2.4  h57fd34a_0            conda-forge/osx-arm64     Cached
  + libxcb                  1.13  h9b22ae9_1004         conda-forge/osx-arm64     Cached
  + libzlib               1.2.12  ha287fd2_2            conda-forge/osx-arm64     Cached
  + llvm-openmp           14.0.4  hd125106_0            conda-forge/osx-arm64     Cached
  + locket                 1.0.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + lz4                    4.0.0  py39h049b86e_2        conda-forge/osx-arm64     Cached
  + lz4-c                  1.9.3  hbdafb3b_1            conda-forge/osx-arm64     Cached
  + markupsafe             2.1.1  py39hb18efdd_1        conda-forge/osx-arm64     Cached
  + msgpack-python         1.0.4  py39hab5e169_0        conda-forge/osx-arm64     Cached
  + ncurses                  6.3  h07bb92c_1            conda-forge/osx-arm64     Cached
  + numpy                 1.23.2  py39h3668e8b_0        conda-forge/osx-arm64     Cached
  + openjpeg               2.5.0  h5d4e404_1            conda-forge/osx-arm64     Cached
  + openssl                3.0.5  h7aea29f_1            conda-forge/osx-arm64     Cached
  + packaging               21.3  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pandas                 1.4.3  py39hd2dba81_0        conda-forge/osx-arm64     Cached
  + partd                  1.3.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pillow                 9.2.0  py39he45c975_2        conda-forge/osx-arm64     Cached
  + pip                   22.2.2  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + psutil                 5.9.1  py39h9eb174b_0        conda-forge/osx-arm64     Cached
  + pthread-stubs            0.4  h27ca646_1001         conda-forge/osx-arm64     Cached
  + pymongo                4.2.0  py39h6e3512e_1        conda-forge/osx-arm64     Cached
  + pyparsing              3.0.9  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + python                3.9.13  h96fcbfb_0_cpython    conda-forge/osx-arm64     Cached
  + python-dateutil        2.8.2  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + python_abi               3.9  2_cp39                conda-forge/osx-arm64     Cached
  + pytz                2022.2.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pyyaml                   6.0  py39hb18efdd_4        conda-forge/osx-arm64     Cached
  + readline               8.1.2  h46ed386_0            conda-forge/osx-arm64     Cached
  + setuptools            65.2.0  py39h2804cbe_0        conda-forge/osx-arm64     Cached
  + six                   1.16.0  pyh6c4a22f_0          conda-forge/noarch        Cached
  + sortedcontainers       2.4.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + sqlite                3.39.2  h40dfcc0_1            conda-forge/osx-arm64     Cached
  + tblib                  1.7.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + tk                    8.6.12  he1e0b03_0            conda-forge/osx-arm64     Cached
  + toolz                 0.12.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + tornado                  6.1  py39hb18efdd_3        conda-forge/osx-arm64     Cached
  + typing_extensions      4.3.0  pyha770c72_0          conda-forge/noarch        Cached
  + tzdata                 2022c  h191b570_0            conda-forge/noarch        Cached
  + wheel                 0.37.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + xorg-libxau            1.0.9  h27ca646_0            conda-forge/osx-arm64     Cached
  + xorg-libxdmcp          1.1.3  h27ca646_0            conda-forge/osx-arm64     Cached
  + xz                     5.2.6  h57fd34a_0            conda-forge/osx-arm64     Cached
  + yaml                   0.2.5  h3422bc3_2            conda-forge/osx-arm64     Cached
  + zict                   2.2.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + zstd                   1.5.2  h8128057_4            conda-forge/osx-arm64     Cached


```

</details>

Extra information:
- I have conda-forge set as the default channel. 
- I'm on arm64 (mac M1) using this miniforge https://github.com/conda-forge/miniforge
- If I do `conda create -n test_ver python=3.9 dask-mongo` It pulls the latest versions 

<details>
<summary>Packages that conda pulls:</summary>

```
  added / updated specs:
    - dask-mongo
    - python=3.9


The following NEW packages will be INSTALLED:

  bokeh              conda-forge/noarch::bokeh-2.4.3-pyhd8ed1ab_3
  brotlipy           conda-forge/osx-arm64::brotlipy-0.7.0-py39hb18efdd_1004
  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h3422bc3_4
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2022.6.15-h4653dfc_0
  certifi            conda-forge/osx-arm64::certifi-2022.6.15-py39h2804cbe_0
  cffi               conda-forge/osx-arm64::cffi-1.15.1-py39h04d3946_0
  click              conda-forge/osx-arm64::click-8.1.3-py39h2804cbe_0
  cloudpickle        conda-forge/noarch::cloudpickle-2.1.0-pyhd8ed1ab_0
  cryptography       conda-forge/osx-arm64::cryptography-37.0.4-py39h4cb6239_0
  cytoolz            conda-forge/osx-arm64::cytoolz-0.12.0-py39h9eb174b_0
  dask               conda-forge/noarch::dask-2022.8.1-pyhd8ed1ab_2
  dask-core          conda-forge/noarch::dask-core-2022.8.1-pyhd8ed1ab_0
  dask-mongo         conda-forge/noarch::dask-mongo-2022.5.0-pyhd8ed1ab_0
  distributed        conda-forge/noarch::distributed-2022.8.1-pyhd8ed1ab_2
  freetype           conda-forge/osx-arm64::freetype-2.12.1-hd633e50_0
  fsspec             conda-forge/noarch::fsspec-2022.7.1-pyhd8ed1ab_0
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  jinja2             conda-forge/noarch::jinja2-3.1.2-pyhd8ed1ab_1
  jpeg               conda-forge/osx-arm64::jpeg-9e-he4db4b2_2
  lcms2              conda-forge/osx-arm64::lcms2-2.12-had6a04f_0
  lerc               conda-forge/osx-arm64::lerc-4.0.0-h9a09cb3_0
  libblas            conda-forge/osx-arm64::libblas-3.9.0-16_osxarm64_openblas
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-16_osxarm64_openblas
  libcxx             conda-forge/osx-arm64::libcxx-14.0.6-h04bba0f_0
  libdeflate         conda-forge/osx-arm64::libdeflate-1.13-h57fd34a_0
  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5
  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0-11_3_0_hd922786_25
  libgfortran5       conda-forge/osx-arm64::libgfortran5-11.3.0-hdaf2cc0_25
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-16_osxarm64_openblas
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.21-openmp_hc731615_2
  libpng             conda-forge/osx-arm64::libpng-1.6.37-h9b2ccdc_4
  libsqlite          conda-forge/osx-arm64::libsqlite-3.39.2-h2c9beb0_1
  libtiff            conda-forge/osx-arm64::libtiff-4.4.0-hd6ca8d7_3
  libwebp-base       conda-forge/osx-arm64::libwebp-base-1.2.4-h57fd34a_0
  libxcb             conda-forge/osx-arm64::libxcb-1.13-h9b22ae9_1004
  libzlib            conda-forge/osx-arm64::libzlib-1.2.12-ha287fd2_2
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-14.0.4-hd125106_0
  locket             conda-forge/noarch::locket-1.0.0-pyhd8ed1ab_0
  lz4                conda-forge/osx-arm64::lz4-4.0.0-py39h049b86e_2
  lz4-c              conda-forge/osx-arm64::lz4-c-1.9.3-hbdafb3b_1
  markupsafe         conda-forge/osx-arm64::markupsafe-2.1.1-py39hb18efdd_1
  msgpack-python     conda-forge/osx-arm64::msgpack-python-1.0.4-py39hab5e169_0
  ncurses            conda-forge/osx-arm64::ncurses-6.3-h07bb92c_1
  numpy              conda-forge/osx-arm64::numpy-1.23.2-py39h3668e8b_0
  openjpeg           conda-forge/osx-arm64::openjpeg-2.5.0-h5d4e404_1
  openssl            conda-forge/osx-arm64::openssl-1.1.1q-ha287fd2_0
  packaging          conda-forge/noarch::packaging-21.3-pyhd8ed1ab_0
  pandas             conda-forge/osx-arm64::pandas-1.4.3-py39hd2dba81_0
  partd              conda-forge/noarch::partd-1.3.0-pyhd8ed1ab_0
  pillow             conda-forge/osx-arm64::pillow-9.2.0-py39he45c975_2
  pip                conda-forge/noarch::pip-22.2.2-pyhd8ed1ab_0
  psutil             conda-forge/osx-arm64::psutil-5.9.1-py39h9eb174b_0
  pthread-stubs      conda-forge/osx-arm64::pthread-stubs-0.4-h27ca646_1001
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pymongo            conda-forge/osx-arm64::pymongo-4.2.0-py39h6e3512e_1
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.0.9-pyhd8ed1ab_0
  pysocks            conda-forge/osx-arm64::pysocks-1.7.1-py39h2804cbe_5
  python             conda-forge/osx-arm64::python-3.9.13-hc596b02_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python_abi         conda-forge/osx-arm64::python_abi-3.9-2_cp39
  pytz               conda-forge/noarch::pytz-2022.2.1-pyhd8ed1ab_0
  pyyaml             conda-forge/osx-arm64::pyyaml-6.0-py39hb18efdd_4
  readline           conda-forge/osx-arm64::readline-8.1.2-h46ed386_0
  setuptools         conda-forge/osx-arm64::setuptools-65.2.0-py39h2804cbe_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.4.0-pyhd8ed1ab_0
  sqlite             conda-forge/osx-arm64::sqlite-3.39.2-h40dfcc0_1
  tblib              conda-forge/noarch::tblib-1.7.0-pyhd8ed1ab_0
  tk                 conda-forge/osx-arm64::tk-8.6.12-he1e0b03_0
  toolz              conda-forge/noarch::toolz-0.12.0-pyhd8ed1ab_0
  tornado            conda-forge/osx-arm64::tornado-6.1-py39hb18efdd_3
  typing_extensions  conda-forge/noarch::typing_extensions-4.3.0-pyha770c72_0
  tzdata             conda-forge/noarch::tzdata-2022c-h191b570_0
  urllib3            conda-forge/noarch::urllib3-1.26.11-pyhd8ed1ab_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xorg-libxau        conda-forge/osx-arm64::xorg-libxau-1.0.9-h27ca646_0
  xorg-libxdmcp      conda-forge/osx-arm64::xorg-libxdmcp-1.1.3-h27ca646_0
  xz                 conda-forge/osx-arm64::xz-5.2.6-h57fd34a_0
  yaml               conda-forge/osx-arm64::yaml-0.2.5-h3422bc3_2
  zict               conda-forge/noarch::zict-2.2.0-pyhd8ed1ab_0
  zstd               conda-forge/osx-arm64::zstd-1.5.2-h8128057_4
```

</details>

**Comment by jonashaag** [comment] 2022-08-22 21:17
Interesting. What happens if you pin `distributed=2022.8.1` in `mamba create`?

**Comment by phobson** [comment] 2022-08-22 23:06
@jonashaag I just tested this out and mamba pulls the expected versions of dask and a distributed

**Comment by jonashaag** [comment] 2022-08-23 11:43
I think this a duplicate of https://github.com/mamba-org/mamba/issues/1581. `distributed=2022.8.1` adds a dependency to `cryptography` that needs `openssl` 1 but Mamba tries to install `openssl` 3.

**Closed by jonashaag** 2022-08-23 11:43 UTC
