### ISSUE TITLE
Powershell "MambaModuleArgs" Variable not found.

### ISSUE THREAD

**Issue by Mukul1127** [mamba-org/mamba#2651] opened 2023-07-04 16:04 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

MambaModuleArgs

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

When Powershell Core starts, it gives this error:
```pwsh
Remove-Variable:
Line |
   3 |  Remove-Variable MambaModuleArgs
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find a variable with the name 'MambaModuleArgs'.
```
When Powershell 5.1 starts, it still gives this error:
```pwsh
Remove-Variable : Cannot find a variable with the name 'MambaModuleArgs'.
At line:3 char:1
+ Remove-Variable MambaModuleArgs
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MambaModuleArgs:String) [Remove-Variable], ItemNotFoundException
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand
```

### mamba info / micromamba info

```shell
libmamba version : 1.4.6
     micromamba version : 1.4.6
           curl version : libcurl/8.1.2-DEV Schannel zlib/1.2.13
     libarchive version : libarchive 3.6.2 zlib/1.2.13 liblzma/5.4.3 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.5
       envs directories : C:\Users\mukul\micromamba\envs
          package cache : C:\Users\mukul\micromamba\pkgs
                          C:\Users\mukul\.mamba\pkgs
                          C:\Users\mukul\AppData\Roaming\.mamba\pkgs
            environment : None (not found)
           env location : -
      user config files : C:\Users\mukul\.mambarc
 populated config files :
       virtual packages : __win=0=0
                          __archspec=1=x86_64
                          __cuda=12.2=0
               channels :
       base environment : C:\Users\mukul\micromamba
               platform : win-64
```

### Logs

```shell
Not Applicable
```

### environment.yml

```yaml
Not Applicable
```

### ~/.condarc

```yaml
Not Applicable
```

**Comment by AntoinePrv** [comment] 2023-07-06 13:23
Thanks for reporting, do you notice any failing feature on `mamba`?

**Comment by firai** [comment] 2023-07-08 18:09
I seem to also be getting this. In my case, this causes shell hook to fail, which in turn prevents me from activating.

**Comment by Mukul1127** [comment] 2023-07-08 18:13
> Thanks for reporting, do you notice any failing feature on `mamba`?

Nope

**Comment by Mukul1127** [comment] 2023-07-08 18:13
Not using micromamba yet because it doesn't seem to work because of this issue

**Comment by Mukul1127** [comment] 2023-07-08 18:15
> I seem to also be getting this. In my case, this causes shell hook with `micromamba` to fail, which in turn prevents `micromamba` from activating.

Exactly what I'm getting

**Comment by mkmark** [comment] 2023-07-17 00:00
add a line `$MambaModuleArgs = @{}` in `%UserProfile%/Documents/WindowsPowerShell/profile.ps1` fixes the issue:

```powershell
#region mamba initialize
# !! Contents within this block are managed by 'mamba shell init' !!
$Env:MAMBA_ROOT_PREFIX = "..."
$Env:MAMBA_EXE = "..."
$MambaModuleArgs = @{}
(& $Env:MAMBA_EXE 'shell' 'hook' -s 'powershell' -p $Env:MAMBA_ROOT_PREFIX) | Out-String | Invoke-Expression
#endregion
```

**Comment by AntoinePrv** [comment] 2023-07-21 09:37
> ```Remove-Variable -Name MambaModuleArgs -ErrorAction SilentlyContinue```

That seems like a safe fix, would you be willing to send a PR?

**Comment by kfsone** [comment] 2023-08-17 16:24
If it's expected to be provided outside the block, why is it the block trying to remove it?

**Comment by chawyehsu** [comment] 2023-08-17 17:11
> > `Remove-Variable -Name MambaModuleArgs -ErrorAction SilentlyContinue`
> 
> That seems like a safe fix, would you be willing to send a PR?

I don't think that's the right fix for this issue. The acutal cause of this is the hook script of PowerShell was not generated properly. From the activation unit test we can see:

https://github.com/mamba-org/mamba/blob/9438ac77d2f4aa5eb5bcde66e04c19514a4c026a/micromamba/tests/test_activation.py#L928-L931

there **should be** a `$MambaModuleArgs = @{ChangePs1 = $True}` declaration generated to the PowerShell hook, however it does not actually present in the hook script micromamba generates.

```powershell
#region mamba initialize
# !! Contents within this block are managed by 'mamba shell init' !!
$Env:MAMBA_ROOT_PREFIX = '...'
$Env:MAMBA_EXE = '...'
#    <-------------- Should $MambaModuleArgs be here
(& $Env:MAMBA_EXE 'shell' 'hook' -s 'powershell' -p $Env:MAMBA_ROOT_PREFIX) | Out-String | Invoke-Expression
#endregion
```
 
The root cause is that the Abstract Activator Builder forgets to apply [`hook_preamble()`](https://github.com/mamba-org/mamba/blob/9438ac77d2f4aa5eb5bcde66e04c19514a4c026a/libmamba/src/core/activation.cpp#L1021) for PowerShell. This also causes another bug of mamba not been able to reflect the `change_ps1` setting in PowerShell.

I may file a PR to address this issue.

**Comment by AntoinePrv** [comment] 2023-08-21 08:28
Thank you everyone for bringing feedback to the discussion, I'm myself not knowledgeable about Powershell.
I agree with @chawyehsu that this code was here for a while, so this is symptomatic of a deeper problem than just silencing the warning.

let's try to go with #2761, I'll rebase it as soon as the CI is green.

**Closed** 2023-08-21 11:36 UTC
