### ISSUE TITLE
mamba claims it cannot find python 3.7, even when py37 already installed in the environment

### ISSUE THREAD

**Issue by tpanza** [mamba-org/mamba#1844] opened 2022-08-06 20:47 UTC
Hello, might this be some weird edge case with how the mamba solver is resolving dependencies, especially with the `build` attribute?

```
$ mamba install "python=3.7" cudatoolkit=11.1 cudnn=8.0 pytorch=1.8 "torchvision=0.9=*py37_cu111*" --verbose

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.25.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['python=3.7', 'cudatoolkit=11.1', 'cudnn=8.0', 'pytorch=1.8', 'torchvision==0.9[build=*py37_cu111*]']

info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/_libgcc_mutex-0.1-conda_forge.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/ca-certificates-2022.6.15-ha878542_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/ld_impl_linux-64-2.36.1-hea4e1c9_2.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libstdcxx-ng-12.1.0-ha89aaad_16.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libgomp-12.1.0-h8d9b700_16.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/_openmp_mutex-4.5-2_gnu.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libgcc-ng-12.1.0-h8d9b700_16.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libffi-3.4.2-h7f98852_5.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libnsl-2.0.0-h7f98852_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libzlib-1.2.12-h166bdaf_2.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/ncurses-6.3-h27087fc_1.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/openssl-3.0.5-h166bdaf_1.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/xz-5.2.5-h516909a_1.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/readline-8.1.2-h0f457ee_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/tk-8.6.12-h27826a3_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/zlib-1.2.12-h166bdaf_2.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/sqlite-3.39.2-h4ff8645_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/python-3.7.12-hf930737_100_cpython.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/python_abi-3.7-2_cp37m.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/wheel-0.37.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/setuptools-63.4.1-py37h89c1867_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/pip-22.2.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/bzip2-1.0.8-h7f98852_4.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/c-ares-1.18.1-h7f98852_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/expat-2.4.8-h27087fc_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/keyutils-1.6.1-h166bdaf_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libev-4.33-h516909a_1.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libiconv-1.16-h516909a_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/gettext-0.19.8.1-h73d1719_1008.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libedit-3.1.20191231-he28a2e2_2.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/perl-5.32.1-2_h7f98852_perl5.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/krb5-1.19.3-h08a2579_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libnghttp2-1.47.0-he49606f_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libssh2-1.10.0-ha35d2d1_2.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/pcre2-10.37-h032f7d1_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/libcurl-7.83.1-h2283fc2_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/curl-7.83.1-h2283fc2_0.json"
info     libmamba Loading single package record: "/home/ec2-user/mambaforge/envs/omnidetr/conda-meta/git-2.37.1-pl5321h04cb727_0.json"
info     libmamba Reading cache files '/tmp/tmp5zn5yoqh.*' for repo index 'installed'
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/nvidia/linux-64/repodata.json'
info     libmamba Found cache at '/home/ec2-user/mambaforge/pkgs/cache/c9ddbd6b.json'
info     libmamba No valid cache found
info     libmamba Expired cache (or invalid mod/etag headers) found at '/home/ec2-user/mambaforge/pkgs'
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/nvidia/noarch/repodata.json'
info     libmamba Found cache at '/home/ec2-user/mambaforge/pkgs/cache/b121c3e7.json'
info     libmamba No valid cache found
info     libmamba Expired cache (or invalid mod/etag headers) found at '/home/ec2-user/mambaforge/pkgs'
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/pytorch/linux-64/repodata.json'
info     libmamba Found cache at '/home/ec2-user/mambaforge/pkgs/cache/ee0ed9e9.json'
pytorch/linux-64                                            Using cache
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/pytorch/noarch/repodata.json'
info     libmamba Found cache at '/home/ec2-user/mambaforge/pkgs/cache/edb1952f.json'
pytorch/noarch                                              Using cache
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/conda-forge/linux-64/repodata.json'
info     libmamba Found cache at '/home/ec2-user/mambaforge/pkgs/cache/497deca9.json'
conda-forge/linux-64                                        Using cache
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/conda-forge/noarch/repodata.json'
info     libmamba Found cache at '/home/ec2-user/mambaforge/pkgs/cache/09cdf8bf.json'
conda-forge/noarch                                          Using cache
info     libmamba Starting to download targets
[+] 0.2s
nvidia/linux-64 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.2s
nvidia/noarch   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.2sinfo     libmamba Transfer done for 'nvidia/linux-64'
nvidia/linux-64                                               No change
[+] 0.6s
nvidia/noarch ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.6sinfo     libmamba Transfer done for 'nvidia/noarch'
info     libmamba Transfer finalized, status: 304 [https://conda.anaconda.org/nvidia/noarch/repodata.json] 0 bytes
nvidia/noarch                                                 No change
Channel: nvidia[linux-64,noarch], platform: linux-64, prio: 3 : 0
Cache path:  /home/ec2-user/mambaforge/pkgs/cache/c9ddbd6b.json
info     libmamba Reading cache files '/home/ec2-user/mambaforge/pkgs/cache/c9ddbd6b.*' for repo index 'https://conda.anaconda.org/nvidia/linux-64'
info     libmamba Writing SOLV file 'c9ddbd6b.solv'
Channel: nvidia[linux-64,noarch], platform: noarch, prio: 3 : 0
Cache path:  /home/ec2-user/mambaforge/pkgs/cache/b121c3e7.json
info     libmamba Reading cache files '/home/ec2-user/mambaforge/pkgs/cache/b121c3e7.*' for repo index 'https://conda.anaconda.org/nvidia/noarch'
info     libmamba Writing SOLV file 'b121c3e7.solv'
Channel: pytorch[linux-64,noarch], platform: linux-64, prio: 2 : 0
Cache path:  /home/ec2-user/mambaforge/pkgs/cache/ee0ed9e9.solv
info     libmamba Reading cache files '/home/ec2-user/mambaforge/pkgs/cache/ee0ed9e9.*' for repo index 'https://conda.anaconda.org/pytorch/linux-64'
Channel: pytorch[linux-64,noarch], platform: noarch, prio: 2 : 0
Cache path:  /home/ec2-user/mambaforge/pkgs/cache/edb1952f.solv
info     libmamba Reading cache files '/home/ec2-user/mambaforge/pkgs/cache/edb1952f.*' for repo index 'https://conda.anaconda.org/pytorch/noarch'
Channel: conda-forge[linux-64,noarch], platform: linux-64, prio: 1 : 0
Cache path:  /home/ec2-user/mambaforge/pkgs/cache/497deca9.solv
info     libmamba Reading cache files '/home/ec2-user/mambaforge/pkgs/cache/497deca9.*' for repo index 'https://conda.anaconda.org/conda-forge/linux-64'
Channel: conda-forge[linux-64,noarch], platform: noarch, prio: 1 : 0
Cache path:  /home/ec2-user/mambaforge/pkgs/cache/09cdf8bf.solv
info     libmamba Reading cache files '/home/ec2-user/mambaforge/pkgs/cache/09cdf8bf.*' for repo index 'https://conda.anaconda.org/conda-forge/noarch'
info     libmamba Parsing MatchSpec python=3.7
info     libmamba Parsing MatchSpec python=3.7
info     libmamba Adding job: python =3.7*
info     libmamba Parsing MatchSpec cudatoolkit=11.1
info     libmamba Parsing MatchSpec cudatoolkit=11.1
info     libmamba Adding job: cudatoolkit =11.1*
info     libmamba Parsing MatchSpec cudnn=8.0
info     libmamba Parsing MatchSpec cudnn=8.0
info     libmamba Adding job: cudnn =8.0*
info     libmamba Parsing MatchSpec pytorch=1.8
info     libmamba Parsing MatchSpec pytorch=1.8
info     libmamba Adding job: pytorch =1.8*
info     libmamba Parsing MatchSpec torchvision==0.9[build=*py37_cu111*]
info     libmamba Parsing MatchSpec torchvision==0.9[build=*py37_cu111*]
info     libmamba Adding job: torchvision 0.9 *py37_cu111*
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec openssl
info     libmamba Problem count: 1
Encountered problems while solving:
  - package torchvision-0.9.0-py37_cu111 requires python >=3.7,<3.8.0a0, but none of the providers can be installed

info     libmamba Freeing solver.
info     libmamba Freeing pool.
```

Output of `mamba info`:

```

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.25.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : omnidetr
    active env location : /home/ec2-user/mambaforge/envs/omnidetr
            shell level : 2
       user config file : /home/ec2-user/.condarc
 populated config files : /home/ec2-user/mambaforge/.condarc
                          /home/ec2-user/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __linux=5.10.130=0
                          __glibc=2.26=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/ec2-user/mambaforge  (writable)
      conda av data dir : /home/ec2-user/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/nvidia/linux-64
                          https://conda.anaconda.org/nvidia/noarch
                          https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/ec2-user/mambaforge/pkgs
                          /home/ec2-user/.conda/pkgs
       envs directories : /home/ec2-user/mambaforge/envs
                          /home/ec2-user/.conda/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.9.13 Linux/5.10.130-118.517.amzn2.x86_64 amzn/2 glibc/2.26
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

Contents of `~/.condarc`:

```
channels:
  - nvidia
  - pytorch
  - conda-forge
```

**Comment by jonashaag** [comment] 2022-08-06 21:05
Removing some requirements gives this:


```
mamba install --dry-run "torchvision=0.9=*py37_cu111*" --verbose --platform linux-64 -c pytorch -c conda-forge -c nvidia
```

```
  - package torchvision-0.9.0-py37_cu111 requires jpeg <=9b, but none of the providers can be installed
```

**Comment by tpanza** [comment] 2022-08-06 21:05
If I try just this:

```
mamba install "torchvision=0.9=*py37_cu111*"
```

it fails with a different error:
```
Encountered problems while solving:
  - package torchvision-0.9.0-py37_cu111 requires jpeg <=9b, but none of the providers can be installed
```

Which is strange, since [builds of the `jpeg` package at version `9b` clearly exist on the conda-forge channel for linux-64](https://anaconda.org/conda-forge/jpeg/files?sort=basename&sort_order=asc&version=9b).

So it looks like there are cases where the solver cannot find packages that ought to be findable.

**Comment by tpanza** [comment] 2022-08-06 21:09
Simply trying to force an install of `jpeg` version `9b` also fails:

```
mamba install jpeg=9b -c conda-forge --override-channels
```

```
Looking for: ['jpeg=9b']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.7.*


Encountered problems while solving:
  - nothing provides requested jpeg 9b**
```

Why would mamba not find something that clearly exists?

**Comment by jonashaag** [comment] 2022-08-07 07:40
Does it conflict with Python 3.7?

**Comment by jonashaag** [comment] 2022-08-07 07:43
Can you try this in https://github.com/AntoinePrv/mamba-error-reporting? I hope it is easy to set that one up. cc @AntoinePrv

**Comment by AntoinePrv** [comment] 2022-08-08 09:23
> Can you try this in https://github.com/AntoinePrv/mamba-error-reporting? I hope it is easy to set that one up. cc @AntoinePrv

I tried it up, it's not mature enough to handle this.

> Simply trying to force an install of jpeg version 9b also fails:

> Does it conflict with Python 3.7?

I did try a single environment with `jpeg=9b` (without Python) and it fails. Maybe a problem with the version naming scheme? I've never seen that one...

**Comment by AntoinePrv** [comment] 2022-08-09 15:48
Update: I tried `micromamba repoquerry search jpeg` and found that `jpeg=9b` does not exsits.

```
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache


 Name Version Build         Channel             
─────────────────────────────────────────────────
 jpeg 9e      h166bdaf_1    conda-forge/linux-64
 jpeg 9e      h166bdaf_2    conda-forge/linux-64
 jpeg 9e      h7f98852_0    conda-forge/linux-64
 jpeg 9d      h36c2ea0_0    conda-forge/linux-64
 jpeg 9d      h516909a_0    conda-forge/linux-64
 jpeg 9c      h14c3975_1001 conda-forge/linux-64
 jpeg 8d      h166bdaf_1    conda-forge/linux-64
 jpeg 8d      h516909a_0    conda-forge/linux-64
```

> Which is strange, since [builds of the jpeg package at version 9b clearly exist on the conda-forge channel for linux-64](https://anaconda.org/conda-forge/jpeg/files?sort=basename&sort_order=asc&version=9b).

@tpanza looking closer at those files they are not in the main channel. You can select them adding `-c conda-forge/label/cf201901` to your channels.

**Comment by jjerphan** [comment] 2024-10-14 15:23
I am closing this issue since python 3.7 reached end of life in June 27th 2023 and since a relaxed version of the command can be used to get newer versions of package. Also it seems that the problem is rather due to an improperly published build of a dependency.

Feel free to comment or reopen this issue shall you face any similar problem. :slightly_smiling_face:

**Closed by jjerphan** 2024-10-14 15:23 UTC
Labels: type::bug
