### ISSUE TITLE
mamba failed to parse complicated re package spec as conda

### ISSUE THREAD

**Issue by holymonson** [mamba-org/mamba#3169] opened 2024-02-02 08:14 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

#1853

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Here is a complicated package spec `libblas[build=^.*(accelerate|mkl)$]`, conda could parse it correctly and give `libblas-3.9.0-21_osx64_accelerate`, while mamba wrongly gives `libblas-3.9.0-21_osx64_openblas`. It seems mamba simply omitted those selectors.

### mamba info / micromamba info

```shell
__    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : grb
    active env location : /usr/local/conda/envs/grb
            shell level : 2
       user config file : /Users/monson/.condarc
 populated config files : /usr/local/Caskroom/mambaforge/base/.condarc
                          /Users/monson/.config/conda/condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=12.7.3=0
                          __unix=0=0
       base environment : /usr/local/Caskroom/mambaforge/base  (writable)
      conda av data dir : /usr/local/Caskroom/mambaforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
          package cache : /Users/monson/Library/Caches/conda/pkgs
       envs directories : /usr/local/conda/envs
                          /Users/monson/.conda/envs
                          /usr/local/Caskroom/mambaforge/base/envs
               platform : osx-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Darwin/21.6.0 OSX/12.7.3
                UID:GID : 1000:20
             netrc file : None
           offline mode : False
```

### Logs

```log
<omit>

Looking for: ["libblas[build='^.*(accelerate|mkl)$']"]


info     libmamba Reading cache files '/var/folders/9j/yfdks5ds49dgpm0196xnbn_h0000z8/T/tmpzdjz9uo6.*' for repo index 'installed'
info     libsolv  number of solvables: 567395, memory used: 31029 K
info     libsolv  number of ids: 214541 + 312444
info     libsolv  string memory used: 838 K array + 3183 K data,  rel memory used: 3661 K array
info     libsolv  string hash memory: 2048 K, rel hash memory : 4096 K
info     libsolv  provide ids: 23120
info     libsolv  provide space needed: 590517 + 624888
info     libsolv  shrunk whatprovidesdata from 590517 to 590517
info     libsolv  shrunk whatprovidesauxdata from 590517 to 567394
info     libsolv  whatprovides memory used: 2062 K id array, 4747 K data
info     libsolv  whatprovidesaux memory used: 838 K id array, 2216 K data
info     libsolv  createwhatprovides took 52 ms
info     libmamba Parsing MatchSpec libblas[build='^.*(accelerate|mkl)$']
info     libmamba Parsing MatchSpec libblas[build='^.*(accelerate|mkl)$']
info     libmamba Adding job: libblas[build='^.*(accelerate|mkl)$']
info     libsolv  solver started
info     libsolv  dosplitprovides=0, noupdateprovide=0, noinfarchcheck=0
info     libsolv  allowuninstall=0, allowdowngrade=1, allownamechange=1, allowarchchange=0, allowvendorchange=0
info     libsolv  dupallowdowngrade=1, dupallownamechange=1, dupallowarchchange=1, dupallowvendorchange=1
info     libsolv  promoteepoch=0, forbidselfconflicts=0
info     libsolv  obsoleteusesprovides=0, implicitobsoleteusesprovides=0, obsoleteusescolors=0, implicitobsoleteusescolors=0
info     libsolv  dontinstallrecommended=0, addalreadyrecommended=0 onlynamespacerecommended=0
info     libsolv  obsoletes data: 1 entries
info     libsolv  added 0 pkg rules for installed solvables
info     libsolv  added 0 pkg rules for updaters of installed solvables
info     libsolv  added 76156 pkg rules for packages involved in a job
info     libsolv  added 0 pkg rules because of weak dependencies
info     libsolv  493 of 567394 installable solvables considered for solving
info     libsolv  pruned rules from 76157 to 76157
info     libsolv    binary: 75677
info     libsolv    normal: 479, 13214 literals
info     libsolv  pkg rule memory used: 1784 K
info     libsolv  pkg rule creation took 56 ms
info     libsolv  job: install providing libblas
info     libsolv    - job Rule #76163:
info     libsolv      libblas-3.8.0-10_blis [111442] (w1)
<omit similar lines>
info     libsolv      libblas-3.9.0-21_osx64_accelerate [329501]
info     libsolv      libblas-3.9.0-21_osx64_blis [329502]
info     libsolv      libblas-3.9.0-21_osx64_openblas [329503]
info     libsolv      next rules: 0 0
info     libsolv  choice rule creation took 1 ms
info     libsolv  76156 pkg rules, 2 * 3 update rules, 1 job rules, 0 infarch rules, 0 dup rules, 0 choice rules, 0 best rules, 0 yumobs rules
info     libsolv  0 black rules, 0 recommends rules, 0 repo priority rules
info     libsolv  overall rule memory used: 1785 K
info     libsolv  solving...
info     libsolv  resolving job rules
info     libsolv  prune_to_best_version_conda 132
info     libsolv  - libblas-3.8.0-10_blis [111442]
<omit similar lines>
info     libsolv  - libblas-3.9.0-21_osx64_accelerate [329501]
info     libsolv  - libblas-3.9.0-21_osx64_blis [329502]
info     libsolv  - libblas-3.9.0-21_osx64_openblas [329503]
info     libsolv  installing libblas-3.9.0-21_osx64_openblas

<omit>
```

### environment.yml

```yaml
name: grb-test
channels:
  - conda-forge
dependencies:
  - libblas[build=^.*(accelerate|mkl)$]
```

**Comment by jonashaag** [comment] 2024-02-02 09:17
Do the selectors work when not using regexes but simple wildcards?

**Comment by holymonson** [comment] 2024-02-04 11:36
> Do the selectors work when not using regexes but simple wildcards?

yes

**Comment by holymonson** [comment] 2024-02-05 05:52
cc @jaimergp @AntoinePrv @wolfv

**Comment by AntoinePrv** [comment] 2024-02-07 22:45
Hello, yes I can confirm this is not implemented, neither in libolv, nor (yet) in our replacement.

**Comment by jaimergp** [comment] 2024-02-08 18:09
This is a duplicate of https://github.com/mamba-org/mamba/issues/1853.

I submitted a PR for `libsolv` at https://github.com/openSUSE/libsolv/pull/506, but it never received attention.

**Comment by jonashaag** [comment] 2024-02-08 18:16
Try pinging the maintainer, worked for me

**Comment by AntoinePrv** [comment] 2024-02-08 19:33
We'll soon be able to provided our own matchspec, so the PR is not strictly required.
(matchspecs inside repodata.json are still being adressed by libsolv for now, as we would need to investigate if our MatchSpec bring a performance hit).

**Closed** 2024-03-20 17:52 UTC
Labels: type::bug
