### ISSUE TITLE
mamba install --rev x does not rollback environment

### ISSUE THREAD

**Issue by ahrib** [mamba-org/mamba#2836] opened 2023-09-14 01:37 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

962

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

In Conda, `conda list --revisions` and `conda install --rev REV_NUM` can be used to roll back accidental installs

As an example `conda install --rev 1` will effectively re-set the base environment

Expected behaviour
`mamba install --rev 1` will roll back the environment to revision 1
this behaviour was apparently implemented in mamba here: https://github.com/mamba-org/mamba/issues/962 
this behaviour was implemented in conda here: https://github.com/conda/conda/issues/1032

Actual behaviour
mamba attempts to perform a new install of an empty package list

### mamba info / micromamba info

```shell
mamba version : 1.5.1
     active environment : base
    active env location : C:\Users\ahribern\AppData\Local\mambaforge
            shell level : 1
       user config file : C:\Users\ahribern\.condarc
 populated config files : C:\Users\ahribern\AppData\Local\mambaforge\.condarc
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\ahribern\AppData\Local\mambaforge  (writable)
      conda av data dir : C:\Users\ahribern\AppData\Local\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\ahribern\AppData\Local\mambaforge\pkgs
                          C:\Users\ahribern\.conda\pkgs
                          C:\Users\ahribern\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\ahribern\AppData\Local\mambaforge\envs
                          C:\Users\ahribern\.conda\envs
                          C:\Users\ahribern\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.19045
          administrator : True
             netrc file : None
           offline mode : False
```

### Logs

```shell
Looking for: []

info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\boltons-23.0.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\brotli-1.1.0-hcfcfb64_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\brotli-bin-1.1.0-hcfcfb64_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\brotli-python-1.1.0-py311h12c1d0e_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\brotlipy-0.7.0-py311ha68e1ae_1005.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\bzip2-1.0.8-h8ffe710_4.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\ca-certificates-2023.7.22-h56e8100_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\certifi-2023.7.22-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\cffi-1.15.1-py311h7d9ee11_3.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\charset-normalizer-3.2.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\colorama-0.4.6-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\conda-23.7.4-py311h1ea47a8_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\conda-package-handling-2.2.0-pyh38be061_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\conda-package-streaming-0.9.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\cryptography-41.0.3-py311h28e9c30_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\fmt-10.1.1-h181d51b_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\idna-3.4-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\jsonpatch-1.32-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\jsonpointer-2.4-py311h1ea47a8_2.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\krb5-1.21.2-heb0366b_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libarchive-3.6.2-h6f8411a_1.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libbrotlicommon-1.1.0-hcfcfb64_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libbrotlidec-1.1.0-hcfcfb64_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libbrotlienc-1.1.0-hcfcfb64_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libcurl-8.3.0-hd5e4a3a_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libexpat-2.5.0-h63175ca_1.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libffi-3.4.2-h8ffe710_5.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libiconv-1.17-h8ffe710_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libmamba-1.5.1-h16d0179_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libmambapy-1.5.1-py311h0317a69_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libsolv-0.7.24-h12be248_4.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libsqlite-3.43.0-hcfcfb64_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libssh2-1.11.0-h7dfc565_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libxml2-2.11.5-hc3477c8_1.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\libzlib-1.2.13-hcfcfb64_5.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\lz4-c-1.9.4-hcfcfb64_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\lzo-2.10-he774522_1000.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\mamba-1.5.1-py311h8cb466b_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\menuinst-1.4.19-py311h1ea47a8_1.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\miniforge_console_shortcut-2.0-h57928b3_1.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\openssl-3.1.2-hcfcfb64_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\packaging-23.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\pip-23.2.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\pluggy-1.3.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\pybind11-abi-4-hd8ed1ab_3.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\pycosat-0.6.4-py311ha68e1ae_1.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\pycparser-2.21-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\pyopenssl-23.2.0-pyhd8ed1ab_1.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\pysocks-1.7.1-pyh0701188_6.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\python-3.11.5-h2628c8c_0_cpython.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\python_abi-3.11-3_cp311.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\pywin32-304-py311h12c1d0e_2.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\reproc-14.2.4-hcfcfb64_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\reproc-cpp-14.2.4-h63175ca_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\requests-2.31.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\ruamel.yaml-0.17.32-py311ha68e1ae_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\ruamel.yaml.clib-0.2.7-py311ha68e1ae_1.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\ruamel_yaml-0.15.80-py311ha68e1ae_1008.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\setuptools-68.2.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\six-1.16.0-pyh6c4a22f_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\sqlite-3.43.0-hcfcfb64_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\tk-8.6.12-h8ffe710_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\toolz-0.12.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\tqdm-4.66.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\tzdata-2023c-h71feb2d_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\ucrt-10.0.22621.0-h57928b3_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\urllib3-2.0.4-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\vc-14.3-h64f974e_17.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\vc14_runtime-14.36.32532-hfdfe4a8_17.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\vs2015_runtime-14.36.32532-h05e6639_17.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\wheel-0.41.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\win_inet_pton-1.1.0-pyhd8ed1ab_6.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\xz-5.2.6-h8d14728_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\yaml-0.2.5-h8ffe710_2.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\yaml-cpp-0.7.0-h63175ca_2.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\zlib-1.2.13-hcfcfb64_5.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\zstandard-0.19.0-py311ha68e1ae_0.json"
info     libmamba Loading single package record: "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\conda-meta\\zstd-1.5.5-h12be248_0.json"
info     libmamba Adding package record to repo __archspec
info     libmamba Adding package record to repo __win
info     libmamba Adding package record to repo boltons
info     libmamba Adding package record to repo brotli
info     libmamba Adding package record to repo brotli-bin
info     libmamba Adding package record to repo brotli-python
info     libmamba Adding package record to repo brotlipy
info     libmamba Adding package record to repo bzip2
info     libmamba Adding package record to repo ca-certificates
info     libmamba Adding package record to repo certifi
info     libmamba Adding package record to repo cffi
info     libmamba Adding package record to repo charset-normalizer
info     libmamba Adding package record to repo colorama
info     libmamba Adding package record to repo conda
info     libmamba Adding package record to repo conda-package-handling
info     libmamba Adding package record to repo conda-package-streaming
info     libmamba Adding package record to repo cryptography
info     libmamba Adding package record to repo fmt
info     libmamba Adding package record to repo idna
info     libmamba Adding package record to repo jsonpatch
info     libmamba Adding package record to repo jsonpointer
info     libmamba Adding package record to repo krb5
info     libmamba Adding package record to repo libarchive
info     libmamba Adding package record to repo libbrotlicommon
info     libmamba Adding package record to repo libbrotlidec
info     libmamba Adding package record to repo libbrotlienc
info     libmamba Adding package record to repo libcurl
info     libmamba Adding package record to repo libexpat
info     libmamba Adding package record to repo libffi
info     libmamba Adding package record to repo libiconv
info     libmamba Adding package record to repo libmamba
info     libmamba Adding package record to repo libmambapy
info     libmamba Adding package record to repo libsolv
info     libmamba Adding package record to repo libsqlite
info     libmamba Adding package record to repo libssh2
info     libmamba Adding package record to repo libxml2
info     libmamba Adding package record to repo libzlib
info     libmamba Adding package record to repo lz4-c
info     libmamba Adding package record to repo lzo
info     libmamba Adding package record to repo mamba
info     libmamba Adding package record to repo menuinst
info     libmamba Adding package record to repo miniforge_console_shortcut
info     libmamba Adding package record to repo openssl
info     libmamba Adding package record to repo packaging
info     libmamba Adding package record to repo pip
info     libmamba Adding package record to repo pluggy
info     libmamba Adding package record to repo pybind11-abi
info     libmamba Adding package record to repo pycosat
info     libmamba Adding package record to repo pycparser
info     libmamba Adding package record to repo pyopenssl
info     libmamba Adding package record to repo pysocks
info     libmamba Adding package record to repo python
info     libmamba Adding package record to repo python_abi
info     libmamba Adding package record to repo pywin32
info     libmamba Adding package record to repo reproc
info     libmamba Adding package record to repo reproc-cpp
info     libmamba Adding package record to repo requests
info     libmamba Adding package record to repo ruamel.yaml
info     libmamba Adding package record to repo ruamel.yaml.clib
info     libmamba Adding package record to repo ruamel_yaml
info     libmamba Adding package record to repo setuptools
info     libmamba Adding package record to repo six
info     libmamba Adding package record to repo sqlite
info     libmamba Adding package record to repo tk
info     libmamba Adding package record to repo toolz
info     libmamba Adding package record to repo tqdm
info     libmamba Adding package record to repo tzdata
info     libmamba Adding package record to repo ucrt
info     libmamba Adding package record to repo urllib3
info     libmamba Adding package record to repo vc
info     libmamba Adding package record to repo vc14_runtime
info     libmamba Adding package record to repo vs2015_runtime
info     libmamba Adding package record to repo wheel
info     libmamba Adding package record to repo win_inet_pton
info     libmamba Adding package record to repo xz
info     libmamba Adding package record to repo yaml
info     libmamba Adding package record to repo yaml-cpp
info     libmamba Adding package record to repo zlib
info     libmamba Adding package record to repo zstandard
info     libmamba Adding package record to repo zstd
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/conda-forge/win-64/repodata.json'
conda-forge/win-64                                          Using cache
info     libmamba All targets to download are cached
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/conda-forge/noarch/repodata.json'
conda-forge/noarch                                          Using cache
info     libmamba All targets to download are cached
info     libmamba All targets to download are cached
Channel: conda-forge[win-64,noarch], platform: win-64, prio: 1 : 0
Cache path:  C:\Users\ahribern\AppData\Local\mambaforge\pkgs\cache\5afe41e9.solv
info     libmamba Reading cache files 'C:\Users\ahribern\AppData\Local\mambaforge\pkgs\cache\5afe41e9.solv.*' for repo '
info     libmamba Attempting to read libsolv solv file "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\pkgs\\cache\\54
info     libmamba Expecting solv metadata : {"etag":"\"d5f5747e8c8ee0e640fdeaab2a5879cb\"","mod":"Thu, 14 Sep 2023 01:1}
info     libmamba Loaded solv metadata : {"etag":"\"d5f5747e8c8ee0e640fdeaab2a5879cb\"","mod":"Thu, 14 Sep 2023 01:10:3}
info     libmamba Metadata from solv are valid, loading successful
Channel: conda-forge[win-64,noarch], platform: noarch, prio: 1 : 0
Cache path:  C:\Users\ahribern\AppData\Local\mambaforge\pkgs\cache\09cdf8bf.solv
info     libmamba Reading cache files 'C:\Users\ahribern\AppData\Local\mambaforge\pkgs\cache\09cdf8bf.solv.*' for repo '
info     libmamba Attempting to read libsolv solv file "C:\\Users\\ahribern\\AppData\\Local\\mambaforge\\pkgs\\cache\\0h
info     libmamba Expecting solv metadata : {"etag":"\"984d5eb79bb88de2a8a91eebaf36ecb3\"","mod":"Thu, 14 Sep 2023 01:2}
info     libmamba Loaded solv metadata : {"etag":"\"984d5eb79bb88de2a8a91eebaf36ecb3\"","mod":"Thu, 14 Sep 2023 01:21:2}
info     libmamba Metadata from solv are valid, loading successful
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec certifi
info     libmamba Parsing MatchSpec certifi
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec python 3.11.*
info     libmamba Parsing MatchSpec pin-1
info     libmamba Adding job: pin-1
info     libmamba Parsing MatchSpec pin-1
info     libmamba Parsing MatchSpec pin-1
info     libmamba Adding job: pin-1

Pinned packages:
  - python 3.11.*


info     libmamba Problem count: 0
info     libmamba Found python in installed packages 3.11.5
Transaction

  Prefix: C:\Users\ahribern\AppData\Local\mambaforge

  All requested packages already installed

info     libmamba All targets to download are cached
INFO conda.core.link:__init__(210): initializing UnlinkLinkTransaction with
  target_prefix: C:\Users\ahribern\AppData\Local\mambaforge
  unlink_precs:

  link_precs:
```

**Comment by janxkoci** [comment] 2023-09-26 14:54
Duplicate of https://github.com/mamba-org/mamba/issues/803

**Closed** 2023-09-26 15:03 UTC
