### ISSUE TITLE
Command 'mamba' not found, did you mean:

### ISSUE THREAD

**Issue by jeanmonet** [mamba-org/mamba#1278] opened 2021-11-18 20:23 UTC
```bash
$ mamba update --all

Command 'mamba' not found, did you mean:

  command 'samba' from deb samba (2:4.13.14+dfsg-0ubuntu0.20.04.1)

Try: apt install <deb name>
```

Context:
- Ubuntu 20.04LTS
- mamba 0.18.0

What happened?
I updated from mamba 0.17.0 to 0.18.0 (with `mamba update --all`). The `mamba`  command disappeared immediately.

I removed mamba with conda. Reinstalled mamba 0.18.0 with conda. Same problem.

```bash
$ conda install mamba -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /path/to/miniconda_py39

  added / updated specs:
    - mamba


The following NEW packages will be INSTALLED:

  libmamba           conda-forge/linux-64::libmamba-0.18.0-h3985d26_0
  libmambapy         conda-forge/linux-64::libmambapy-0.18.0-py39h8bfa403_0
  mamba              conda-forge/linux-64::mamba-0.18.0-py39hfa8f2c8_0
  pybind11-abi       conda-forge/noarch::pybind11-abi-4-hd8ed1ab_3
  yaml-cpp           conda-forge/linux-64::yaml-cpp-0.6.3-he1b5a44_4


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done


$ mamba

Command 'mamba' not found, did you mean:

  command 'samba' from deb samba (2:4.13.14+dfsg-0ubuntu0.20.04.1)

Try: apt install <deb name>
```

Removed and installed mamba 0.17.0 with conda. The mamba command works again. Will not update to 0.18 until a fix is released.

**Comment by wolfv** [comment] 2021-11-18 23:51
Hi @jeanmonet sorry for the trouble! I think the issue is fixed with this PR (that adds back the symlink from `$PREFIX/condabin/mamba -> $PREFIX/bin/mamba`)

https://github.com/conda-forge/mamba-feedstock/pull/137

Will merge that once it's green, and hopefully that will fix this issue in the next two hours once the package is synced with the CDN.

**Comment by psobolewskiPhD** [comment] 2021-11-19 10:39
I can confirm the issue is resolved.
I reverted my conda base env last night and just now updated mamba again and everything is peachy.
Side note: this new version is 🔥🚀

**Comment by wolfv** [comment] 2021-11-19 12:10
Great! We're still fixing some smaller issues with additional log output but happy to hear that this is working!

**Closed by wolfv** 2021-11-19 12:10 UTC

**Comment by jeanmonet** [comment] 2021-11-19 15:11
Thank you for lightning-fast fix! I can confirm as well that the issue is resolved.

Slightly off topic: is there a configuration setting for less verbose output?

**Comment by wolfv** [comment] 2021-11-19 15:37
yes, we're fixing that right now! Will be released this (european) evening

**Comment by danyanim2006** [comment] 2022-11-17 12:33
Hi, 
I am facing a similar issue with Mamba. I installed Mamba using miniforge. 
https://github.com/conda-forge/miniforge#mambaforge
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
bash Mambaforge-$(uname)-$(uname -m).sh

When I try to create a new environment using "mamba create -n nameofmyenv <list of packages>", I am getting an error                        
Command 'mamba' not found, did you mean:
  command 'samba' from deb samba (2:4.15.9+dfsg-0ubuntu0.2)
Try: sudo apt install <deb name>

**Comment by jonashaag** [comment] 2022-11-17 14:27
Can you please open a new issue for this?

Did you restart the shell? Does `conda` work?
