### ISSUE TITLE
implement --force and other conda command line options 

### ISSUE THREAD

**Issue by dirkpetersen** [mamba-org/mamba#3139] opened 2024-01-18 06:30 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

force

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Some downstream projects use the conda --force option and assume that micromamba also has it 
e.g. https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/generic/conda.py#L87

This would not bomb out if Micromamba would simply implement these cli options and ignore them if they are not applicable or fill them with code later as time allows.

**Comment by jjerphan** [comment] 2024-12-06 12:37
Closing as duplicate of #3535 which is keeping track of discrepancies better.

**Closed by jjerphan** 2024-12-06 12:37 UTC
