### ISSUE TITLE
The 'micromamba env export' command does not include pip dependencies in the YAML output

### ISSUE THREAD

**Issue by zN3utr4l** [mamba-org/mamba#2521] opened 2023-05-08 11:07 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

Micromamba export lacks pip export pkgs

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

Currently, I've noticed that when I run the **micromamba env export -n test > environment.test.yml** command to export the Micromamba 'test' environment to a YAML file, **pip's dependencies** are not included in the YAML output. 

However, when using the same YAML file to create a new Conda environment with **micromamba create -f environment.test.yml**, the pip dependencies are correctly installed.

### mamba info / micromamba info

```shell
micromamba create -n test python=3.9 pip
micromamba activate test
pip install pandas matplotlib

micromamba env export -n test > environment.test.yml

name: test
channels:
- pkgs/main
dependencies:
- ca-certificates=2023.01.10=haa95532_0
- openssl=1.1.1t=h2bbff1b_0
- pip=23.0.1=py39haa95532_0
- python=3.9.16=h6244533_2
- setuptools=66.0.0=py39haa95532_0
- sqlite=3.41.2=h2bbff1b_0
- tzdata=2023c=h04d1e81_0
- vc=14.2=h21ff451_1
- vs2015_runtime=14.27.29016=h5e58377_2
- wheel=0.38.4=py39haa95532_0
```
```


### Logs

```shell
micromamba env export -n test > environment.test.yml -v
info     libmamba Loading single package record: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\ca-certificates-2023.01.10-haa95532_0.json"
info     libmamba Loading single package record: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\openssl-1.1.1t-h2bbff1b_0.json"
info     libmamba Loading single package record: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\pip-23.0.1-py39haa95532_0.json"
info     libmamba Loading single package record: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\python-3.9.16-h6244533_2.json"
info     libmamba Loading single package record: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\setuptools-66.0.0-py39haa95532_0.json"
info     libmamba Loading single package record: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\sqlite-3.41.2-h2bbff1b_0.json"
info     libmamba Loading single package record: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\tzdata-2023c-h04d1e81_0.json"
info     libmamba Loading single package record: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\vc-14.2-h21ff451_1.json"
info     libmamba Loading single package record: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\vs2015_runtime-14.27.29016-h5e58377_2.json"
info     libmamba Loading single package record: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\wheel-0.38.4-py39haa95532_0.json"
info     libmamba parsing history: "D:\\Users\\g.chirico\\envs\\test\\conda-meta\\history"
info     libmamba Parsing MatchSpec python=3.9
info     libmamba Parsing MatchSpec pip
```

### ~/.condarc

```yaml
channel_priority: strict
channels:
  - defaults
  - conda-forge
```

**Comment by jonashaag** [comment] 2023-05-08 11:32
Duplicate of https://github.com/mamba-org/mamba/issues/2008

**Closed by jonashaag** 2023-05-08 11:32 UTC
