### ISSUE TITLE
Typo in env yaml leads to "bad conversion" error with micromamba

### ISSUE THREAD

**Issue by johanneskoester** [mamba-org/mamba#1146] opened 2021-08-27 20:47 UTC
This env:

```
channels:
  - conda-forge
depencencies:
  - curl
```

Causes micromamba to simply say `bad conversion`, instead of displaying an error message explaining what's wrong.

**Comment by wolfv** [comment] 2021-10-02 06:44
I think this is basically a duplicate of https://github.com/mamba-org/mamba/issues/1136

**Closed by wolfv** 2021-10-02 06:44 UTC
