### ISSUE TITLE
mamba remove mss --force different to conda

### ISSUE THREAD

**Issue by ReimarBauer** [mamba-org/mamba#2263] opened 2023-02-03 09:27 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

remove 

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Reproducible with Conda

### Describe your issue

 **conda** 

conda remove mss --force

only the mss package gets removed

**mamba**

while mamba removes also all dependencies

### mamba info / micromamba info

```shell
active environment : base
    active env location : /home/reimar/miniconda3/envs/mssdev
            shell level : 2
       user config file : /home/reimar/.condarc
 populated config files : /home/reimar/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/reimar/miniconda3/envs/mssdev  (writable)
      conda av data dir : /home/reimar/miniconda3/envs/mssdev/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/reimar/miniconda3/envs/mssdev/pkgs
                          /home/reimar/.conda/pkgs
       envs directories : /home/reimar/miniconda3/envs/mssdev/envs
                          /home/reimar/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.8 Linux/5.15.0-10058-tuxedo tuxedo/22.04 glibc/2.35
                UID:GID : 30000:30003
             netrc file : None
           offline mode : False
```

### ~/.condarc

```yaml
channels:
  - conda-forge
  - defaults
```

**Comment by jonashaag** [comment] 2023-02-03 11:34
Dupe of https://github.com/mamba-org/mamba/issues/1523

**Closed by jonashaag** 2023-02-03 11:34 UTC
