### ISSUE TITLE
mamba install failure with current (fresh) anaconda install

### ISSUE THREAD

**Issue by chetmurthy** [mamba-org/mamba#1735] opened 2022-06-10 00:12 UTC
1. Installing on Debian 10 in a Linux container on a Chromebook, but this has failed on Ubuntu 18 also.
2. install Anaconda using: Anaconda3-2022.05-Linux-x86_64.sh
3. then `conda update -y --all`
4. then check that `conda-forge` is the current channel (and there are no others)
5. then `conda install -c conda-forge mamba`
6. wait interminably as conda fails to resolve dependencies, eventually saying
```
(base) chet@penguin:~$ conda install -c conda-forge mamba
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): / 
done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining bcrypt:  25%|██████████████████████████████████████████████▎                                                                                                                                         | 110/437 [07:07<1:04:57, 11.92s/- (base) chet@penguin:~$ 
```

Eventually it failed, but without an error-message.

**Comment by qlandman** [comment] 2022-06-10 08:26
Running into the same issue on Windows 10 with a fresh install of the latest version of Miniconda:

```
(base) PS C:\> conda install -c conda-forge mamba
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```
After the search for conflicts it just fails.

**Comment by z--m-n** [comment] 2022-06-10 11:30
The same occurred for a fresh miniconda3. Installing mamba _after_ updating conda fails, hinting at a mismatch with `conda=4.13.0`:
```
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (conda):

  - mamba -> conda[version='4.6.*,<4.13.0|4.6.*|4.7.*,<4.13.0|>=4.7.12,<4.13.0|>=4.8,<4.13.0|>=4.7.12,<4.8']
```

A simple fix (today) was to reinstall miniconda3 and add mamba **_before_** updating conda=4.12.0 to the newer version.

**Comment by jonashaag** [comment] 2022-06-10 12:12
Duplicate of https://github.com/mamba-org/mamba/issues/1724?

**Comment by chetmurthy** [comment] 2022-06-10 15:26
So if I understand correctly, the incompatibility can be resolved either by:

1. install mamba before updating conda (to 4.13.0)

2. (maybe?) pin conda at 4.12.0 ?

The latter seems like it ought to be safer?  B/c who knows what will happen with mamba and conda both installed but actually incompatible ?

**Comment by z--m-n** [comment] 2022-06-13 09:02
> B/c who knows what will happen with mamba and conda both installed but actually incompatible ?

Indeed not a pleasant thought, more about that in #1724 as @jonashaag pointed out. My understanding: once mamba is installed together with the last compatible conda (conda=4.12.0), the mamba requirements prevent an upgrade of conda (to conda=4.13) in that environment.

**Comment by adamcc** [comment] 2022-09-27 09:37
I have a similar issue, it's still running several hours later.
conda 4.14.0
anaconda 2022.05


```
% conda install mamba -n base -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for r-data.table r-memoise r-irkernel matplotlib r-formatr r-rcolorbrewer \ d
```

**Comment by wolfv** [comment] 2022-09-27 15:26
I really don't recommend using the Anaconda distribution. It's much better to start with `miniforge` or `mambaforge` (comes pre-installed with mamba), or `miniconda`: 

- https://github.com/conda-forge/miniforge
- https://docs.conda.io/en/latest/miniconda.html

**Comment by adamcc** [comment] 2022-09-28 02:40
OK, thanks. I've been using anaconda for a while. So should I uninstall anaconda before attempting to install mamba?

So I entered this:
'''
% conda install mamba -n base -c conda-forge
'''
and left it running overnight. I came back to a giant mess of conflict reports and the conclusion:
'''
…
Your installed version is: 10.16
% which mamba
mamba not found
'''

Is anaconda a problem in general, or mainly for mamba installation? In other words, could I re-install anaconda after installing mamba?

**Comment by jonashaag** [comment] 2022-09-29 20:18
We recommend to not use Anaconda at all and start from a fresh Mambaforge install (or just use Micromamba) and use Conda-forge only

**Comment by adamcc** [comment] 2022-09-30 04:54
Thanks @jonashaag for the guidance. That makes the decision easy to just stay with anaconda.

**Comment by jonashaag** [comment] 2022-09-30 05:50
Not sure what’s wrong with your Homebrew. You can use this after you’ve removed Conda: https://github.com/conda-forge/miniforge#mambaforge

**Comment by jonashaag** [comment] 2022-09-30 05:51
Sorry I meant this https://github.com/conda-forge/miniforge#unix-like-platforms

**Comment by adamcc** [comment] 2022-09-30 07:22
Thanks @jonashaag

**Comment by pmarcellino** [comment] 2022-11-01 19:07
I also had the same issue. I like starting with Anaconda as it has a large set of packages pre installed. Is there a similar way to start with mamba and a similar large list of packages?

**Comment by jonashaag** [comment] 2022-11-07 17:57
I'm not aware of any, and with #2086 we have an acute problem if being incompatible with Anaconda.

IMO for reproducible research and experiments it's much better to have a dedicated `environment.yml` for each project.

**Closed** 2022-11-07 17:58 UTC
Labels: documentation

**Comment by Karlheinzniebuhr** [comment] 2023-01-28 15:21
Same issue with fresh conda install on Win10

**Comment by kullrich** [comment] 2023-04-05 09:43
Same issue, on fresh OS, Ubuntu 22.04, latest anaconda

**Comment by AnnaWojciechowska** [comment] 2023-05-31 19:43
same, ubuntu 22.04
onda list anaconda
# packages in environment at /home/anna/Downloads/anaconda3:
#
# Name                    Version                   Build  Channel
anaconda-client           1.11.2          py310h06a4308_0  
anaconda-navigator        2.4.0           py310h06a4308_0  
anaconda-project          0.11.1          py310h06a4308_0  

i ended up with manual micromamaba installation

**Comment by jonashaag** [comment] 2023-05-31 20:40
Hi everyone, please stop adding new "I'm affected as well" comments that don't add any new insights.

Please check the [official installation guide](https://mamba.readthedocs.io/en/latest/installation.html) for our recommended way to install Mamba.
