### ISSUE TITLE
`mamba init` add powershell support

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1088] opened 2021-07-15 19:31 UTC
`mamba init` works for bash & zsh now. But not yet for powershell. Would be cool to add support for that, too.

**Comment by wolfv** [comment] 2022-09-30 11:08
I think we might have to reopen this since it is related to `mamba` and not `micromamba`. Mamba still doesn't have the `mamba activate` working on powershell :/

**Comment by jjerphan** [comment] 2024-10-14 15:41
Closing as a duplicate of https://github.com/mamba-org/mamba/issues/1717.

**Closed by jjerphan** 2024-10-14 15:41 UTC
Labels: type::feature-request
