### ISSUE TITLE
Requested feature: micromamba env update

### ISSUE THREAD

**Issue by nick-youngblut** [mamba-org/mamba#2563] opened 2023-06-04 16:34 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

micromamba env update

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

`micromamba env update` is not implemented. One can only use `mamba env update` for updating a conda env via a yaml file.

**Comment by jonashaag** [comment] 2023-06-04 18:42
Dupe of https://github.com/mamba-org/mamba/issues/1455

**Closed by jonashaag** 2023-06-04 18:42 UTC
