### ISSUE TITLE
KeyError with private channel packages

### ISSUE THREAD

**Issue by vdsbenoit** [mamba-org/mamba#655] opened 2021-01-11 16:21 UTC
mamba throws a KeyError when I try to install a package from my private channel.

I have a private channel in my `.condarc` that contains HTTP authentication credentials in it. Let's say my `.condarc` is the following :  
````yaml
channels:
  - https://username:pass@my-private-conda-repo.com/api/conda/conda
  - conda-forge
````
The package `my_package` only exists on my private channel. When I run  `mamba install my_package`, I get the following error : 
````
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 882, in exception_converter
        raise e
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 716, in do_call
        exit_code = install(args, parser, "install")
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 593, in install
        index,
      File "C:\Miniconda3\lib\site-packages\mamba\utils.py", line 254, in to_txn
        sdir = lookup_dict[split_anaconda_token(c)[0]]
    KeyError: 'https://username:pass@my-private-conda-repo.com/api/conda/conda/noarch'
````

I use mamba 0.7.6.

<details>
<summary>My setup info</summary>

````
  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Miniconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Miniconda3\python.exe
               CONDA_ROOT=C:\Miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\username
                     PATH=
             PSMODULEPATH=
         PYTHONIOENCODING=utf-8
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : base
    active env location : C:\Miniconda3
            shell level : 1
       user config file : C:\Users\username\.condarc
 populated config files : C:\Users\username\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://username:pass@my-private-conda-repo.com/api/conda/conda/win-64
                          https://username:pass@my-private-conda-repo.com/api/conda/conda/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\username\.conda\pkgs
                          C:\Users\username\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\username\.conda\envs
                          C:\Users\username\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.7.3 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
````
</details>

**Comment by vdsbenoit** [comment] 2021-01-11 16:32
I have tried to locate the regression. According to my tests, it was introduced between 0.7.4 and 0.7.5 : 

0.6.4 ok
0.7.1 ok
0.7.3 ok
0.7.4 ok
0.7.5 nok
0.7.6 nok

**Comment by wolfv** [comment] 2021-01-11 17:31
thanks @vdsbenoit 

I think we need proper tests for this! I'll make a pass soon.

**Comment by wenjuno** [comment] 2021-01-27 16:34
@wolfv Do you have any update on this? I need to use basic auth for our internal channels too and this issue prevents me from using mamba for that. I have looked a bit into the code and I think the problem is that the call `.url(with_credentials=False)` strips out both token and basic auth:
https://github.com/mamba-org/mamba/blob/24409390306cb8b9123561db2909350946f56a2a/mamba/utils.py#L242
However, the `lookup_dict` is later queried with url stripped out only the token but not basic auth with `split_anaconda_token`:
https://github.com/mamba-org/mamba/blob/24409390306cb8b9123561db2909350946f56a2a/mamba/utils.py#L254
I think we could use `remove_auth` to strip out the basic auth either before or after calling `split_anaconda_token`:
https://github.com/conda/conda/blob/e37cf84a57f935c578cdcea6ea034c80d7677ccc/conda/common/url.py#L376-L380
Alternatively, we could use `split_scheme_auth_token` to strip out both token and basic auth but we will need to reassemble the URL with the scheme part:
https://github.com/conda/conda/blob/e37cf84a57f935c578cdcea6ea034c80d7677ccc/conda/common/url.py#L306-L320
Does this sound right to you?

**Comment by wolfv** [comment] 2021-01-27 19:56
Yes that sounds good. A PR would be awesome

**Comment by wolfv** [comment] 2021-02-17 15:47
I believe this is now fixed, and we have tests to prevent it from happening again.  

Thanks for the bug report and please let me know if I am mistaken!

**Closed** 2021-02-17 15:46 UTC

**Comment by vdsbenoit** [comment] 2021-02-17 17:20
I confirm I do not have the issue anymore with mamba 0.7.14. Thank you !
