### ISSUE TITLE
Basic auth gets dropped from some network requests, leading to failures

### ISSUE THREAD

**Issue by johnhany97** [mamba-org/mamba#1132] opened 2021-08-17 19:08 UTC
In an internal setup, we have conda channels that require basic auth for access purposes. An example call to a repodata.json file would require us to hit:

```
https://:$TOKEN@host/channel/repodata.json
```

We therefore pass to mamba the following 2 args
```
mamba ... --override-channels -c https://:$TOKEN@host/channel1/repodata.json -c https://:$TOKEN@host/channel2/repodata.json
```

Initially, we were using mamba 0.9.0, but we wanted to bump to a later mamba to benefit from the improvements recently made to the solve mechanism. However, on bumping to the latest release, 0.15.2, we noticed that we started seeing errors manifesting as:

```
ERROR File not valid: file size doesn't match expectation "/tmp/caches/CONDA_PKGS_DIRS/future-0.18.2-py36h5fab9bb_3.tar.bz2"

Expected: 733415
```

That was the time we opened https://github.com/mamba-org/mamba/pull/1095 to get more logs. In the meantime, upon upping the verbosity, I noticed we always got a result of size 71 bytes, and a HTTP status code 401 for all these random packages.

At the same time, we had a `MambaSolver` implemented that uses the Python APIs and we noticed that one also started exhibiting 401s, though on downloading the repodata.json files.

These errors manifest from https://github.com/mamba-org/mamba/blob/0.15.2/mamba/utils.py#L100 with the exception:

```
Runtime Error: Multi-download failed.
```

From what we can tell, those 401s thrown from our server-side mean that the authorization header never got to the service.

We binary searched our way through mamba releases to find this broke between 0.9.0 and 0.9.2. We noticed that mamba 0.9.0 had the following spec for libcurl:
```
libcurl >=7.75.0,<8.0a0
```
while 0.9.2 had:
```
libcurl >=7.76.0,<8.0a0
```

So on attempting to install mamba 0.9.0, which we know doesn't exhibit this bug, in our environment, we required libcurl to be >=7.76.0 and we saw the bug come back again.

Given the above investigation, we believe the bug is in libcurl, though a little bit hard to pinpoint given the [amount of changes](https://curl.se/changes.html) made between 7.75.0 and 7.76.0.

We propose as a workaround that we downgrade libcurl in mamba, as we don't particularly leverage any newer feature from libcurl AFAICT until this is followed up on with curl.

N.B. I do suspect https://github.com/curl/curl/commit/27fb920abe23468b503f178bc62fdec3f29d3cf6 might be a relevant change, but I am not certain enough.

**Comment by johnhany97** [comment] 2021-08-17 19:09
Link to the PR with the workaround in the meantime so that mamba isn't blocked on investigating the libcurl issue https://github.com/mamba-org/mamba/pull/1131

**Comment by wolfv** [comment] 2021-08-18 08:32
hey, one thing we saw before is that user names with `@` worked before, but stopped to work at some point. The fix was to URL encode the username + token. Maybe that is the problem / solution here as well?

I am not sure that downgrading curl is the right course of action.

Can you try to see what works from the curl command line? You can also "emit" the corresponding C code by using `curl blabla --libcurl somefile.c` and then you could send me the contents so we can see what should be going on.

**Comment by johnhany97** [comment] 2021-08-24 14:52
Hey @wolfv - sorry for taking a while to come back on this one. I've stripped down our server to the most core version of it and still got the issues described above with the upgraded curl. So from there, I've gone ahead and put up https://github.com/mamba-org/mamba/pull/1141 which has a repro of the same bug we're seeing, using the examples provided from this repo.

We were also able to find that this issue only comes up when the connection is being re-used. This is not to say that if the connection was reused, the auth header is dropped, but more like -> we never saw this issue come up unless the connection was reused.

Notably, we saw that:
```
* Connection #4 to host localhost left intact
* Couldn't find host localhost in the (nil) file; using defaults
* Found bundle for host localhost: 0x7fbd8fd4a640 [serially]
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Transfer was pending, now try another
> GET /service/noarch/repodata.json HTTP/1.1
Host: localhost:8080
Accept: */*
Accept-Encoding: gzip, deflate, compress, identity
Content-Type: application/json
```
for a request that got a 401, but then saw
```
* Couldn't find host localhost in the (nil) file; using defaults
* Found bundle for host localhost: 0x7f8fe0e08f30 [serially]
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user ''
> GET /service/noarch/test-package-0.1-0.tar.bz2 HTTP/1.1
Host: localhost:8080
Authorization: Basic KG5pbCk6dGVzdA==
Accept: */*
```
for a successful, non 401, request.

It's interesting to see `* Server auth using Basic with user ''` show up in the successful one, but not in the failing one. And that seems to be the case for all the logs I have.

**Comment by syslaila** [comment] 2021-09-01 11:49
After investigating a little bit more, it seems the issue gets fixed by setting the "max_parallel_downloads" to 0, so using a new connection for each download. I was able to reproduce the issue and then the solution with the help of "testserver.sh". 
 I'll try to reproduce the issue in libcurl by matching the curl flags that mamba sets.

**Comment by robin-cls** [comment] 2022-03-29 09:35
Just for information, I had the same issues last year with my conda configuration (basic authentification through tokens). I tried the latest mambe version (mamba v0.22.1, libcurl v7.82.0) and it seems to work properly.

**Comment by robin-cls** [comment] 2022-03-29 09:39
I had the same problem last year : a multi-download error caused by a failed token authentification (my conda channels are stored in Artifactory, which asks for tokens). I tried upgrading to the latest mamba version (0.22.1 with libcurl 7.82.0) and it seems to solve the basic authentification problem.

**Comment by johnhany97** [comment] 2022-03-29 09:47
I should've remembered to close this issue. We indeed did resolve this in libcurl 7.82.0 and added a test in mamba to ensure this is caught moving forwards in https://github.com/mamba-org/mamba/pull/1569

**Closed** 2022-03-29 09:47 UTC
