### ISSUE TITLE
mamba env update installing into wrong path

### ISSUE THREAD

**Issue by buhrmann** [mamba-org/mamba#631] opened 2020-12-14 12:25 UTC
Hi, when using `mamba env update -n myenv --file requirements.yml`, and in an active `myenv` environment, the command creates a new nested environment. E.g. if my current environment is at `miniforge3/env/myenv`, then the command installs the desired packages in `miniforge3/env/myenv/env/myenv`,  which is not what conda does, and probably not what's expected. When no environment is activated (i.e. base), the update works correctly.

**Comment by wolfv** [comment] 2020-12-14 12:29
Do you have `mamba` installed in `myenv`? 

mamba needs to be _only_ in the base environment currently.

**Comment by buhrmann** [comment] 2020-12-14 12:34
Yes, that could be it. Sorry, didn't know!

**Comment by wolfv** [comment] 2020-12-14 12:35
yeah, it's a limitation of the way mamba and conda work together.

**Comment by buhrmann** [comment] 2020-12-14 12:51
Ok, thanks. I've got another problem with `mamba env update`, not sure whether to open a new issue. Basically, it seems to ignore the pinned file in `myenv/conda-meta/pinned`. If I do a normal `mamba install ... some_pkg`, in contrast, it is respected. I also tried with `mamba install --file requirements.yml`, but that command fails with`CondaValueError: could not parse 'name: myeny ...' and it seems it doesn't work with the usual conda yml structure (starting with name: prefix)?

**Comment by wolfv** [comment] 2020-12-14 13:56
indeed, there might be an issue since `mamba env` and `mamba create` are implemented differently (it's a historic artifact from conda ... )

PRs welcome!

**Comment by buhrmann** [comment] 2020-12-14 14:55
Sorry, just to confirm... there is currently no way to make `mamba env` respect the pinned file, nor for `mamba install` to consume a conda environment file, right? Just asking because the latter seems to be possible with micromamba, e.g.

**Comment by wolfv** [comment] 2020-12-14 14:58
yes, micromamba is a completley different implementation for the CLI where I removed the weird differences between "conda env" and "conda create".

For conda & mamba, it's true that `conda env` handles `yaml` files, and `conda create` text or explicit env files.

Disrespecting the pinnings is something that can be fixed in `mamba_env.py` (https://github.com/mamba-org/mamba/blob/master/mamba/mamba_env.py) by copying what we're doing in `mamba.py` to handle pinned specs.

**Comment by buhrmann** [comment] 2020-12-14 15:10
Ok, thanks. I was trying to write some install scripts that would use micromamba in production docker images, and mamba in local installs. But seems that for now that isn't possible since one only accepts conda environment yaml files, and the other only plain text files.

**Comment by Haydnspass** [comment] 2021-01-27 15:38
> Do you have `mamba` installed in `myenv`?
> 
> mamba needs to be _only_ in the base environment currently.

What works though is to just tell mamba where to create the environment via the `--prefix` flag.
The issue is, in cluster environments often you don't have write access to the base environment because it is managed centrally.
In this case you can just go with 
`mamba env create --prefix [conda_path]/envs/[new_env_name] -f [environment_file]`

**Comment by wolfv** [comment] 2021-03-12 09:29
Thanks for mentioning this trick @Haydnspass.

A PR to the docs / README would be greatly appreciated!

**Closed by wolfv** 2021-03-12 09:29 UTC
