### ISSUE TITLE
RFE: Allow requesting only specific packages from a channel

### ISSUE THREAD

**Issue by opoplawski** [mamba-org/mamba#3030] opened 2023-12-03 17:53 UTC
This is essentially a duplicate of conda/conda#13381 but I'm curious to get the mamba perspective.

Creating environments with conda-forge is very slow. However, I generally know exactly which packages I need from conda-forge. I think performance could be improved if you could do something like:
```
conda create -n myenv -c conda-forge[packages=scikit-umfpack,sunpy]
```
and the `conda-forge` channel would be immediately filtered down to only `scikit-umfpack` and `sunpy`.

I was inspired by looking at conda-metachannel (and filed regro/conda-metachannel#32). Not sure if there is any code there that would be of any use.

The issue I have is that I can't use `--strict-channel-priority` because a high priority channel has dropped updating a package so we must get it from a lower priority channel. But its presence breaks this. Being able to filter out packages from a channel might also be a useful thing for this.

**Comment by opoplawski** [comment] 2023-12-04 17:12
So, one issue I was having is that apparently the format for the requirements file is not the same as what you can pass on the command line.  So switching to:
```
mamba create -n test $(cat scipy39-intel-requirements-min.txt) -C --dry-run --override-channels -c intel -c main -c conda-forge
```
allows it to actually complete in 2 minutes with a max memory usage of 2600136 kb, which is not particularly slow, but is a lot of memory.

However, if I give it a repository containing only the packages I need from conda-forge, it completes in 11 seconds with a maximum memory usage of  only 162276 kb which I think is a notable improvement for both speed and memory.  So I still think being able to filter a repository on the fly would be useful thing.

But I don't think my initial proposal for options would work.  I think I would need something like:
```
mamba -c conda-forge[packages=scikit-umfpack,sunpy,...]
```

**Comment by jonashaag** [comment] 2023-12-04 17:37
It's unlikely we are going to implement something like this because it doesn't fix the root cause. The root cause is that we pass too many packages to the solver. There should be no help from the user needed.

**Comment by opoplawski** [comment] 2023-12-04 18:06
What are some other ways to fix the root cause of passing too many packages to the solver?

**Comment by jonashaag** [comment] 2023-12-04 18:12
Changes to the code :) See https://github.com/mamba-org/mamba/issues/2824

**Comment by opoplawski** [comment] 2023-12-05 17:08
It seems if the solver is worth it's salt, passing extraneous packages to it wouldn't really slow it down.  On the other hand, what this request is fundamentally about is trying to express a policy to restrict the set of packages to send to the solver - which is fundamentally at a higher level and needs to be expressed by the user.

I ultimately want what `--strict-channel-priority` expresses.  However I cannot use that because the intel channel has old packages that they stopped supporting (for example - pyzmq).  An alternative to the initial proposal would be to be able to exclude pkgs:
```
mamba -c intel[excludepkg=pyzmq,...]
```
Though I think once you have the ability to exclude packages from a channel, adding the ability to limit it to just a specific set should be fairly easily.

One possible way to handle this automatically might be in the case of restricting python to 3.9, to recognize that there are no pyzmq packages in the intel channel that are compatible with python 3.9 and so automatically filter it out from the channel.

**Comment by jonashaag** [comment] 2023-12-05 17:18
If you only want performance, what I described in #2824 should be sufficient.

**Comment by opoplawski** [comment] 2023-12-05 17:33
I don't just want performance (though that is important) - I also want to be able to express my channel priority within the real world conditions I'm presented with.  But I'll keep an eye on other improvements as well.  Thanks.

**Comment by jonashaag** [comment] 2023-12-05 17:46
Yeah unfortunately what you want is not supported by Conda currently. We don't make decisions of these kinds of feature requests here. You'll have to use some of the other channels.

I'll go ahead and close this since there is nothing actionable we can/will do here.

**Closed by jonashaag** 2023-12-05 17:46 UTC
Labels: type::feature-request
