### ISSUE TITLE
mamba install always throws RuntimeError: Found incorrect download

### ISSUE THREAD

**Issue by FHTMitchell** [mamba-org/mamba#779] opened 2021-03-17 15:52 UTC
Even after `conda`/`mamba clean -all`. Note this only happens on `mamba install` in an existing env, creating a new env with `mamba create` or `mamba env create` works fine. 

Full traceback of one instance below 

```
 Summary:

  Install: 42 packages
  Upgrade: 5 packages

  Total download: 31 MB

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

libgcc-ng                [>                   ] (--:--) Decompressing...
Extraction error
libstdcxx-ng             [=>                  ] (--:--) Decompressing...
Extraction error
openssl                  [=>                  ] (--:--) Decompressing...
Extraction error
click                    [>                   ] (--:--) Decompressing...
Extraction error
freetype                 [>                   ] (--:--) Decompressing...
Extraction error
libgomp                  [=>                  ] (--:--) Decompressing...
Extraction error
lz4-c                    [=>                  ] (--:--) Decompressing...
Extraction error
markupsafe               [=>                  ] (--:--) Waiting...
Extraction error
markupsafe               [=>                  ] (--:--) Waiting...
Extraction error
markupsafe               [=>                  ] (--:--) Waiting...
Extraction error
markupsafe               [=>                  ] (--:--) Decompressing...
Extraction error
Finished _libgcc_mutex                        (00m:00s)               3 KB     64 KB/s
Finished _openmp_mutex                        (00m:00s)              22 KB    532 KB/s
Finished cloudpickle                          (00m:00s)              29 KB    690 KB/s
Finished libblas                              (00m:00s)              11 KB    201 KB/s
Finished libgfortran-ng                       (00m:00s)              22 KB    356 KB/s
Finished msgpack-python                       (00m:00s)              92 KB      1 MB/s
Finished libwebp-base                         (00m:00s)             815 KB     12 MB/s
Finished partd                                (00m:00s)              20 KB    265 KB/s
Finished olefile                              (00m:00s)              33 KB    425 KB/s
Finished pyyaml                               (00m:00s)             192 KB      2 MB/s
Finished certifi                              (00m:00s)             143 KB      1 MB/s
Finished heapdict                             (00m:00s)               9 KB     83 KB/s
Finished liblapack                            (00m:00s)              11 KB     97 KB/s
Finished dask-core                            (00m:00s)             702 KB      6 MB/s
Finished tornado                              (00m:00s)             649 KB      5 MB/s
Finished cytoolz                              (00m:00s)             390 KB      3 MB/s
Finished zict                                 (00m:00s)              12 KB     88 KB/s
Finished locket                               (00m:00s)               9 KB     57 KB/s
Finished distributed                          (00m:00s)               1 MB      7 MB/s
Finished pillow                               (00m:00s)             679 KB      5 MB/s
Finished libcblas                             (00m:00s)              11 KB     66 KB/s
Finished dask                                 (00m:00s)               4 KB     25 KB/s
Finished toolz                                (00m:00s)              47 KB    268 KB/s
Finished bokeh                                (00m:02s)               8 MB     53 MB/s
Finished numpy                                (00m:05s)               6 MB     29 MB/s
Finished pandas                               (00m:07s)              12 MB     53 MB/s

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/fmitchel/.conda/envs/mamba/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/fmitchel/.conda/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 882, in exception_converter
        raise e
      File "/home/fmitchel/.conda/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/fmitchel/.conda/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "/home/fmitchel/.conda/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 716, in do_call
        exit_code = install(args, parser, "install")
      File "/home/fmitchel/.conda/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 572, in install
        downloaded = transaction.prompt(
    RuntimeError: Found incorrect download. Aborting
```

<details><summary>Environment</summary>
<p>

```
`$ /home/fmitchel/.conda/envs/mamba/bin/mamba --no-banner install pandas=1.2 dask --yes`

  environment variables:
                 CIO_TEST=<not set>
                  CONDARC=/home/fmitchel/.condarc
         CONDA_BUILD_PATH=/home/fmitchel/conda-bld
        CONDA_DEFAULT_ENV=mw-fs
                CONDA_EXE=/opt/miniconda/bin/conda
             CONDA_PREFIX=/home/fmitchel/.conda/envs/mw-fs
           CONDA_PREFIX_1=/home/fmitchel/.conda/envs/local
    CONDA_PROMPT_MODIFIER=(mw-fs)
         CONDA_PYTHON_EXE=/opt/miniconda/bin/python
               CONDA_ROOT=/opt/miniconda/
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
     KUBECTL_PLUGINS_PATH=/opt/krewplugins/bin
                  MANPATH=:/opt/puppetlabs/puppet/share/man
               MODULEPATH=/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/
                          usr/share/modulefiles
                     PATH=/home/fmitchel/.conda/envs/mw-fs/bin:/opt/miniconda/condabin:/opt/krew
                          plugins/bin:/home/fmitchel/.local/bin:/home/fmitchel/bin:/usr/share/Mo
                          dules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/googl
                          e/chrome:/opt/miniconda/bin:/opt/puppetlabs/bin:/var/lib/snapd/snap/bi
                          n:/home/fmitchel/.local/bin:/home/fmitchel/pyproj/python.scripts/bin:/
                          opt/pycharm-2020.2/bin:/opt/julia/julia-1.5.1/bin:/home/fmitchel/.carg
                          o/bin:/home/fmitchel/.local/bin:/home/fmitchel/pyproj/python.scripts/b
                          in:/opt/pycharm-2020.2/bin:/opt/julia/julia-1.5.1/bin:/home/fmitchel/.
                          cargo/bin
           PYTHONBUFFERED=1
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : mw-fs
    active env location : /home/fmitchel/.conda/envs/mw-fs
            shell level : 2
       user config file : /home/fmitchel/.condarc
 populated config files : /opt/miniconda/condarc
                          /home/fmitchel/.condarc
          conda version : 4.9.0
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/fmitchel/.conda/envs/mamba  (writable)
           channel URLs : <REDACTED>
          package cache : /home/fmitchel/.conda/envs/mamba/pkgs
                          /home/fmitchel/.conda/pkgs
       envs directories : /home/fmitchel/.conda/envs
                          /home/fmitchel/.conda/envs/mamba/envs
               platform : linux-64
             user-agent : conda/4.9.0 requests/2.24.0 CPython/3.8.5 Linux/4.18.0-193.14.3.el8_2.x86_64 rhel/8.2 glibc/2.28
                UID:GID : 1932638008:1932600513
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

```bash
$ mamba --version
mamba 0.8.0
conda 4.9.0
```

</p>
</details>

**Comment by nikhilweee** [comment] 2021-03-24 10:07
I face the same issue. Strange.

**Comment by gerrydevine** [comment] 2021-03-25 06:09
We are seeing the same thing using mamba to do a full "snakemake" install. We can however mamba install a snamkemake-minimal

**Comment by wolfv** [comment] 2021-03-26 08:43
Thanks for the bug reports! 

Can you run with `-v` on the command line to get additional log output? That should indicate which package fails.
Please post the output here or as a gist!

Will look into this asap.

**Comment by ACColin** [comment] 2021-03-29 00:18
I have the same issue with the installation of full snakemake (minimal works just fine)
installing with the following command `mamba create -c conda-forge -c bioconda -n snakemake snakemake`
See the link for the additional log output:
https://gist.github.com/ACColin/a05ebca8b8a924c3aabeb0faccfcaeed

See error at line 394:
`ERROR   Error when extracting package: /data/w0565/data1/Colin_AC/local/bin/miniconda3/pkgs/libiconv-1.16-h5Extraction error`

**Comment by wolfv** [comment] 2021-03-29 08:06
Thanks @ACColin I will try to fix that asap.

**Comment by wolfv** [comment] 2021-03-29 09:25
is it possible that

- mamba is run parallely?
- some other process modifies the pacakges in the cache?
- you're running out of disk space?

**Comment by wolfv** [comment] 2021-03-29 09:26
@FHTMitchell can you check if there are different versions of `libarchive` in the

- environment where you want to install
- base environment (where mamba is installed)?

**Comment by FHTMitchell** [comment] 2021-03-29 09:53
I think this may actually be the issue. So I don't edit my `base` environment because doing so required root. Instead I installed `mamba` in a different env called "mamba":

```
fmitchel@lonpwkd019 ~
$ conda activate base

(base) fmitchel@lonpwkd019 ~
$ conda list libarchive
# packages in environment at /opt/miniconda:
#
# Name                    Version                   Build
libarchive                3.3.3                h5d8350f_5
python-libarchive-c       2.8                     py37_13

(base) fmitchel@lonpwkd019 ~
$ conda activate mamba

(mamba) fmitchel@lonpwkd019 ~
$ conda list libarchive
# packages in environment at /home/fmitchel/.conda/envs/mamba:
#
# Name                    Version                   Build  Channel
libarchive                3.5.1                h899b81a_0    defaults
```

Then when I use `mamba` directly without activating the environment e.g. `~/.conda/envs/mamba/bin/mamba`, it uses the base `libarchive`, not the one included with mamba.

**Comment by ACColin** [comment] 2021-03-29 22:48
I checked in `/local/bin/miniconda3/pkgs/` and `libiconv-1.16-h5` is not present.
 * Disk space is fine
 * I checked and mamba is not running in parallel
 * I can't find other things affecting the package

**Comment by ACColin** [comment] 2021-03-31 02:01
If someone is running in the same issue as me there is an easy/fast solution.

First I'll share the problem again:
When running the command `mamba create -v -c conda-forge -c bioconda -n snakemake snakemake`
it throws the following error: `ERROR Error when extracting package: /data/w0565/data1/Colin_AC/local/bin/miniconda3/pkgs/libiconv-1.16-h5Extraction error`

For me the problem is that for some reason this package is absent in `/miniconda3/pkgs`
You can check the full command info here : https://gist.github.com/ACColin/4b1884cb2f1c67082b8a4cbfa65fe1d5 and look for `libiconv-1.16-h516909a_0`.

The issue is avoided and snakemake gets installed if, prior to the installation I download the package and put it manually in `/miniconda3/pkgs`. Download available here: https://anaconda.org/conda-forge/libiconv/files

I think the root of the issue in my case is that I work on a cluster and have two versions of `conda` available for installing things. One is a global install and needs sudo rights to update and modify and one is my local install. When installing snakemake with mamba the `libiconv-1.16-h516909a_0` is "found" in the global `conda` folders but the following steps tries to find it in my local `conda`.

Simply downloading the package and putting it myself in the `/pkgs` folder solved the issue.

Hope it helps someone.

**Comment by wenjuno** [comment] 2021-04-21 03:48
Hi everyone, I think this issue should be fixed as of mamba 0.11.1 if I'm correct about the root cause being the bug of handling package cache (#852). Can anyone confirm so we can close the issue? Thanks.

**Comment by mdehollander** [comment] 2021-04-30 12:33
I can confirm that with version `0.12.1` it works, I think I was on `0.9` before and ran into this issue. So it seems indeed fixed.

**Comment by adriendelsalle** [comment] 2021-06-04 11:10
Thanks for the feedbacks!

**Closed by adriendelsalle** 2021-06-04 11:10 UTC

**Comment by half-adder** [comment] 2022-07-21 02:32
for people in the future - i ran into this problem and it was my disk space

**Comment by raphaelobinna** [comment] 2024-05-02 08:27
> I think this may actually be the issue. So I don't edit my `base` environment because doing so required root. Instead I installed `mamba` in a different env called "mamba":
> 
> ```
> fmitchel@lonpwkd019 ~
> $ conda activate base
> 
> (base) fmitchel@lonpwkd019 ~
> $ conda list libarchive
> # packages in environment at /opt/miniconda:
> #
> # Name                    Version                   Build
> libarchive                3.3.3                h5d8350f_5
> python-libarchive-c       2.8                     py37_13
> 
> (base) fmitchel@lonpwkd019 ~
> $ conda activate mamba
> 
> (mamba) fmitchel@lonpwkd019 ~
> $ conda list libarchive
> # packages in environment at /home/fmitchel/.conda/envs/mamba:
> #
> # Name                    Version                   Build
> libarchive                3.5.1                h899b81a_0
> ```
> 
> Then when I use `mamba` directly without activating the environment e.g. `~/.conda/envs/mamba/bin/mamba`, it uses the base `libarchive`, not the one included with mamba.

This solved my issue.
 Creating an env called mamba using conda, Then activate the env and ran my mamba package installation
