### ISSUE TITLE
2.0.0rc0: `micromamba env update` cannot install packages into root prefix

### ISSUE THREAD

**Issue by pauldmccarthy** [mamba-org/mamba#3354] opened 2024-07-17 18:14 UTC
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

Expected environment not found at prefix

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Howdy,

Using `micromamba 2.0.0rc0` (commit 413285c7b76fbfa76fc501ac395dc8ef7caa00e1), the `micromamba env update` command does not seem to support installing packages into the `MAMBA_ROOT_PREFIX` directory.

I'm not actually sure if this workflow is officially supported with `micromamba`, as I cannot find a clear answer in the documentation. However, it does seem to be supported by `micromamba 1.5.8`, e.g. the following commands successfully install `bin/python` alongside `bin/micromamba`:

```
mkdir mm
cd mm
export MAMBA_ROOT_PREFIX=$(pwd)
curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
./bin/micromamba install -c conda-forge -p $(pwd) python=3.11
```

However, using the new `micromamba env update` command with `micromamba 2.0.0rc0` does not seem to work. For example, given this `environment.yml` file:

```
channels:
 - conda-forge
dependencies:
 - python 3.11
```

and running these commands (after installing `micromamba 2.0.0rc0` from commit 413285c7b76fbfa76fc501ac395dc8ef7caa00e1) into `mm200/bin/micromamba`):

```
cd mm200
export MAMBA_ROOT_PREFIX=$(pwd)
./bin/micromamba env update -p $(pwd) -f ../environment.yml
```

results in this error (full output below):

```
error    libmamba Expected environment not found at prefix: /home/paulmc/Downloads/micromamba/mm200
```

If I create a `conda-meta` directory before running `micromamba env update`, I seem to be able to trick the command into running, however it erroneously reports that the requested packages are already installed - running these commands:

```
mkdir conda-meta
./bin/micromamba env update -p $(pwd) -f ../environment.yml
```

results in this output (but no packages are installed):

```
conda-forge/noarch                                  15.5MB @   2.0MB/s  7.7s
conda-forge/linux-64                                36.2MB @   2.8MB/s 13.1s

Transaction

  Prefix: /home/paulmc/Downloads/micromamba/mm200

  All requested packages already installed


Transaction starting

Transaction finished

To activate this environment, use:

    micromamba activate base

Or to execute a single command in this environment, use:

    micromamba run -n base mycommand
```

Thanks!

### mamba info / micromamba info

```shell
libmamba version : 2.0.0
     micromamba version : 2.0.0
           curl version : libcurl/8.8.0 OpenSSL/3.3.1 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
       envs directories : /home/paulmc/Downloads/micromamba/mm200/envs
          package cache : /home/paulmc/Downloads/micromamba/mm200/pkgs
                          /home/paulmc/.mamba/pkgs
            environment : None (not found)
           env location : -
      user config files : /home/paulmc/.mambarc
 populated config files :
       virtual packages : __unix=0=0
                          __linux=6.5.0=0
                          __glibc=2.35=0
                          __archspec=1=x86_64-v3
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /home/paulmc/Downloads/micromamba/mm200
               platform : linux-64
```

### Logs

```shell
info     libmamba ****************** Backtrace Start ******************
debug    libmamba Loading configuration
trace    libmamba Compute configurable 'create_base'
trace    libmamba Compute configurable 'no_env'
trace    libmamba Compute configurable 'no_rc'
trace    libmamba Compute configurable 'rc_files'
trace    libmamba Compute configurable 'root_prefix'
trace    libmamba Get RC files configuration from locations up to HomeDir
trace    libmamba Configuration not found at '/home/paulmc/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/.conda/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.conda/condarc'
trace    libmamba Configuration not found at '/home/paulmc/.conda/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/condarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/micromamba/mm200/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/micromamba/mm200/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/micromamba/mm200/condarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/micromamba/mm200/.condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.mambarc'
trace    libmamba Configuration not found at '/var/lib/conda/condarc.d/'
trace    libmamba Configuration not found at '/var/lib/conda/condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.condarc'
trace    libmamba Configuration not found at '/etc/conda/.mambarc'
trace    libmamba Configuration not found at '/etc/conda/condarc.d/'
trace    libmamba Configuration not found at '/etc/conda/condarc'
trace    libmamba Configuration not found at '/etc/conda/.condarc'
trace    libmamba Update configurable 'no_env'
trace    libmamba Compute configurable 'envs_dirs'
trace    libmamba Compute configurable 'file_specs'
debug    libmamba No env 'name' specified in YAML spec file '/home/paulmc/Downloads/micromamba/environment.yml'
trace    libmamba Compute configurable 'spec_file_env_name'
trace    libmamba Compute configurable 'env_name'
trace    libmamba Compute configurable 'use_target_prefix_fallback'
trace    libmamba Compute configurable 'target_prefix'
trace    libmamba Get RC files configuration from locations up to TargetPrefix
trace    libmamba Configuration not found at '/home/paulmc/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/.conda/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.conda/condarc'
trace    libmamba Configuration not found at '/home/paulmc/.conda/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/condarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/micromamba/mm200/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/micromamba/mm200/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/micromamba/mm200/condarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/micromamba/mm200/.condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.mambarc'
trace    libmamba Configuration not found at '/var/lib/conda/condarc.d/'
trace    libmamba Configuration not found at '/var/lib/conda/condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.condarc'
trace    libmamba Configuration not found at '/etc/conda/.mambarc'
trace    libmamba Configuration not found at '/etc/conda/condarc.d/'
trace    libmamba Configuration not found at '/etc/conda/condarc'
trace    libmamba Configuration not found at '/etc/conda/.condarc'
trace    libmamba Update configurable 'no_env'
trace    libmamba Compute configurable 'relocate_prefix'
trace    libmamba Compute configurable 'target_prefix_checks'
error    libmamba Expected environment not found at prefix: /home/paulmc/Downloads/micromamba/mm200
critical libmamba Aborting.
info     libmamba ****************** Backtrace End ********************
```

### environment.yml

```yaml
channels:
 - conda-forge
dependencies:
 - python 3.11
```

**Comment by Hind-M** [comment] 2024-07-26 15:41
Thanks for reporting!
To help understand the issue, can you please check that in the same conditions, the same `micromamba` commands give different outputs? (between `1.5.8` and `2.0.0rc0`).
IIUC, you used `micromamba install` with `1.5.8` and `micromamba env update `with `2.0.0rc0`.
Thanks!

**Comment by pauldmccarthy** [comment] 2024-07-31 08:18
Hi @Hind-M, the `micromamba env update` command is not available in 1.5.8, so I used `micromamba install` as the nearest equivalent.

**Comment by Hind-M** [comment] 2024-07-31 15:57
Hum, that's very weird, because [micromamba 1.5.8](https://github.com/mamba-org/mamba/blob/1.x/libmamba/src/api/configuration.cpp#L746-L750) has the same code behind it as in [2.0](https://github.com/mamba-org/mamba/blob/main/libmamba/src/api/configuration.cpp#L831-L835) for this part.
If your `MICROMAMBA_ROOT_PREFIX` has initially no `conda-meta` directory in it, it should abort in both versions of `micromamba`, so the question is why it doesn't in the first case for you.
When you run the `install` command with `1.5.8`,  `MICROMAMBA_ROOT_PREFIX` doesn't have initially the `conda-meta` directory and it does after it finishes the install, is that it?

**Comment by Hind-M** [comment] 2024-08-01 09:00
Ok, so setting `MAMBA_ROOT_PREFIX` to `some-dir` (and not `MICROMAMBA_ROOT_PREFIX` which is not considered) and then trying to `install` or `env update` at `some-dir` using `-p` flag does create `conda-meta` directory in the env in both versions.

So if you do: 
```
export MAMBA_ROOT_PREFIX=$(pwd)
micromamba install -p $(pwd) some-spec -c conda-forge
```
It should work with the latest commit or the one you mentioned (https://github.com/mamba-org/mamba/commit/ca8cee50feb2a03816e3db2cfdae49d43b7143cb).

Can you please try it out?

**Comment by pauldmccarthy** [comment] 2024-08-01 09:23
Hi @Hind-M, sorry, my mistake! I accidentally set `MICROMAMBA_ROOT_PREFIX` instead of `MAMBA_ROOT_PREFIX`.

So `micromamba install -p ${MAMBA_ROOT_PREFIX} ...` *does* work with the build from commit ca8cee5).

However, I still experience the reported error with `micromamba env update` from a freshly installed `micromamba` binary:

```
cd ~/Downloads/

echo "channels:
 - conda-forge
dependencies:
 - python 3.11.*
 - ipython" > env.yml
 
mkdir -p test/bin
unzip micromamba-linux-64.zip
mv micromamba test/bin
chmod a+x test/bin/micromamba
export MAMBA_ROOT_PREFIX=$(pwd)/test
./test/bin/micromamba env update -f env.yml -p ${MAMBA_ROOT_PREFIX}
```

<details>

```
info     libmamba ****************** Backtrace Start ******************
debug    libmamba Loading configuration
trace    libmamba Compute configurable 'create_base'
trace    libmamba Compute configurable 'no_env'
trace    libmamba Compute configurable 'no_rc'
trace    libmamba Compute configurable 'rc_files'
trace    libmamba Compute configurable 'root_prefix'
trace    libmamba Get RC files configuration from locations up to HomeDir
trace    libmamba Configuration not found at '/home/paulmc/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/.conda/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.conda/condarc'
trace    libmamba Configuration not found at '/home/paulmc/.conda/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/condarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/test/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/test/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/test/condarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/test/.condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.mambarc'
trace    libmamba Configuration not found at '/var/lib/conda/condarc.d/'
trace    libmamba Configuration not found at '/var/lib/conda/condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.condarc'
trace    libmamba Configuration not found at '/etc/conda/.mambarc'
trace    libmamba Configuration not found at '/etc/conda/condarc.d/'
trace    libmamba Configuration not found at '/etc/conda/condarc'
trace    libmamba Configuration not found at '/etc/conda/.condarc'
trace    libmamba Update configurable 'no_env'
trace    libmamba Compute configurable 'envs_dirs'
trace    libmamba Compute configurable 'file_specs'
debug    libmamba No env 'name' specified in YAML spec file '/home/paulmc/Downloads/env.yml'
trace    libmamba Compute configurable 'spec_file_env_name'
trace    libmamba Compute configurable 'env_name'
trace    libmamba Compute configurable 'use_target_prefix_fallback'
trace    libmamba Compute configurable 'target_prefix'
trace    libmamba Get RC files configuration from locations up to TargetPrefix
trace    libmamba Configuration not found at '/home/paulmc/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.mamba/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/mamba/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/.conda/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.conda/condarc'
trace    libmamba Configuration not found at '/home/paulmc/.conda/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/condarc'
trace    libmamba Configuration not found at '/home/paulmc/.config/conda/.condarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/test/.mambarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/test/condarc.d'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/test/condarc'
trace    libmamba Configuration not found at '/home/paulmc/Downloads/test/.condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.mambarc'
trace    libmamba Configuration not found at '/var/lib/conda/condarc.d/'
trace    libmamba Configuration not found at '/var/lib/conda/condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.condarc'
trace    libmamba Configuration not found at '/etc/conda/.mambarc'
trace    libmamba Configuration not found at '/etc/conda/condarc.d/'
trace    libmamba Configuration not found at '/etc/conda/condarc'
trace    libmamba Configuration not found at '/etc/conda/.condarc'
trace    libmamba Update configurable 'no_env'
trace    libmamba Compute configurable 'relocate_prefix'
trace    libmamba Compute configurable 'target_prefix_checks'
error    libmamba Expected environment not found at prefix: /home/paulmc/Downloads/test
critical libmamba Aborting.
info     libmamba ****************** Backtrace End ********************
```

</details>


I also get some strange behaviour if I initialise the base environment with a `micromamba install` command before trying to run `micromamba env update`. The following command (just installing `python=3.11.*`) seems to work fine:

```
./test/bin/micromamba install -p ${MAMBA_ROOT_PREFIX} -c conda-forge "python=3.11.*"
```

<details>

```
conda-forge/noarch                                  15.8MB @   1.9MB/s  8.3s
conda-forge/linux-64                                36.6MB @   2.7MB/s 13.5s

error    libmamba Could not lock non-existing path '/home/paulmc/.mamba/pkgs'

Transaction

  Prefix: /home/paulmc/Downloads/test

  Updating specs:

   - python=3.11


  Package              Version  Build               Channel          Size
───────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex          0.1  conda_forge         conda-forge       3kB
  + _openmp_mutex          4.5  2_gnu               conda-forge      24kB
  + bzip2                1.0.8  h4bc722e_7          conda-forge     253kB
  + ca-certificates   2024.7.4  hbcca054_0          conda-forge     155kB
  + ld_impl_linux-64      2.40  hf3520f5_7          conda-forge     708kB
  + libexpat             2.6.2  h59595ed_0          conda-forge      74kB
  + libffi               3.4.2  h7f98852_5          conda-forge      58kB
  + libgcc-ng           14.1.0  h77fa898_0          conda-forge     842kB
  + libgomp             14.1.0  h77fa898_0          conda-forge     457kB
  + libnsl               2.0.1  hd590300_0          conda-forge      33kB
  + libsqlite           3.46.0  hde9e2c9_0          conda-forge     865kB
  + libuuid             2.38.1  h0b41bf4_0          conda-forge      34kB
  + libxcrypt           4.4.36  hd590300_1          conda-forge     100kB
  + libzlib              1.3.1  h4ab18f5_1          conda-forge      62kB
  + ncurses                6.5  h59595ed_0          conda-forge     887kB
  + openssl              3.3.1  h4bc722e_2          conda-forge       3MB
  + pip                   24.2  pyhd8ed1ab_0        conda-forge       1MB
  + python              3.11.9  hb806964_0_cpython  conda-forge      31MB
  + readline               8.2  h8228510_1          conda-forge     281kB
  + setuptools          71.0.4  pyhd8ed1ab_0        conda-forge       1MB
  + tk                  8.6.13  noxft_h4845f30_101  conda-forge       3MB
  + tzdata               2024a  h0c530f3_0          conda-forge     120kB
  + wheel               0.43.0  pyhd8ed1ab_1        conda-forge      58kB
  + xz                   5.2.6  h166bdaf_0          conda-forge     418kB

  Summary:

  Install: 24 packages

  Total download: 45MB

───────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] y

Transaction starting
pip                                                  1.2MB @ 752.4kB/s  1.5s
setuptools                                           1.5MB @ 622.7kB/s  2.3s
ncurses                                            887.5kB @ 945.4kB/s  0.9s
tk                                                   3.3MB @   1.0MB/s  3.2s
libgcc-ng                                          842.1kB @ 961.7kB/s  0.9s
libsqlite                                          865.3kB @ 680.8kB/s  1.3s
libgomp                                            456.9kB @ 742.6kB/s  0.6s
ld_impl_linux-64                                   707.6kB @ 838.8kB/s  0.8s
xz                                                 418.4kB @ 628.0kB/s  0.6s
readline                                           281.5kB @ 830.4kB/s  0.3s
bzip2                                              252.8kB @ 706.7kB/s  0.3s
tzdata                                             119.8kB @ 436.8kB/s  0.2s
ca-certificates                                    154.9kB @ 488.3kB/s  0.3s
libxcrypt                                          100.4kB @ 568.7kB/s  0.2s
libexpat                                            73.7kB @ 155.1kB/s  0.1s
libzlib                                             61.6kB @ 327.6kB/s  0.1s
libffi                                              58.3kB @  ??.?MB/s  0.1s
openssl                                              2.9MB @ 614.9kB/s  4.7s
libuuid                                             33.6kB @  ??.?MB/s  0.1s
libnsl                                              33.4kB @  ??.?MB/s  0.1s
wheel                                               58.0kB @  ??.?MB/s  0.1s
_libgcc_mutex                                        2.6kB @  ??.?MB/s  0.1s
_openmp_mutex                                       23.6kB @  ??.?MB/s  0.1s
python                                              30.9MB @   2.6MB/s 11.9s
Linking _libgcc_mutex-0.1-conda_forge
Linking ld_impl_linux-64-2.40-hf3520f5_7
Linking ca-certificates-2024.7.4-hbcca054_0
Linking libgomp-14.1.0-h77fa898_0
Linking _openmp_mutex-4.5-2_gnu
Linking libgcc-ng-14.1.0-h77fa898_0
Linking libffi-3.4.2-h7f98852_5
Linking openssl-3.3.1-h4bc722e_2
Linking libzlib-1.3.1-h4ab18f5_1
Linking libxcrypt-4.4.36-hd590300_1
Linking bzip2-1.0.8-h4bc722e_7
Linking ncurses-6.5-h59595ed_0
Linking xz-5.2.6-h166bdaf_0
Linking libuuid-2.38.1-h0b41bf4_0
Linking libnsl-2.0.1-hd590300_0
Linking libexpat-2.6.2-h59595ed_0
Linking tk-8.6.13-noxft_h4845f30_101
Linking libsqlite-3.46.0-hde9e2c9_0
Linking readline-8.2-h8228510_1
Linking tzdata-2024a-h0c530f3_0
Linking python-3.11.9-hb806964_0_cpython
Linking wheel-0.43.0-pyhd8ed1ab_1
Linking setuptools-71.0.4-pyhd8ed1ab_0
Linking pip-24.2-pyhd8ed1ab_0

Transaction finished

To activate this environment, use:

    micromamba activate base

Or to execute a single command in this environment, use:

    micromamba run -n base mycommand
```

</details>


But then if I follow this up with `micromamba env update` (recalling that my `env.yml` file contains both `python=3.11.*` and `ipython`), `micromamba` claims that all requested packages are already installed, which they are not:

```
./test/bin/micromamba env update -p ${MAMBA_ROOT_PREFIX} -f env.yml
```

```
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Transaction

  Prefix: /home/paulmc/Downloads/test

  All requested packages already installed


Transaction starting

Transaction finished

To activate this environment, use:

    micromamba activate base

Or to execute a single command in this environment, use:

    micromamba run -n base mycommand
```

**Comment by Hind-M** [comment] 2024-08-01 15:44
Yeah so `env update` has an expected behavior as we only allow initialization of an empty base/root folder with `install` command (creating implicitly the `conda-meta` directory).
I'm not sure if this was done on purpose or just omitted (will need to go deeper in the code history and be sure this is the behavior we want after discussing with the team).
Is this specific workflow (using `env update` on root prefix - since it wasn't available in `1.x`) something you feel is blocking/cumbersome for your use cases? (In that case, it would be a kind of feature request).

As for the `env update` after `install`, it seems to be the expected behavior as well. Since `ipython` was not installed in the first place, `env update` (same for `update`) will ignore it and considers all the requested packages as installed since it didn't have to update `python`(same version requested).

If you want the behavior you're expecting you may use `install` instead:
`./test/bin/micromamba install -p ${MAMBA_ROOT_PREFIX} -f env.yml`

**Comment by pauldmccarthy** [comment] 2024-08-01 17:37
Hi @Hind-M Aah ok, thanks for the explanation. I had assumed that `micromamba env update` would give the same behaviour as `conda env update` which does install and update all packages in the provided environment file (i.e. semantically speaking, it is the entire environment that gets updated, rather than just the packages that are already installed).  

Is this the case, i.e. is the `micromamba env update` command **not** intended to mimic `conda env update`?

I was not aware of the `micromamba install -f <envfile>` option - I'll have a play with this, as it should suffice for my needs.

**Comment by Hind-M** [comment] 2024-08-02 08:06
Hi @pauldmccarthy!
Since `micromamba env update` was recently added and not so much tested by users, I would say that not mimicking `conda env update` wasn't intentional (even if not all commands in (micro)mamba are intended to follow conda's behavior).
I will therefore open an issue for it and close this one :)
If anything else comes up, feel free to reopen this issue or another one if more specific.
Thanks!

**Closed by Hind-M** 2024-08-02 08:06 UTC

**Comment by pauldmccarthy** [comment] 2024-08-02 08:35
@Hind-M No problem, thanks for helping!
