### ISSUE TITLE
Mamba remove --force different than Conda

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1523] opened 2022-02-22 15:44 UTC
(Maybe a duplicate of #1521?)

```
$ mamba create -n test pyarrow
...
```

Mamba:

```
$ mamba remove -n test --dry-run --force arrow-cpp
...

  Removing specs:

   - arrow-cpp
...
  Remove: 60 packages
...
```

Conda:

```
$ conda remove -n test --dry-run --force arrow-cpp
...
The following packages will be REMOVED:

  arrow-cpp-7.0.0-py310hdcb6bdc_2_cpu
...
```

Micromamba: same as Conda

**Comment by timsnyder** [comment] 2022-02-26 17:56
I ran into this as well in the past couple of days.  My use case is to do `conda remove --force conda-build` as a precursor to doing `pip install -e <conda-build-clone>` when working on local conda-build changes to get it installed in development mode.  I like to force remove only conda-build so that all of it's dependencies are installed by conda/mamba and pip only does the development path magic for conda-build (since `conda develop` is part of conda-build).

**Comment by wolfv** [comment] 2022-02-26 18:31
You can use --only-deps for that (with install or create)

I'll take a look with the force modifier. This is all already much better with micromamba btw :) we need to make the same changes in mamba

**Comment by marimeireles** [comment] 2022-02-28 17:13
I can work on this later :)
If u think it's a good idea

**Comment by timsnyder** [comment] 2022-03-16 16:43
> You can use --only-deps for that (with install or create)

@wolfv, my case is very close to the one in the OP except that I'm wanting to do this to install a dev conda-build inside the conda-forge container and it already has conda-build installed in the environment.  The minimal way of getting it out is with `remove --force` or (as I was recently reminded) using `pip remove` and I usually forget about using `pip` because I never use it.

> This is all already much better with micromamba 

I'll have to give it a try.  I've been away from needing to worry about packaging for awhile doing other things.  It seems like mamba has come a long way in the past couple of years.

**Comment by megies** [comment] 2022-05-24 11:18
:+1:  `conda remove --force` is what I use to set up dev installs

```
$ conda create -n test obspy  # install all dependencies
$ conda remove --force obspy  # only remove the one package
$ pip install -e ~/git/obspy  # install from a git clone, not pulling in anything else via pip
```

**Comment by dhirschfeld** [comment] 2022-05-24 11:35
Duplicate of #412

**Comment by megies** [comment] 2022-05-24 12:09
@dhirschfeld yes, I don't have issues achieving this (`conda remove --force --offline obspy` doesn't do any resolutions), but I noted `mamba remove --help` is reusing conda's help and thus it's not in line with what mamba actually does. So thought I'd point it out again

**Comment by hmaarrfk** [comment] 2022-09-13 16:14
I think one challenge that is important to consider is people testing downstream dependencies. In this case `--only-deps` isn't really easy to use because mamba cannot be expected to work with all development installation setups.

For example, if package `foo` depends on `bar`, and you want to install a development version of `bar`. I typically follow:

1. Install package `foo`. This pulls in a released version of `bar`.
2. Then `conda uninstall --force --offline --yes bar` to just remove `bar`.
3. Then `pip install -e . -vv` in the `a` directory. OR just install the files with `cmake` or some other package manager. The possibilities are endless.

Honestly, I don't expect conda to really detect my development installation of `bar`. But I expect `python` or the dynamic linking process to detect things well.

The `conda uninstall --force --offline --yes` has been a command that I've really dedicated to muscle memory.

**Comment by megies** [comment] 2022-09-14 08:00
Yes, thats pretty much what I'm doing quite regularly. The main point of the ticket is probably.. mamba just uses conda's `--help` for `mamba remove` but the info just doesnt really represent what mamba does in many cases. At this point I'm just using conda for pretty much everything still but use mamba for installing stuff in existing envs.

**Comment by jonashaag** [comment] 2022-09-14 10:53
Note that this works as expected in Micromamba.

**Comment by truatpasteurdotfr** [comment] 2023-03-02 15:08
any progress for `mamba --force` ?

```
mamba info 
     active environment : py310-pytorch 
    active env location : /pasteur/appa/scratch/mambaforge/2023-03-02/envs/py310-pytorch 
            shell level : 1 
       user config file : /pasteur/appa/homes/tru/.condarc 
 populated config files : /pasteur/appa/scratch/mambaforge/2023-03-02/.condarc 
                          /pasteur/appa/homes/tru/.condarc 
          conda version : 23.1.0 
    conda-build version : not installed 
         python version : 3.10.9.final.0 
       virtual packages : __archspec=1=x86_64 
                          __glibc=2.28=0 
                          __linux=4.18.0=0 
                          __unix=0=0 
       base environment : /pasteur/appa/scratch/mambaforge/2023-03-02  (writable) 
      conda av data dir : /pasteur/appa/scratch/mambaforge/2023-03-02/etc/conda 
  conda av metadata url : None 
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64 
                          https://conda.anaconda.org/conda-forge/noarch 
          package cache : /pasteur/appa/scratch/mambaforge/2023-03-02/pkgs 
                          /pasteur/appa/homes/tru/.conda/pkgs 
       envs directories : /pasteur/appa/scratch/mambaforge/2023-03-02/envs 
                          /pasteur/appa/homes/tru/.conda/envs 
               platform : linux-64 
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.9 Linux/4.18.0-372.41.1.el8_6.x86_64 rhel/8.6 glibc/2.28 
                UID:GID : 2765:400 
             netrc file : None 
           offline mode : False 
```

```
(py310-pytorch) [tru@maestro-submit mambaforge-py310-pytorch]$ conda remove cuda-demo-suite --force -d 
 
## Package Plan ## 
 
  environment location: /pasteur/appa/scratch/mambaforge/2023-03-02/envs/py310-pytorch 
 
  removed specs: 
    - cuda-demo-suite 
 
 
The following packages will be REMOVED: 
 
  cuda-demo-suite-12.1.55-0 
 
 
 
DryRunExit: Dry run. Exiting. 
```
VS
```
(py310-pytorch) [tru@maestro-submit mambaforge-py310-pytorch]$ mamba remove cuda-demo-suite --force -d 
 ...
Removing specs: ['cuda-demo-suite'] 
Transaction 
 
  Prefix: /pasteur/appa/scratch/mambaforge/2023-03-02/envs/py310-pytorch 

  Removing specs: 
 
   - cuda-demo-suite 
 
...
  Summary: 

  Remove: 71 packages 
 
  Total download: 0 B 
 
```

**Comment by truatpasteurdotfr** [comment] 2023-03-02 15:11
```
(py310-pytorch) [tru@maestro-submit mambaforge-py310-pytorch]$ micromamba info

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


            environment : /pasteur/appa/scratch/mambaforge/2023-03-02/envs/py310-pytorch (active)
           env location : /pasteur/appa/scratch/mambaforge/2023-03-02/envs/py310-pytorch
      user config files : /pasteur/appa/homes/tru/.mambarc
 populated config files : /pasteur/appa/homes/tru/.condarc
       libmamba version : 1.3.1
     micromamba version : 1.3.1
           curl version : libcurl/7.87.0 OpenSSL/3.0.8 zlib/1.2.13 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=4.18.0=0
                          __glibc=2.28=0
                          __archspec=1=x86_64
               channels : 
       base environment : /pasteur/appa/homes/tru/micromamba
               platform : linux-64
(py310-pytorch) [tru@maestro-submit mambaforge-py310-pytorch]$ 
(py310-pytorch) [tru@maestro-submit mambaforge-py310-pytorch]$ micromamba remove cuda-demo-suite --force --dry-run

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

Transaction

  Prefix: /pasteur/appa/scratch/mambaforge/2023-03-02/envs/py310-pytorch

  Removing specs:

   - cuda-demo-suite


  Package            Version  Build  Channel     Size
───────────────────────────────────────────────────────
  Remove:
───────────────────────────────────────────────────────

  - cuda-demo-suite  12.1.55  0      nvidia       5MB

  Summary:

  Remove: 1 packages

  Total download: 0 B

───────────────────────────────────────────────────────


Dry run. Not executing the transaction.
```
as hinted

**Comment by jonashaag** [comment] 2023-03-02 18:43
No progress, do you want to try to come up with an initial draft for a patch?

**Comment by truatpasteurdotfr** [comment] 2023-03-02 21:27
The workaround using micromamba is good enough for me.
No idea where to start look at :P I found this entry while searching for a way to fix pytorch  excessive size packaging until their next release (which come with a smaller disk usage) is GA.

Meanwhile I will be using `micromamba create -y --no-deps --name xxxx --file my.yml`.

**Comment by ChrisBarker-NOAA** [comment] 2023-05-09 16:30
I really need mamba to respect the --force option for remove :-(

I'm not sure i have what it takes to fo a PR, but I may take a look if no one else iw working ont his.

**Comment by jonashaag** [comment] 2023-05-09 16:38
Probably no one working on it.

**Comment by jaimergp** [comment] 2023-09-20 10:25
See https://github.com/mamba-org/mamba/pull/2856

**Comment by megies** [comment] 2023-09-21 07:34
Kudos for the improvement @jaimergp. :+1: Bit rough how this was left as is for 1.5 years considering command line help wasn't matching the execution, but I know how it is.. too much to work on at all times.

**Closed** 2023-10-09 21:14 UTC
Labels: type::bug
